### ISSUE TITLE
Potential duplicate action is broken

### ISSUE THREAD

**Issue by sachinraja** [simple-icons/simple-icons#7104] opened 2022-01-28 05:18 UTC
Leaving this here mostly so others can take it if they're interested and so I don't forget about it. The potential duplicates action does not work most of the time. It usually falsy marks things as a duplicate or identifies the wrong issue as a duplicate.

**Comment by mondeja** [comment] 2022-01-28 09:42
Could you share what are the exact affectted issues @sachinraja? If the problem is that after excluding words the title is empty so it computes similarities with all the issues, should be fixed by https://github.com/wow-actions/potential-duplicates/pull/20

**Comment by sachinraja** [comment] 2022-01-28 17:53
That is one of the problems, but there are a lot where it did not identify a duplicate at all:
* https://github.com/simple-icons/simple-icons/issues/7081
* https://github.com/simple-icons/simple-icons/issues/7080
* https://github.com/simple-icons/simple-icons/issues/7070
* https://github.com/simple-icons/simple-icons/issues/7069
* https://github.com/simple-icons/simple-icons/issues/7031

There are others where it identified the wrong duplicate because of a word like `project`. Maybe this can be fixed by increasing the threshold?

**Comment by mondeja** [comment] 2022-02-04 12:55
I'm taking a look now. Seems that #7081 was added on August, but the potential duplicate action was added on October by #4817

**Comment by mondeja** [comment] 2024-02-27 18:08
This is no longer relevant. There are other issues with the action but this issue is currently noise, so closing it...

**Closed by mondeja** 2024-02-27 18:08 UTC
Labels: meta
