### ISSUE TITLE
Request: UiPath

### ISSUE THREAD

**Issue by driedsoba** [simple-icons/simple-icons#9852] opened 2023-11-13 13:07 UTC
### Brand Name

UiPath

### Website

https://www.uipath.com

### Popularity Metric

The similarweb rank is 25,990. See https://www.similarweb.com/website/uipath.com/#overview

### Official Resources for Icon and Color

https://brandguidelines.uipath.com

**Comment by driedsoba** [comment] 2023-11-13 13:08
Hello I am looking to raise a pr for this issue as my first open source contribution, please let me know if I can proceed thank you!

**Comment by Mvlprem** [comment] 2023-12-06 15:30
> Hello I am looking to work on this issue as my first open source contribution, please let me know if I can proceed thank you!

@driedsoba Yes you can, you don't have to be assigned.

**Comment by uncenter** [comment] 2024-04-28 00:38
Duplicate of #6802.

**Closed by uncenter** 2024-04-28 00:38 UTC
Labels: new icon
