### ISSUE TITLE
Huggingface

### ISSUE THREAD

**Issue by Blessian** [simple-icons/simple-icons#9483] opened 2023-09-03 08:09 UTC
### Brand Name

Huggingface

### Website

https://huggingface.co/

### Popularity Metric

https://github.com/huggingface

### Official Resources for Icon and Color

https://huggingface.co/brand

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-09-03 08:12
Duplicate of #6074

**Closed by adamrusted** 2023-09-03 08:12 UTC
Labels: new icon
