### ISSUE TITLE
Clip Studio Paint Icon request 

### ISSUE THREAD

**Issue by tkamran** [simple-icons/simple-icons#8678] opened 2023-05-21 20:32 UTC
### Brand Name

Clip Studio Paint

### Website

https://www.clipstudio.net/en/

### Popularity Metric

https://www.similarweb.com/website/clipstudio.net/#overview

### Official Resources for Icon and Color

![CSP](https://github.com/simple-icons/simple-icons/assets/61532118/1449e6d4-a8cc-4171-b7a6-853e7d1fb3e8)

### Additional Comments

There is another icon that has a gray/silver background which can also be used. Not sure about any licensing. 

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-23 12:43
Duplicate of #7656

**Closed by service-paradis** 2023-05-23 12:43 UTC
Labels: new icon
