### ISSUE TITLE
langchain logo request

### ISSUE THREAD

**Issue by choismne** [simple-icons/simple-icons#10791] opened 2024-04-08 15:55 UTC
### Brand Name

langchain

### Website

https://www.langchain.com/

### Popularity Metric

langchain.com 's global rank is 18734 and country rank is 13500
https://www.similarweb.com/website/langchain.com/

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2024-04-08 17:16
Duplicate of #9482

**Closed by service-paradis** 2024-04-08 17:16 UTC
Labels: new icon
