### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by zealjinwala** [simple-icons/simple-icons#7238] opened 2022-03-18 18:26 UTC
### Brand Name

Matlab

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

The Similarweb rank is 4,415. The link is: https://www.similarweb.com/website/mathworks.com/#overview

### Official Resources for Icon and Color

[None](https://commons.wikimedia.org/wiki/File:Matlab_Logo.png)

### Contributing

No

**Comment by sachinraja** [comment] 2022-03-19 02:04
See https://github.com/simple-icons/simple-icons/issues/5835#issuecomment-853626958

**Comment by sachinraja** [comment] 2022-03-19 02:05
Duplicate of #5835

**Closed by sachinraja** 2022-03-19 02:04 UTC
Labels: new icon
