### ISSUE TITLE
Request: Hardhat

### ISSUE THREAD

**Issue by Laughing0900** [simple-icons/simple-icons#11544] opened 2024-07-28 04:30 UTC
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=hardhat.org

global rank is # 403,805

### Official Resources for Icon and Color

none

**Comment by helloscoopa** [comment] 2024-10-06 17:02
Duplicate of https://github.com/simple-icons/simple-icons/issues/7026

**Closed** 2024-10-06 17:02 UTC
Labels: new icon
