### ISSUE TITLE
Formik is missing

### ISSUE THREAD

**Issue by ttcode10** [simple-icons/simple-icons#8631] opened 2023-05-12 02:00 UTC
### Brand Name

Formik

### Website

https://formik.org/

### Popularity Metric

Global rank 297,558, https://www.similarweb.com/website/formik.org/#overview

### Official Resources for Icon and Color

color: #2563E6, sorry I cannot find the SVG format logo, but here is the script from official website header:

```
<svg xmlns="http://www.w3.org/2000/svg" width="182" height="41" fill="none" viewBox="0 0 367 84"><path fill="#172B4D" d="M83.3701 59C83.0567 59 82.7747 58.8903 82.5241 58.671C82.3047 58.4203 82.1951 58.1383 82.1951 57.825V27.322C82.1951 26.9773 82.3047 26.6953 82.5241 26.476C82.7434 26.2253 83.0254 26.1 83.3701 26.1H105.225C105.57 26.1 105.852 26.2253 106.071 26.476C106.322 26.6953 106.447 26.9773 106.447 27.322V32.304C106.447 32.6487 106.322 32.9307 106.071 33.15C105.852 33.3693 105.57 33.479 105.225 33.479H90.8431V40.012H104.285C104.63 40.012 104.912 40.1373 105.131 40.388C105.382 40.6073 105.507 40.8893 105.507 41.234V46.216C105.507 46.5607 105.382 46.8427 105.131 47.062C104.912 47.2813 104.63 47.391 104.285 47.391H90.8431V57.825C90.8431 58.1383 90.7334 58.4203 90.5141 58.671C90.2947 58.8903 90.0127 59 89.6681 59H83.3701Z"></path><path fill="#172B4D" d="M124.787 59.47C120.338 59.47 116.828 58.389 114.259 56.227C111.69 54.065 110.327 50.8847 110.17 46.686C110.139 45.8087 110.123 44.4613 110.123 42.644C110.123 40.8267 110.139 39.4637 110.17 38.555C110.295 34.419 111.658 31.2387 114.259 29.014C116.891 26.758 120.4 25.63 124.787 25.63C129.142 25.63 132.62 26.758 135.221 29.014C137.853 31.2387 139.232 34.419 139.357 38.555C139.42 40.3723 139.451 41.7353 139.451 42.644C139.451 43.584 139.42 44.9313 139.357 46.686C139.2 50.8847 137.837 54.065 135.268 56.227C132.73 58.389 129.236 59.47 124.787 59.47ZM124.787 52.42C126.416 52.42 127.717 51.9343 128.688 50.963C129.659 49.9603 130.176 48.4407 130.239 46.404C130.302 44.5867 130.333 43.2863 130.333 42.503C130.333 41.7197 130.302 40.4507 130.239 38.696C130.176 36.6593 129.659 35.1553 128.688 34.184C127.717 33.1813 126.416 32.68 124.787 32.68C123.126 32.68 121.81 33.1813 120.839 34.184C119.868 35.1553 119.351 36.6593 119.288 38.696C119.257 39.5733 119.241 40.8423 119.241 42.503C119.241 44.195 119.257 45.4953 119.288 46.404C119.351 48.4407 119.868 49.9603 120.839 50.963C121.81 51.9343 123.126 52.42 124.787 52.42Z"></path><path fill="#172B4D" d="M145.93 59C145.616 59 145.334 58.8903 145.084 58.671C144.864 58.4203 144.755 58.1383 144.755 57.825V27.322C144.755 26.9773 144.864 26.6953 145.084 26.476C145.303 26.2253 145.585 26.1 145.93 26.1H158.855C162.991 26.1 166.218 27.04 168.537 28.92C170.887 30.8 172.062 33.4477 172.062 36.863C172.062 39.0563 171.545 40.9207 170.511 42.456C169.508 43.9913 168.114 45.182 166.328 46.028L172.673 57.496C172.767 57.684 172.814 57.8563 172.814 58.013C172.814 58.2637 172.72 58.4987 172.532 58.718C172.344 58.906 172.109 59 171.827 59H165.2C164.291 59 163.649 58.577 163.273 57.731L158.103 47.532H153.591V57.825C153.591 58.1697 153.465 58.4517 153.215 58.671C152.995 58.8903 152.713 59 152.369 59H145.93ZM158.808 40.623C160.155 40.623 161.173 40.294 161.863 39.636C162.583 38.9467 162.944 38.0067 162.944 36.816C162.944 35.6253 162.583 34.6697 161.863 33.949C161.173 33.2283 160.155 32.868 158.808 32.868H153.591V40.623H158.808Z"></path><path fill="#172B4D" d="M178.656 59C178.312 59 178.014 58.8903 177.763 58.671C177.544 58.4517 177.434 58.1697 177.434 57.825V27.322C177.434 26.9773 177.544 26.6953 177.763 26.476C178.014 26.2253 178.312 26.1 178.656 26.1H183.967C184.751 26.1 185.315 26.4447 185.659 27.134L193.743 41.61L201.874 27.134C202.219 26.4447 202.783 26.1 203.566 26.1H208.877C209.222 26.1 209.504 26.2253 209.723 26.476C209.974 26.6953 210.099 26.9773 210.099 27.322V57.825C210.099 58.1697 209.974 58.4517 209.723 58.671C209.504 58.8903 209.222 59 208.877 59H202.908C202.595 59 202.313 58.8903 202.062 58.671C201.843 58.4203 201.733 58.1383 201.733 57.825V40.717L196.657 50.023C196.25 50.7437 195.702 51.104 195.012 51.104H192.474C191.848 51.104 191.299 50.7437 190.829 50.023L185.8 40.717V57.825C185.8 58.1697 185.675 58.4517 185.424 58.671C185.205 58.8903 184.923 59 184.578 59H178.656Z"></path><path fill="#172B4D" d="M217.669 59C217.356 59 217.074 58.8903 216.823 58.671C216.604 58.4203 216.494 58.1383 216.494 57.825V27.275C216.494 26.9303 216.604 26.6483 216.823 26.429C217.074 26.2097 217.356 26.1 217.669 26.1H224.39C224.735 26.1 225.017 26.2097 225.236 26.429C225.455 26.6483 225.565 26.9303 225.565 27.275V57.825C225.565 58.1383 225.455 58.4203 225.236 58.671C225.017 58.8903 224.735 59 224.39 59H217.669Z"></path><path fill="#172B4D" d="M233.137 59C232.823 59 232.541 58.8903 232.291 58.671C232.071 58.4203 231.962 58.1383 231.962 57.825V27.322C231.962 26.9773 232.071 26.6953 232.291 26.476C232.51 26.2253 232.792 26.1 233.137 26.1H239.435C239.779 26.1 240.061 26.2253 240.281 26.476C240.5 26.6953 240.61 26.9773 240.61 27.322V37.568L248.929 27.04C249.273 26.4133 249.884 26.1 250.762 26.1H257.953C258.203 26.1 258.423 26.2097 258.611 26.429C258.83 26.617 258.94 26.8363 258.94 27.087C258.94 27.3377 258.877 27.5257 258.752 27.651L247.801 41.845L259.645 57.449C259.77 57.5743 259.833 57.7623 259.833 58.013C259.833 58.2637 259.723 58.4987 259.504 58.718C259.316 58.906 259.081 59 258.799 59H251.42C250.918 59 250.511 58.906 250.198 58.718C249.884 58.4987 249.665 58.2793 249.54 58.06L240.61 46.592V57.825C240.61 58.1383 240.5 58.4203 240.281 58.671C240.061 58.8903 239.779 59 239.435 59H233.137Z"></path><path fill="#4C9AFF" d="M282.3 59.47C279.01 59.47 276.534 58.4047 274.874 56.274C273.244 54.1433 272.367 51.4487 272.242 48.19L272.195 46.78L272.242 45.37C272.367 42.1427 273.26 39.4637 274.921 37.333C276.581 35.171 279.041 34.09 282.3 34.09C285.558 34.09 288.096 35.2493 289.914 37.568V26.711C289.914 26.3977 290.008 26.147 290.196 25.959C290.415 25.7397 290.681 25.63 290.995 25.63H293.11C293.423 25.63 293.674 25.7397 293.862 25.959C294.081 26.147 294.191 26.3977 294.191 26.711V57.919C294.191 58.2323 294.081 58.4987 293.862 58.718C293.674 58.906 293.423 59 293.11 59H291.089C290.775 59 290.525 58.906 290.337 58.718C290.149 58.4987 290.055 58.2323 290.055 57.919V55.898C288.269 58.2793 285.684 59.47 282.3 59.47ZM283.193 55.804C285.386 55.804 287.031 55.0833 288.128 53.642C289.224 52.1693 289.82 50.4303 289.914 48.425C289.945 48.0803 289.961 47.485 289.961 46.639C289.961 45.7617 289.945 45.1507 289.914 44.806C289.851 42.8947 289.24 41.2497 288.081 39.871C286.953 38.461 285.323 37.756 283.193 37.756C280.937 37.756 279.292 38.461 278.258 39.871C277.224 41.281 276.66 43.1297 276.566 45.417L276.519 46.78C276.519 52.796 278.743 55.804 283.193 55.804Z"></path><path fill="#4C9AFF" d="M309.193 59.47C305.746 59.47 303.083 58.4987 301.203 56.556C299.354 54.6133 298.367 52.0283 298.242 48.801L298.195 46.78L298.242 44.759C298.367 41.5317 299.37 38.9467 301.25 37.004C303.161 35.0613 305.809 34.09 309.193 34.09C312.577 34.09 315.209 35.0613 317.089 37.004C319 38.9467 320.019 41.5317 320.144 44.759C320.207 45.4483 320.238 46.122 320.238 46.78C320.238 47.438 320.207 48.1117 320.144 48.801C320.019 52.0283 319.016 54.6133 317.136 56.556C315.287 58.4987 312.64 59.47 309.193 59.47ZM309.193 55.945C311.198 55.945 312.781 55.3183 313.94 54.065C315.131 52.7803 315.773 50.9473 315.867 48.566C315.898 48.2527 315.914 47.6573 315.914 46.78C315.914 45.9027 315.898 45.3073 315.867 44.994C315.773 42.6127 315.131 40.7953 313.94 39.542C312.781 38.2573 311.198 37.615 309.193 37.615C307.188 37.615 305.59 38.2573 304.399 39.542C303.24 40.7953 302.613 42.6127 302.519 44.994L302.472 46.78L302.519 48.566C302.613 50.9473 303.24 52.7803 304.399 54.065C305.59 55.3183 307.188 55.945 309.193 55.945Z"></path><path fill="#4C9AFF" d="M333.949 59.47C330.596 59.47 327.98 58.53 326.1 56.65C324.22 54.7387 323.233 52.0753 323.139 48.66L323.092 46.78L323.139 44.9C323.233 41.4847 324.22 38.837 326.1 36.957C327.98 35.0457 330.596 34.09 333.949 34.09C336.205 34.09 338.1 34.4973 339.635 35.312C341.202 36.0953 342.361 37.0823 343.113 38.273C343.897 39.4637 344.32 40.6543 344.382 41.845C344.414 42.127 344.304 42.3777 344.053 42.597C343.834 42.8163 343.583 42.926 343.301 42.926H341.233C340.92 42.926 340.685 42.8633 340.529 42.738C340.372 42.5813 340.215 42.315 340.059 41.939C339.495 40.4037 338.711 39.3227 337.709 38.696C336.737 38.038 335.5 37.709 333.996 37.709C332.022 37.709 330.455 38.32 329.296 39.542C328.136 40.764 327.51 42.6283 327.416 45.135L327.368 46.78L327.416 48.425C327.51 50.9317 328.136 52.796 329.296 54.018C330.455 55.24 332.022 55.851 333.996 55.851C335.531 55.851 336.784 55.5377 337.756 54.911C338.727 54.253 339.495 53.1563 340.059 51.621C340.215 51.245 340.372 50.9943 340.529 50.869C340.685 50.7123 340.92 50.634 341.233 50.634H343.301C343.583 50.634 343.834 50.7437 344.053 50.963C344.304 51.1823 344.414 51.433 344.382 51.715C344.32 52.8743 343.897 54.0493 343.113 55.24C342.361 56.4307 341.202 57.4333 339.635 58.248C338.1 59.0627 336.205 59.47 333.949 59.47Z"></path><path fill="#4C9AFF" d="M356.379 59.47C354.217 59.47 352.384 59.1253 350.88 58.436C349.408 57.7153 348.311 56.9007 347.59 55.992C346.87 55.0833 346.509 54.3313 346.509 53.736C346.509 53.4227 346.619 53.1877 346.838 53.031C347.058 52.843 347.293 52.749 347.543 52.749H349.517C349.705 52.749 349.846 52.7803 349.94 52.843C350.066 52.9057 350.222 53.0467 350.41 53.266C351.131 54.1433 351.93 54.8327 352.807 55.334C353.716 55.8353 354.922 56.086 356.426 56.086C358.118 56.086 359.466 55.7727 360.468 55.146C361.502 54.5193 362.019 53.6107 362.019 52.42C362.019 51.6367 361.8 51.01 361.361 50.54C360.923 50.07 360.186 49.647 359.152 49.271C358.15 48.895 356.646 48.4877 354.64 48.049C351.914 47.4537 349.987 46.592 348.859 45.464C347.731 44.336 347.167 42.879 347.167 41.093C347.167 39.9337 347.512 38.8213 348.201 37.756C348.891 36.6593 349.909 35.782 351.256 35.124C352.635 34.4347 354.264 34.09 356.144 34.09C358.118 34.09 359.795 34.419 361.173 35.077C362.583 35.735 363.633 36.5027 364.322 37.38C365.043 38.2573 365.403 38.9937 365.403 39.589C365.403 39.871 365.294 40.106 365.074 40.294C364.886 40.482 364.651 40.576 364.369 40.576H362.583C362.145 40.576 361.831 40.4037 361.643 40.059C361.111 39.4637 360.656 39.0093 360.28 38.696C359.936 38.3513 359.419 38.0693 358.729 37.85C358.04 37.5993 357.178 37.474 356.144 37.474C354.609 37.474 353.434 37.803 352.619 38.461C351.805 39.0877 351.397 39.9337 351.397 40.999C351.397 41.657 351.57 42.221 351.914 42.691C352.259 43.1297 352.917 43.5527 353.888 43.96C354.86 44.336 356.301 44.7277 358.212 45.135C361.189 45.7617 363.288 46.6547 364.51 47.814C365.764 48.9733 366.39 50.4617 366.39 52.279C366.39 53.6263 365.999 54.8483 365.215 55.945C364.463 57.0417 363.32 57.9033 361.784 58.53C360.28 59.1567 358.479 59.47 356.379 59.47Z"></path><path fill="#172B4D" d="M38.8688 0L48.5628 5.57462L10.3866 27.5283L0.692639 21.9536L38.8688 0Z"></path><path fill="#172B4D" d="M48.9537 6.74507L11.0179 28.5506L11.0166 39.5831L48.9525 17.7776L48.9537 6.74507Z"></path><path fill="#172B4D" d="M33.6985 28.2757L11.0976 41.2669L11.0964 52.2997L33.6972 39.3084L33.6985 28.2757Z"></path><path fill="#172B4D" d="M25.0346 45.7171L11.0441 53.7592L11.0428 64.7922L25.0334 56.7501L25.0346 45.7171Z"></path><path fill="#172B4D" d="M0.00375833 23.0173L9.75474 28.622L9.75099 39.6571L0 34.0525L0.00375833 23.0173Z"></path><path fill="#172B4D" d="M0.0965426 35.6574L9.72924 41.1941L9.72548 52.2292L0.0927843 46.6926L0.0965426 35.6574Z"></path><path fill="#172B4D" d="M0.0922985 48.2214L9.72824 53.76L9.72423 65.523L0.0882924 59.9844L0.0922985 48.2214Z"></path><path fill="#172B4D" d="M21.5645 84L11.8705 78.4254L49.6134 56.7209L59.3073 62.2955L21.5645 84Z"></path><path fill="#172B4D" d="M11.102 77.4713L48.9809 55.6985L48.9821 44.666L11.1032 66.4388L11.102 77.4713Z"></path><path fill="#172B4D" d="M26.3002 55.9735L48.901 42.9822L48.9023 31.9495L26.3014 44.9407L26.3002 55.9735Z"></path><path fill="#172B4D" d="M34.9641 38.532L48.9546 30.4899L48.9558 19.457L34.9653 27.4991L34.9641 38.532Z"></path><path fill="#172B4D" d="M59.9962 61.3058L50.2453 55.7012L50.249 44.666L60 50.2706L59.9962 61.3058Z"></path><path fill="#172B4D" d="M59.9041 48.5947L50.2714 43.058L50.2751 32.0229L59.9078 37.5595L59.9041 48.5947Z"></path><path fill="#172B4D" d="M59.9077 36.0307L50.2717 30.4921L50.2756 18.9405L59.9116 24.479L59.9077 36.0307Z"></path></svg>
```

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-12 12:52
Duplicate of #8333

**Closed by service-paradis** 2023-05-12 12:52 UTC
Labels: new icon
