### ISSUE TITLE
PhotoPrism

### ISSUE THREAD

**Issue by AdrianMihalache** [simple-icons/simple-icons#9146] opened 2023-07-29 10:16 UTC
### Brand Name

PhotoPrism

### Website

https://www.photoprism.app/

### Popularity Metric

The Similarweb rank is: 353,755.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-07-29 18:00
Duplicate of #7820

**Closed by adamrusted** 2023-07-29 18:00 UTC
Labels: new icon
