### ISSUE TITLE
Request Sanity.io icon

### ISSUE THREAD

**Issue by ecabigting** [simple-icons/simple-icons#7251] opened 2022-03-22 06:12 UTC
### Brand Name

sanity

### Website

https://www.sanity.io/

### Popularity Metric

https://github.com/sanity-io

### Official Resources for Icon and Color

none

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-03-23 02:15
Duplicate of #6443

**Comment by sachinraja** [comment] 2022-03-23 02:15
You can still make a PR linking to that issue

**Closed by sachinraja** 2022-03-23 02:15 UTC
Labels: new icon
