### ISSUE TITLE
Request: Processing

### ISSUE THREAD

**Issue by taleroangel** [simple-icons/simple-icons#7393] opened 2022-05-08 06:01 UTC
### Brand Name

Processing

### Website

https://processing.org/

### Popularity Metric

648 Starts at GitHub in repo https://github.com/processing/processing4

### Official Resources for Icon and Color

svg: https://github.com/processing/processing-website/blob/main/src/images/logo-processing.svg

### Contributing

Yes

**Comment by sisp** [comment] 2022-05-12 14:37
Unfortunately, this brand does not meet any of the [popularity criteria](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon). Unless you can make a strong argument why it should be considered sufficiently popular nevertheless, I'm afraid it doesn't qualify for being added.

**Comment by service-paradis** [comment] 2022-05-16 17:57
Processing foundation already exists (https://simpleicons.org/?q=processing).

Also duplicate of #4885

**Closed by service-paradis** 2022-05-16 17:57 UTC
Labels: new icon
