### ISSUE TITLE
Request: Garuda Linux

### ISSUE THREAD

**Issue by aditya8Raj** [simple-icons/simple-icons#10902] opened 2024-05-05 19:27 UTC
### Brand Name

Garuda Linux

### Website

https://garudalinux.org/

### Popularity Metric

The Similarweb rank is: 157,245. See at https://www.similarweb.com/website/garudalinux.org/

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment] 2024-05-05 21:03
Duplicate of #6561.

**Closed by uncenter** 2024-05-05 21:03 UTC
Labels: new icon
