### ISSUE TITLE
Gofiber Icon

### ISSUE THREAD

**Issue by xenitane** [simple-icons/simple-icons#9228] opened 2023-08-07 06:21 UTC
### Brand Name

GoFiber

### Website

https://gofiber.io

### Popularity Metric

The github repository for [Gofiber Github](https://github.com/gofiber/fiber) has more than 27k stars.

### Official Resources for Icon and Color

svg: https://gofiber.io/assets/images/logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-08-07 12:42
Duplicate of #8170

**Closed by service-paradis** 2023-08-07 12:42 UTC
Labels: new icon
