### ISSUE TITLE
Request: Clip Studio Paint

### ISSUE THREAD

**Issue by xtrat3rrestrial** [simple-icons/simple-icons#10819] opened 2024-04-16 19:51 UTC
### Brand Name

Clip Studio Paint

### Website

https://www.clipstudio.net/en/

### Popularity Metric

28,000

### Official Resources for Icon and Color

https://www.clipstudio.net/view/img/common/main_visual/top_main_CSP_logo_bk.svg, color: '#231815', from website header

### Additional Comments

I created a smaller one without the words for easier implementation.
https://drive.google.com/file/d/1HWEmVsoAVH06yzga6RJCJISBcEc2t7Vv/view?usp=sharing

**Comment by service-paradis** [comment] 2024-04-17 15:28
Duplicate of #7656

**Closed by service-paradis** 2024-04-17 15:28 UTC
Labels: new icon
