### ISSUE TITLE
🍍 Pinia (Vue.js official state management library)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [simple-icons/simple-icons#8075] opened 2022-11-28 19:05 UTC
### Brand Name

Pinia

### Website

https://pinia.vuejs.org

### Popularity Metric

9.3k GitHub stars

https://github.com/vuejs/pinia

### Official Resources for Icon and Color

I already converted their logo over to a single-color path, at `0 0 24px 24px`

`M 16.949 5.229 c -0.148 -0.232 -0.648 -0.378 -1.322 -0.378 c -0.943 0 -2.223 0.284 -3.346 1.005 c 0.113 -2.785 -1.238 -5.525 -1.871 -5.604 c -0.012 -0.002 -0.021 -0.002 -0.033 -0.002 c -0.656 0 -2.577 2.23 -3.169 4.867 c -1.2 -1.209 -2.773 -1.795 -3.645 -1.795 c -0.257 0 -0.454 0.051 -0.56 0.152 c -0.536 0.511 -0.668 4.063 0.665 6.396 l 0 0 c -1.633 1.847 -2.668 4.592 -2.668 7.639 c 0 5.517 3.393 6.732 7.581 6.732 c 4.187 0 7.583 -1.216 7.583 -6.732 c 0 -2.305 -0.594 -4.437 -1.588 -6.138 C 16.541 9.468 17.355 5.872 16.949 5.229 z M 14.273 10.891 c -0.668 -1.007 -1.484 -1.836 -2.402 -2.427 c 0.146 -0.557 0.26 -1.189 0.348 -1.887 c 1.117 -0.857 2.496 -1.171 3.408 -1.171 c 0.496 0 0.762 0.087 0.852 0.136 c 0.02 0.09 0.037 0.318 -0.02 0.722 c -0.063 0.458 -0.193 0.985 -0.379 1.524 C 15.826 8.528 15.261 9.89 14.273 10.891 z M 7.511 7.567 c 0.004 -0.487 0.044 -1.039 0.121 -1.66 c 0.19 -1.555 0.919 -2.873 1.337 -3.521 c 0.576 -0.896 1.121 -1.403 1.367 -1.548 c 0.201 0.201 0.596 0.824 0.926 1.828 c 0.24 0.728 0.611 2.18 0.422 3.736 c -0.084 0.682 -0.188 1.27 -0.313 1.771 c -0.863 -0.457 -1.805 -0.707 -2.791 -0.707 C 8.218 7.468 7.86 7.502 7.511 7.567 z M 7.082 5.839 c -0.083 0.675 -0.127 1.297 -0.125 1.861 c -1.064 0.309 -2.045 0.916 -2.89 1.75 c -0.619 -1.164 -0.808 -2.515 -0.864 -3.257 c -0.043 -0.565 -0.038 -1.129 0.017 -1.587 c 0.048 -0.408 0.122 -0.629 0.162 -0.713 c 0.032 -0.008 0.089 -0.017 0.181 -0.017 c 0.388 0 1.092 0.161 1.904 0.614 C 5.934 4.751 6.543 5.21 7.082 5.839 z M 15.609 17.511 c 0 2.385 -0.65 4.016 -1.992 4.986 c -1.123 0.813 -2.725 1.192 -5.037 1.192 c -2.313 0 -3.913 -0.379 -5.036 -1.192 c -1.34 -0.971 -1.991 -2.602 -1.991 -4.986 c 0 -1.292 0.191 -2.546 0.569 -3.728 c 0.363 -1.136 0.881 -2.155 1.54 -3.029 c 1.327 -1.762 3.074 -2.732 4.918 -2.732 c 1.843 0 3.591 0.971 4.919 2.732 c 0.658 0.874 1.178 1.894 1.541 3.029 C 15.418 14.965 15.609 16.219 15.609 17.511 z M 8.34 16.189 c -0.07 0 -0.141 -0.005 -0.212 -0.013 c -0.471 -0.055 -0.827 -0.255 -1.058 -0.597 c -0.047 -0.069 -0.029 -0.164 0.041 -0.211 c 0.069 -0.047 0.163 -0.028 0.21 0.041 c 0.181 0.27 0.457 0.422 0.841 0.467 c 0.388 0.044 0.721 -0.052 1.017 -0.292 c 0.064 -0.052 0.16 -0.043 0.212 0.022 c 0.054 0.064 0.044 0.16 -0.021 0.212 C 9.067 16.065 8.722 16.189 8.34 16.189 z M 13.494 15.881 c 0 0.278 -0.484 0.503 -1.084 0.503 c -0.598 0 -1.082 -0.225 -1.082 -0.503 c 0 -0.083 0.043 -0.161 0.121 -0.23 c 0.088 0.017 0.18 0.024 0.275 0.021 c 0.287 -0.011 0.549 -0.119 0.754 -0.294 C 13.045 15.395 13.494 15.614 13.494 15.881 z M 5.525 15.711 c -0.034 0.276 -0.543 0.44 -1.137 0.367 s -1.047 -0.355 -1.014 -0.632 c 0.029 -0.237 0.411 -0.393 0.896 -0.385 c 0.231 0.218 0.546 0.348 0.889 0.335 c 0.061 -0.002 0.12 -0.009 0.178 -0.02 C 5.468 15.479 5.54 15.596 5.525 15.711 z M 11.648 13.507 c -0.516 0.018 -0.918 0.449 -0.898 0.963 c 0.018 0.515 0.449 0.918 0.963 0.899 c 0.516 -0.017 0.918 -0.449 0.898 -0.964 C 12.593 13.891 12.162 13.488 11.648 13.507 z M 11.359 14.625 c -0.195 0.008 -0.357 -0.145 -0.365 -0.339 c -0.006 -0.195 0.146 -0.358 0.34 -0.365 c 0.195 -0.007 0.357 0.146 0.365 0.34 C 11.705 14.455 11.552 14.619 11.359 14.625 z M 5.084 13.231 c -0.514 0.018 -0.917 0.449 -0.898 0.965 c 0.018 0.514 0.45 0.916 0.964 0.898 c 0.515 -0.018 0.917 -0.449 0.899 -0.965 C 6.03 13.615 5.599 13.214 5.084 13.231 z M 4.796 14.351 c -0.195 0.007 -0.358 -0.146 -0.365 -0.34 c -0.007 -0.195 0.146 -0.358 0.34 -0.364 c 0.195 -0.007 0.358 0.145 0.365 0.34 C 5.143 14.18 4.99 14.344 4.796 14.351 z M 6.759 22.101 c -0.054 0.052 -0.123 0.078 -0.192 0.078 c -0.073 0 -0.146 -0.029 -0.2 -0.086 l -1.681 -1.749 l -0.79 0.84 c -0.055 0.059 -0.128 0.088 -0.202 0.088 c -0.068 0 -0.136 -0.025 -0.189 -0.075 c -0.112 -0.104 -0.117 -0.28 -0.012 -0.392 l 0.809 -0.86 l -1.663 -1.73 c -0.106 -0.11 -0.103 -0.285 0.008 -0.392 c 0.11 -0.105 0.286 -0.103 0.392 0.008 l 1.644 1.711 l 1.179 -1.256 c 0.105 -0.111 0.28 -0.117 0.392 -0.012 c 0.112 0.105 0.117 0.28 0.012 0.393 l -1.198 1.274 l 1.7 1.77 C 6.872 21.82 6.868 21.995 6.759 22.101 z M 14.474 18.214 l -1.664 1.73 l 0.809 0.86 c 0.105 0.111 0.1 0.287 -0.012 0.392 c -0.053 0.05 -0.121 0.075 -0.189 0.075 c -0.074 0 -0.146 -0.029 -0.201 -0.088 l -0.789 -0.84 l -1.682 1.749 c -0.055 0.057 -0.127 0.086 -0.199 0.086 c -0.07 0 -0.139 -0.026 -0.193 -0.078 c -0.109 -0.105 -0.113 -0.28 -0.006 -0.391 l 1.699 -1.77 l -1.199 -1.274 c -0.104 -0.112 -0.098 -0.287 0.014 -0.393 s 0.285 -0.1 0.391 0.012 l 1.18 1.256 l 1.643 -1.711 c 0.107 -0.11 0.281 -0.113 0.393 -0.008 C 14.576 17.929 14.58 18.103 14.474 18.214 z M 10.289 9.653 l -1.291 1.291 l 0.787 0.785 c 0.107 0.109 0.107 0.284 0 0.393 c -0.055 0.055 -0.125 0.082 -0.195 0.082 c -0.072 0 -0.142 -0.027 -0.197 -0.082 l -0.786 -0.787 l -0.786 0.787 c -0.054 0.055 -0.125 0.082 -0.196 0.082 s -0.142 -0.027 -0.196 -0.082 c -0.108 -0.108 -0.108 -0.283 0 -0.393 l 0.787 -0.785 l -1.291 -1.291 c -0.108 -0.107 -0.108 -0.284 0 -0.393 c 0.109 -0.107 0.284 -0.107 0.392 0 l 1.291 1.291 l 1.29 -1.291 c 0.109 -0.107 0.283 -0.107 0.393 0 C 10.396 9.369 10.396 9.546 10.289 9.653 z`

Official brand color is `#FFD859`.

### Contributing

No

**Comment by service-paradis** [comment] 2022-11-28 19:53
Duplicate of #7498

**Closed** 2022-12-01 19:22 UTC
Labels: new icon, duplicate
