### ISSUE TITLE
Request: Optimizely

### ISSUE THREAD

**Issue by Thiez-64** [simple-icons/simple-icons#11524] opened 2024-07-24 15:25 UTC
### Brand Name

Optimizely

### Website

https://www.optimizely.com/

### Popularity Metric

Similarweb Global Rank: [62,642](https://www.similarweb.com/website/optimizely.com)

### Official Resources for Icon and Color

- SVG :https://www.optimizely.com/

**Comment by uncenter** [comment] 2024-07-24 20:48
As per https://www.optimizely.com/legal/website-terms-of-use/:

> Optimizely, the Optimizely logos, product/service names and other marks used by Optimizely from time to time are trademarks and the property of Optimizely. The appearance, layout, color scheme, and design of the Optimizely.com site are protected trade dress. You do not receive any right or license to use the foregoing.

I believe we will need to request permission from them before including this icon in our collection. Would you be willing to [reach out](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-permission) @Thiez-64?

**Comment by Thiez-64** [comment] 2024-07-25 14:18
I just sent the text example to Optimizely :
Dear [Brand Name],

I am contributing to the Simple Icons project on GitHub (https://github.com/simple-icons/simple-icons) and would like to add your brand's icon.
One of the maintainers has requested - as per your Terms and Conditions - that I reach out to formally obtain permission prior to accepting it into their collection.
Could you please let me know at your earliest convenience whether or not we are okay to include your brand's icon in the project?

Kind regards,

[Your name]

**Comment by uncenter** [comment] 2024-07-25 14:45
Did you change the brand name and your name?...

**Comment by Thiez-64** [comment] 2024-07-25 14:52
yes

**Comment by uncenter** [comment] 2024-12-05 03:09
Duplicate of #10511, sorry for catching this now 😅

**Closed by uncenter** 2024-12-05 03:09 UTC
Labels: new icon, permission required
