### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by prakhar-1005** [simple-icons/simple-icons#8099] opened 2022-12-03 11:40 UTC
### Brand Name

Wells Fargo

### Website

https://www.wellsfargo.com/

### Popularity Metric

The Similarweb ranking is 175. See https://www.similarweb.com/website/wellsfargo.com/#overview

### Official Resources for Icon and Color

https://www.wellsfargo.com/

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-11-08 06:48
Duplicate of #6338

**Closed** 2023-11-08 06:48 UTC
Labels: new icon, duplicate
