### ISSUE TITLE
Appium

### ISSUE THREAD

**Issue by marcusberger** [simple-icons/simple-icons#5795] opened 2021-05-28 11:22 UTC
**Brand Name:*Appium*
**Website:*https://appium.io/*
**Alexa rank:*https://www.alexa.com/siteinfo/appium.io*
  

**Official resources for icon and color:**

**Comment by adamrusted** [comment] 2021-05-28 11:37
Duplicate of #3385

**Closed by adamrusted** 2021-05-28 11:37 UTC
Labels: new icon
