### ISSUE TITLE
CodeBerg

### ISSUE THREAD

**Issue by Sonnenbrand** [simple-icons/simple-icons#3648] opened 2020-10-04 08:34 UTC
**Name:** Codeberg
**Website:**https://codeberg.org/
**Alexa rank:**364028
  

**Official resources for icon and color:** https://codeberg.org/Codeberg/Design/src/branch/master/logo-kit blue

**Comment by fschrempf** [comment] 2021-01-04 19:26
Duplicate of #3491

**Closed** 2021-01-04 19:55 UTC
Labels: duplicate, new icon
