### ISSUE TITLE
Request: Ocado

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#11322] opened 2024-06-24 16:57 UTC
### Brand Name

Ocado

### Website

https://www.ocado.com

### Popularity Metric

The Similarweb rank is 5,175.
https://www.similarweb.com/website/ocado.com

### Official Resources for Icon and Color

SVG: https://en.wikipedia.org/wiki/File:Ocado_Logo.svg
Color: `#454b4b`

**Comment by service-paradis** [comment] 2024-06-26 15:03
Duplicate of #10194, please search existing issue before opening new ones.

**Closed by service-paradis** 2024-06-26 15:03 UTC
Labels: new icon
