### ISSUE TITLE
Hugging Face icon is missing

### ISSUE THREAD

**Issue by NotShrirang** [simple-icons/simple-icons#9835] opened 2023-11-08 17:23 UTC
### Brand Name

Hugging Face

### Website

https://huggingface.co/

### Popularity Metric

SimilarWeb rank is 2,733.

### Official Resources for Icon and Color

color: FFD21E

**Comment by service-paradis** [comment] 2023-11-08 17:46
Duplicate of #6074

**Closed by service-paradis** 2023-11-08 17:46 UTC
Labels: new icon
