### ISSUE TITLE
Question - why is there a <title> element in the SVGs?

### ISSUE THREAD

**Issue by kpion** [simple-icons/simple-icons#1189] opened 2019-02-03 07:45 UTC
### Kind of issue 
  - [ ] Improvement
  - [ ] Bug
  - [x] Other, namely: question

### This issue concerns 
  - [ ] The NPM Package
  - [ ] The website
  - [x] Other, namely: icons themselves

### Description

This is just a question, probably stupid, as I'm not really experienced with SVG's and my google fu has failed me.

The question is - **why** do we have this <title> element in the files. Like e.g. here: 
``` 
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<title>ArtStation icon</title>
<path d="M0 17.723l2.027 3.505h.001a2.424 2.424 0 0 0 2.164 1.333h13.457l-2.792-4.838H0zm24 .025c0-.484-.143-.935-.388-1.314L15.728 2.728a2.424 2.424 0 0 0-2.142-1.289H9.419L21.598 22.54l1.92-3.325c.378-.637.482-.919.482-1.467zm-11.129-3.462L7.428 4.858l-5.444 9.428h10.887z"/></svg>
```

When I want to use this svg as `<svg>`, not `<img>`, I can see the title popping up on hover, which obviously isn't what I want / need. If I wanted - I would add it to the parent element.

I have many (also hypothetical) reasons I would like to use the svg as `<svg>`, one would be that I want to change a color of **one** element (a path) when hovering or 'checking' something. Just for fun, this is why they invented SVGs (among other things :) right? And I can't o.O

Here is an example of what I'm talking about:
https://codepen.io/anon/pen/zewXKE

Hover it, and you'll see I'm changing a 'fill' property of a path of my choice, pretty cool. Except there is this 'title' showing up, which I can't get rid of.

Yeah, I can use js, but that would be silly to use it just for this one purpose imo.

**Comment by ericcornelissen** [comment] 2019-02-03 18:38
For the `<title>`, it has to do with accessibility (read more [here](https://github.com/simple-icons/simple-icons/issues/1135#issuecomment-454674687)) but I get your frustration it popping up on hover. Depending on how you're using the icons it might be possible to find a solution for you.

As for the styling of one element. I see why you would do that with any random SVG, but not really why you would do that with the logo of some brand. That being said, I'm not necessarily against supporting it, how would you go about supporting that in the general case?

**Comment by kpion** [comment] 2019-02-03 20:20
Hi @ericcornelissen 

Thanks for the answer. I did prepare a much longer explanation about why I want to do what I want, but when I realized it took about 3 A4 pages, I thought this might be a bit too much.

So, in short: no, it's not about coloring these specific icons, What I really want is **one** way of adding icons to the websites I make, I'm not a designer, so I want to make my life easier :) I want to use the svg icons inside the **tag**, always, it doesn't matter if on a particular site I want to toy with coloring them or not. Well, I can also use svg sprite - no big difference here.

So Simple Icons, Font Awesome or XYZ, I just hoped I can put the svg, and call it a day. 

Now, in the issue you linked you said:  

> I tried to investigate why we're using `<title>` rather then aria-label but I was unsuccessful (...) 

Welcome to the club! 

> From the W3C's article it seems that we should use `<title>` rather then aria-label (...)

That is where a lot of my doubts start. I have a feeling this whole way of putting this is just wrong - here, in this context, it's not the image creator's competence / responsibility / business. It's the site/app creator's responsibility to provide the title. Can you imagine gif/png creators adds a 'title' tooltip to their files? And site's creator can't get rid of it / modify it? 

It's **my** responsibility :)

This is why I understand the recommendations completely differently. It's when you make an SVG **component**, which will later become a part of a larger SVG, you should provide a `<title>` for every single component. This makes sense (some). And this is why when it comes to accessibility, in this draft: https://w3c.github.io/writing-accessible-svg/accessible-svg.html they start with exactly this: components. The whole `<use>` thing. For example they say:

> Authors should include a desc element for each graphical **object defined in the defs** that they reference with a use element.

Emphasis mine.

This means that the whole discussion aria-xyz vs `<title>` seems pointless in case when we just want to use a single image and we do have the control over giving it a title. I might be wrong, but I have an impression, that the whole thing is a big misunderstanding. This rfc and the previous one is/was **not** about single icons. They are/were more about complex svgs "documents" the whole time.

I really tried hard to make it short... well, maybe next time :)

Thanks again for your answer and this project. When it comes to me, I'll just remove the `<title> `elements before I'll use the icons.

**Comment by kpion** [comment] 2019-02-04 07:06
@birjolaxew - thanks for the answer!

Well, let me express my opinion, even considering that I do agree with the "you can edit it, it's simple"' argument in 100%, and actually this is what I'm gonna do.

> Given the wide range of uses and ways to implement SVGs, that's not something we can provide.

And later:

> Depending on your needs you may want to embed the icons directly in your HTML (...) (or) icons using <img> tags (...) or you may want to take the SVG (...)

The thing is - I did not really suggest you to "provide" something, I just wanted you to **stop** providing something it's hard to find a purpose for. You say in the latter paragraph that those SVGs can be used in many different ways, OK, but then why limit those possible range of uses by intentionally **putting**  something into the files, something which makes troubles in so many use cases? 

My clients are in 30% non English speakers, and this just doesn't make any sense for me. The creator of a **document** is the one who's responsible for implementing the a11y - and i18n and l10n are among of the reasons why :) 

**I** have the tools to localize stuff, I was working hard on bringing them to life on any given project, but then it turns out a 'textual' hint is **hard coded** into an... image.... 

I spent ~12h in the last week trying to understand it, without success. I just still don't understand the reasoning behind **manual**, **hard coding** any **textual** information into an **image** in **one** arbitrary language, for... "accessibility" reasons  o.O 

I can't stop but now I have this image in my head :) 

![a11y](https://i.imgur.com/NLZ3E4V.jpg "Not really accessible IMO ¯\_(ツ)_/¯")

So sounds like pretty ineffectively spent 12 h :)

And yes, I do understand that my view point maybe be biased, because when it comes to using images my experience is very limited to apps and websites. But because of not knowing the other view points I can't have an unbiased opinion :)

Uff. That said I believe `aria-label` seems to be a perfect compromise. 

And thanks again for your details answer!

**Comment by birjolaxew** [comment] 2019-02-04 12:00
@kpion I don't really know what to tell you if you've spent 12h trying to figure out how to change/remove the `<title>`. As mentioned in my previous post, we do not provide an all-encompassing solution. If the specific document we provide does not fit your needs, then you are expected to modify it.

I'll be closing this in favor of #1191, as I feel everything relevant has been said - but please feel free to keep the discussion going if you have more to add.

**Closed by birjolaxew** 2019-02-04 12:00 UTC

**Comment by kpion** [comment] 2019-02-04 12:14
@birjolaxew 

>  if you've spent 12h trying to figure out how to change/remove the <title>

:( I tried to emphasize that I spent the time on understanding **why**, and the **purpose** of this `<title>` element, I hoped to get some clue from experts. Seems like interpreted my whole issue as **how**, which is understandable considering the nature of this communication channel.

Surely I should not treat this issue service as a way of doing my research / asking theoretical questions, but this is exactly what I did :)  And indeed, that wasn't the brightest of my ideas :)

So yes, lets leave it, and I'll try to find other ways to discuss this further.

Thank you for your time and thanks for #1191 - I'll be watching it :)

**Comment by ericcornelissen** [comment] 2019-02-04 13:36
Even though the issue is closed, I want to way in on two specific comments 🙂 

> The creator of a document is the one who's responsible for implementing the a11y - and i18n and l10n are among of the reasons why

I can get behind that. But there's plenty of creators that don't, and providing a default is better then nothing in my opinion.


> As mentioned in my previous post, we do not provide an all-encompassing solution, and do not expect our icons to be plug-and-play for every use case. If the specific document we provide does not fit your needs, then you are expected to modify it.

In this regard, we could expand the capabilities of our NPM package to allow users to more easily modify the icon. With [vue-simpleicons](https://github.com/sh7dm/vue-simpleicons) this is already done to some extend, but of course not everyone is using Vue (...and its not yet published to NPM).

And of course this does not help users of our website.

**Comment by birjolaxew** [comment] 2019-02-04 14:05
> I spent the time on understanding why, and the purpose of this <title> element, I hoped to get some clue from experts. Seems like you interpreted my whole issue as how, which is understandable considering the nature of this communication channel.

The purpose of the `<title>` element is been a11y. We've kind of flopped between different ways to implement a11y (mostly related to whether `aria-labelledby` is required), but [eventually found](https://github.com/simple-icons/simple-icons/issues/991#issuecomment-425357557) that all browsers/readers (and the SVG spec) supports a lone `<title>` as the first element as a way to give an SVG a machine-readable title.
