### ISSUE TITLE
New Icon: VB

### ISSUE THREAD

**Issue by chrimaho** [simple-icons/simple-icons#8211] opened 2023-01-04 00:17 UTC
### Brand Name

Microsoft Language: Visual Basic

### Website

https://learn.microsoft.com/en-us/dotnet/visual-basic/

### Popularity Metric

The SimilarWeb.com rank is 40. See: https://www.similarweb.com/website/microsoft.com
GitHub stars: 3.8k. See: https://github.com/vscode-icons/vscode-icons

### Official Resources for Icon and Color

SVG: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_vb.svg
Colour: `#00519a`

![](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_vb.svg)

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-01-09 14:51
Duplicate of #7562

**Closed by service-paradis** 2023-01-09 14:51 UTC
Labels: new icon, duplicate
