### ISSUE TITLE
matplotlib python library

### ISSUE THREAD

**Issue by mahmoud-shihab** [simple-icons/simple-icons#11738] opened 2024-09-08 17:50 UTC
### Brand Name

matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

 1400019 total downloads according to https://anaconda.org/anaconda/matplotlib

### Official Resources for Icon and Color

SVG: https://matplotlib.org/_static/images/documentation.svg
Color = #FFFFFF

**Comment by uncenter** [comment] 2024-09-08 17:54
Duplicate of #3410.

**Closed by uncenter** 2024-09-08 17:54 UTC
Labels: new icon
