### ISSUE TITLE
Add Alteryx Badge

### ISSUE THREAD

**Issue by quantumudit** [simple-icons/simple-icons#6075] opened 2021-07-03 21:45 UTC
![alteryx](https://user-images.githubusercontent.com/54057814/124367531-98562980-dc75-11eb-8c9c-6b0eb7fd888e.png)

**Brand Name:** Alteryx
**Website:** https://www.alteryx.com/
**Alexa rank:** 30,809
  

**Official resources for icon and color:** https://www.alteryx.com/

**Comment by service-paradis** [comment] 2021-07-04 18:34
Duplicate of #5469

**Closed by service-paradis** 2021-07-04 18:34 UTC
Labels: new icon
