### ISSUE TITLE
Icon Request - Nike 

### ISSUE THREAD

**Issue by adempus** [simple-icons/simple-icons#5526] opened 2021-04-23 06:11 UTC
**Brand Name:** Nike
**Website:** https://www.nike.com/
**Alexa rank:** 121.4 k

Kind of surprised given the popularity, and FILA icon is included. 🤔

**Comment by PeterShaggyNoble** [comment] 2021-04-23 09:03
Duplicate of #3585

**Closed by PeterShaggyNoble** 2021-04-23 09:03 UTC
Labels: new icon
