### ISSUE TITLE
Amazon Music Icon

### ISSUE THREAD

**Issue by MattBudz** [simple-icons/simple-icons#9268] opened 2023-08-12 11:17 UTC
### Brand Name

Amazon Music

### Website

https://music.amazon.com/

### Popularity Metric

The similarweb Global Rank is #6952 https://www.similarweb.com/website/music.amazon.com/#overview

### Official Resources for Icon and Color

svg in white: https://d5fx445wy2wpk.cloudfront.net/static/logo.svg
color: #25d1da, from website navbar

### Additional Comments

There are two variants of this icon, one in white, and one in #25d1da. 

### Contributing

No

**Comment by quantumflo** [comment] 2023-08-12 16:20
Kindly assign this to me.
Thanks :)

**Comment by PratyushJayachandran** [comment] 2023-08-13 21:24
Duplicate of #3163 and #7566
Maintainers take note: https://github.com/simple-icons/simple-icons/issues/3163#issuecomment-1626856049

**Closed** 2023-08-14 12:39 UTC
Labels: new icon, duplicate
