### ISSUE TITLE
Request: Axios

### ISSUE THREAD

**Issue by UnlikelyHero** [simple-icons/simple-icons#6812] opened 2021-11-01 21:30 UTC
### Brand Name

Axios

### Website

https://axios-http.com/

### Popularity Metric

The Alex rank is #59,480. Axios is a simple promise-based HTTP client for the browser and node.js. Axios provides a simple to use library in a small package with a very extensible interface. It's also a promise based making it popular for beginner Javascript programmers

### Official Resources for Icon and Color

None - I looked but wasn't able to find official resources

### Contributing

No

**Comment by service-paradis** [comment] 2021-11-01 21:33
Duplicate of #3821

PR: #5991

**Closed by service-paradis** 2021-11-01 21:33 UTC
Labels: new icon, potential duplicate
