### ISSUE TITLE
Spoj(sports-programming platform) icon.

### ISSUE THREAD

**Issue by malavindra5** [simple-icons/simple-icons#3813] opened 2020-11-04 13:06 UTC
**Name:** SPOJ
**Website:** https://www.spoj.com/
**Alexa rank:**#51,225
  

**Official resources for icon and color:**

**Comment by PeterShaggyNoble** [comment] 2021-01-07 09:57
Duplicate of #3505

**Closed by PeterShaggyNoble** 2021-01-07 09:57 UTC
Labels: new icon
