### ISSUE TITLE
MediaWiki Icon

### ISSUE THREAD

**Issue by iamenews** [simple-icons/simple-icons#11365] opened 2024-07-01 04:29 UTC
### Brand Name

MediaWiki

### Website

https://mediawiki.org

### Popularity Metric

MediaWiki is one of the most popular wiki software used by sites like wikipedia, fandom and more.  

### Official Resources for Icon and Color

https://www.mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines

**Comment by adamrusted** [comment] 2024-07-01 05:40
Duplicate of #5805.

See https://github.com/simple-icons/simple-icons/issues/5805#issuecomment-1819427225 for reasoning behind not including.

**Closed by adamrusted** 2024-07-01 05:40 UTC
Labels: new icon
