### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by iamRabia-N** [simple-icons/simple-icons#11471] opened 2024-07-14 15:32 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

https://www.similarweb.com/website/seaborn.pydata.org/#overview

### Official Resources for Icon and Color

![seaborn_svg](https://github.com/user-attachments/assets/6bb1fbfe-18ff-4c76-af74-7a3b79fb5533)

**Comment by uncenter** [comment] 2024-07-14 16:50
Duplicate of #6324. Please search existing issues before opening new ones.

**Closed by uncenter** 2024-07-14 16:50 UTC
Labels: new icon
