### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12027] opened 2024-10-16 09:18 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

Global Rank - 15169

### Official Resources for Icon and Color

https://seaborn.pydata.org/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment] 2024-10-16 10:01
Duplicate of #6324  - please check previous issues before raising new ones.

**Closed by adamrusted** 2024-10-16 10:01 UTC
Labels: new icon
