### ISSUE TITLE
Request: FedEx Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4335] opened 2020-12-13 04:53 UTC
**Name:** FedEx
**Website:** https://www.fedex.com/
**Alexa rank:**254
  

**Official resources for icon and color:** https://www.fedex.com/

**Comment by fbernhart** [comment] 2020-12-13 08:19
Duplicate of #3225

**Closed** 2020-12-13 08:19 UTC
Labels: duplicate, new icon
