### ISSUE TITLE
Request to add Seaborn Library used in Python

### ISSUE THREAD

**Issue by Vishal-Pattar** [simple-icons/simple-icons#11143] opened 2024-06-08 14:51 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

The data is available in https://www.similarweb.com/website/seaborn.pydata.org

### Official Resources for Icon and Color

![Seaborn](https://seaborn.pydata.org/_static/logo-wide-lightbg.svg)

**Comment by uncenter** [comment] 2024-06-08 14:57
Duplicate of #6324. Please search existing issues before opening a new one (and please follow the template we give you for the issue title!).

**Closed by uncenter** 2024-06-08 14:57 UTC
Labels: new icon, duplicate
