### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by M-Amrollahi** [simple-icons/simple-icons#8353] opened 2023-02-16 05:05 UTC
### Brand Name

matplotlib

### Website

https://matplotlib.org/stable/index.html

### Popularity Metric

the global rank is about 35,000.

### Official Resources for Icon and Color

https://matplotlib.org/stable/index.html

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-02-20 13:54
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed by service-paradis** 2023-02-20 13:54 UTC
Labels: new icon
