### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by Laxman-Lakhan** [simple-icons/simple-icons#7507] opened 2022-06-16 15:10 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org

### Popularity Metric

26306

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by sisp** [comment] 2022-06-16 19:38
Duplicate of #3410.

**Closed by sisp** 2022-06-16 19:38 UTC
Labels: new icon, duplicate
