### ISSUE TITLE
Folding@home

### ISSUE THREAD

**Issue by Brulijam** [simple-icons/simple-icons#11657] opened 2024-08-20 22:28 UTC
### Brand Name

Folding@home

### Website

https://foldingathome.org

### Popularity Metric

Similarweb Rank of 287,718 https://www.similarweb.com/website/foldingathome.org

### Official Resources for Icon and Color

https://foldingathome.org/wp-content/uploads/2016/09/cropped-folding-at-home-logo-1.png

**Comment by uncenter** [comment] 2024-08-20 22:29
Duplicate of https://github.com/simple-icons/simple-icons/issues/8553. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-08-20 22:29 UTC
Labels: new icon
