### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by BumbleIV** [simple-icons/simple-icons#6991] opened 2021-12-29 03:11 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

14.8k GitHub stars

### Official Resources for Icon and Color

https://matplotlib.org/stable/#

### Contributing

Yes

**Comment by adamrusted** [comment] 2022-01-03 17:49
Duplicate of #3410.

**Closed by adamrusted** 2022-01-03 17:49 UTC
Labels: duplicate
