### ISSUE TITLE
Livewire

### ISSUE THREAD

**Issue by antharuu** [simple-icons/simple-icons#6138] opened 2021-07-22 17:08 UTC
**Brand Name:** Livewire
**Website:** https://laravel-livewire.com/
**Alexa rank:** 14,850

**Official resources for icon and color:** Logo is available on the website, and color is #fb70a9

**Comment by antharuu** [comment] 2021-07-22 17:09
BASE SVG CODE
```html
<svg width="234px" height="54px" viewBox="0 0 234 54" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <path d="M6.21428571,3.96764549 L6.21428571,13.5302735 C6.21428571,15.2463011 4.82317047,16.6374164 3.10714286,16.6374164 C1.39111524,16.6374164 -2.95438243e-14,15.2463011 -2.97539771e-14,13.5302735 L-2.9041947e-14,1.98620229 C0.579922224,0.921664997 1.24240791,1.12585387e-13 2.43677218,1.0658141e-13 C4.3810703,1.0658141e-13 5.06039718,2.44244728 6.21428571,3.96764549 Z M17.952381,4.46584612 L17.952381,19.587619 C17.952381,21.4943164 16.4066974,23.04 14.5,23.04 C12.5933026,23.04 11.047619,21.4943164 11.047619,19.587619 L11.047619,2.47273143 C11.6977478,1.21920793 12.3678531,1.0658141e-13 13.7415444,1.0658141e-13 C15.916357,1.0658141e-13 16.5084695,3.05592831 17.952381,4.46584612 Z M29,4.18831009 L29,15.1664032 C29,16.8824308 27.6088848,18.2735461 25.8928571,18.2735461 C24.1768295,18.2735461 22.7857143,16.8824308 22.7857143,15.1664032 L22.7857143,1.67316044 C23.3267006,0.747223402 23.9709031,1.0658141e-13 25.0463166,1.0658141e-13 C27.0874587,1.0658141e-13 27.7344767,2.69181961 29,4.18831009 Z" id="path-100"></path>
        <path d="M6.21428571,6.89841791 C5.66311836,6.22351571 5.01068733,5.72269617 4.06708471,5.72269617 C1.82646191,5.72269617 1.41516964,8.5465388 1.66533454e-15,9.81963771 L4.4408921e-16,-2.36068323 C2.33936437e-16,-4.07671085 1.39111524,-5.46782609 3.10714286,-5.46782609 C4.82317047,-5.46782609 6.21428571,-4.07671085 6.21428571,-2.36068323 L6.21428571,6.89841791 Z M17.952381,7.11630262 C17.3645405,6.33416295 16.6773999,5.72269617 15.6347586,5.72269617 C13.1419388,5.72269617 12.9134319,9.21799873 11.047619,10.1843478 L11.047619,4.79760812 C11.047619,2.89091077 12.5933026,1.34522717 14.5,1.34522717 C16.4066974,1.34522717 17.952381,2.89091077 17.952381,4.79760812 L17.952381,7.11630262 Z M29,6.51179 C28.521687,6.04088112 27.9545545,5.72269617 27.2024325,5.72269617 C24.7875975,5.72269617 24.497619,9.0027269 22.7857143,10.086414 L22.7857143,-0.846671395 C22.7857143,-2.56269901 24.1768295,-3.95381425 25.8928571,-3.95381425 C27.6088848,-3.95381425 29,-2.56269901 29,-0.846671395 L29,6.51179 Z" id="path-300"></path>
    </defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="10.5″-iPad-Pro-Copy-6" transform="translate(-116.000000, -134.000000)">
            <g id="Group-3" transform="translate(115.000000, 136.000000)">
                <g id="Livewire" transform="translate(65.535000, 5.881000)" fill-rule="nonzero">
                    <path d="M3.38593404,35.0257215 C2.53791669,35.0257215 1.83909806,34.7847546 1.28945719,34.3028134 C0.739816315,33.8208723 0.465,33.129064 0.465,32.2273676 L0.465,4.38374623 C0.465,3.4820499 0.739816315,2.79801468 1.28945719,2.33162003 C1.83909806,1.86522538 2.53791669,1.63203155 3.38593404,1.63203155 C4.23395139,1.63203155 4.94062191,1.86522538 5.50596681,2.33162003 C6.07131171,2.79801468 6.35397992,3.4820499 6.35397992,4.38374623 L6.35397992,32.2273676 C6.35397992,33.129064 6.07131171,33.8208723 5.50596681,34.3028134 C4.94062191,34.7847546 4.23395139,35.0257215 3.38593404,35.0257215 Z M15.5030991,35.0257215 C14.6550818,35.0257215 13.9562632,34.7847546 13.4066223,34.3028134 C12.8569814,33.8208723 12.5821651,33.129064 12.5821651,32.2273676 L12.5821651,14.2246241 C12.5821651,13.3229278 12.8569814,12.6388926 13.4066223,12.1724979 C13.9562632,11.7061033 14.6550818,11.4729095 15.5030991,11.4729095 C16.3511165,11.4729095 17.057787,11.7061033 17.6231319,12.1724979 C18.1884768,12.6388926 18.471145,13.3229278 18.471145,14.2246241 L18.471145,32.2273676 C18.471145,33.129064 18.1884768,33.8208723 17.6231319,34.3028134 C17.057787,34.7847546 16.3511165,35.0257215 15.5030991,35.0257215 Z M15.5030991,7.32201783 C14.4352254,7.32201783 13.5872208,7.03441211 12.9590598,6.45919204 C12.3308988,5.88397198 12.016823,5.1299786 12.016823,4.1971893 C12.016823,3.2644 12.3308988,2.51817975 12.9590598,1.95850617 C13.5872208,1.39883259 14.4352254,1.119 15.5030991,1.119 C16.5395648,1.119 17.3797175,1.39883259 18.0235826,1.95850617 C18.6674476,2.51817975 18.9893753,3.2644 18.9893753,4.1971893 C18.9893753,5.1299786 18.6752995,5.88397198 18.0471385,6.45919204 C17.4189775,7.03441211 16.5709728,7.32201783 15.5030991,7.32201783 Z M40.7644674,13.1519218 C41.0157318,12.5922482 41.3533633,12.1724993 41.777372,11.8926626 C42.2013807,11.6128258 42.6646424,11.4729095 43.1671712,11.4729095 C43.8895564,11.4729095 44.5412637,11.7138764 45.1223126,12.1958176 C45.7033615,12.6777587 45.9938816,13.2762895 45.9938816,13.991428 C45.9938816,14.3645437 45.8996589,14.7376538 45.7112106,15.1107695 L36.9955203,33.1601523 C36.7128478,33.7509188 36.3124012,34.2017602 35.7941684,34.51269 C35.2759356,34.8236198 34.7027472,34.9790823 34.0745862,34.9790823 C33.4778333,34.9790823 32.904645,34.8236198 32.3550041,34.51269 C31.8053632,34.2017602 31.3892128,33.7509188 31.1065404,33.1601523 L22.3437382,15.1107695 C22.186698,14.7998398 22.108179,14.4422759 22.108179,14.0380672 C22.108179,13.3229288 22.4144029,12.7166248 23.0268599,12.2191372 C23.6393169,11.7216495 24.3381355,11.4729095 25.1233368,11.4729095 C26.2540266,11.4729095 27.0863274,12.0170284 27.6202643,13.1052826 L34.2159218,27.5168052 L40.7644674,13.1519218 Z M67.4863027,28.4962291 C68.0202396,28.4962291 68.4520938,28.6983304 68.7818783,29.1025391 C69.1116629,29.5067478 69.2765526,30.0508667 69.2765526,30.7349122 C69.2765526,31.6987945 68.6955124,32.5071998 67.5334146,33.1601523 C66.4655409,33.7509188 65.2563491,34.2250796 63.905803,34.5826488 C62.5552568,34.9402181 61.2675461,35.119 60.0426321,35.119 C56.3364822,35.119 53.3998736,34.0618547 51.2327182,31.9475322 C49.0655627,29.8332098 47.9820013,26.9416064 47.9820013,23.2726351 C47.9820013,20.9406619 48.4531149,18.8730099 49.3953564,17.0696173 C50.3375979,15.2662246 51.6645681,13.8670617 53.3763069,12.8720864 C55.0880456,11.8771112 57.0274636,11.379631 59.194619,11.379631 C61.2675503,11.379631 63.0734861,11.8304724 64.6124805,12.7321687 C66.151475,13.633865 67.344963,14.908658 68.1929803,16.5565857 C69.0409977,18.2045135 69.465,20.1477954 69.465,22.3864897 C69.465,23.7234877 68.868256,24.3919767 67.6747501,24.3919767 L53.7767575,24.3919767 C53.9652058,26.5373921 54.5776536,28.115337 55.6141192,29.1258587 C56.6505849,30.1363805 58.1581487,30.6416337 60.1368558,30.6416337 C61.1419134,30.6416337 62.0291775,30.5172637 62.7986747,30.2685199 C63.568172,30.0197761 64.4397323,29.6777585 65.4133818,29.2424568 C66.3556233,28.7449692 67.04659,28.4962291 67.4863027,28.4962291 Z M59.3359545,15.4838834 C57.734144,15.4838834 56.4542852,15.9813636 55.4963396,16.9763388 C54.5383941,17.9713141 53.9652058,19.4015695 53.7767575,21.2671481 L64.4240332,21.2671481 C64.3612171,19.3704766 63.8901034,17.932448 63.010678,16.9530192 C62.1312526,15.9735904 60.906357,15.4838834 59.3359545,15.4838834 Z" id="Combined-Shape" fill="#4E56A6"></path>
                    <path d="M105.166478,12.5404386 C105.386697,11.9639618 105.709156,11.5316107 106.133866,11.2433723 C106.558575,10.9551339 107.022602,10.8110169 107.52596,10.8110169 C108.249539,10.8110169 108.902322,11.0592185 109.484331,11.555629 C110.06634,12.0520396 110.35734,12.6685402 110.35734,13.4051495 C110.35734,13.8214938 110.278691,14.1897929 110.121391,14.5100578 L102.335098,33.1013413 C102.083419,33.7098446 101.69804,34.1742217 101.178952,34.4944866 C100.659863,34.8147515 100.085728,34.9748815 99.4565291,34.9748815 C98.8587905,34.9748815 98.3003851,34.8147515 97.7812963,34.4944866 C97.2622075,34.1742217 96.8768291,33.7098446 96.6251497,33.1013413 L91.0095806,19.3620465 L85.5827701,33.1013413 C85.3310907,33.7098446 84.9457123,34.1742217 84.4266235,34.4944866 C83.9075347,34.8147515 83.3333996,34.9748815 82.704201,34.9748815 C82.1064624,34.9748815 81.5401922,34.8147515 81.0053734,34.4944866 C80.4705546,34.1742217 80.0773114,33.7098446 79.825632,33.1013413 L72.0865283,14.5100578 C71.9292287,14.0937135 71.85058,13.7414274 71.85058,13.453189 C71.85058,12.7165797 72.1651746,12.0840661 72.7943732,11.555629 C73.4235717,11.027192 74.1156798,10.7629774 74.8707181,10.7629774 C75.4055368,10.7629774 75.8931584,10.9070944 76.3335974,11.1953328 C76.7740364,11.4835712 77.1043607,11.9159223 77.3245802,12.4923991 L82.8929597,27.1444443 L88.6029081,12.6365176 C88.8545875,12.0280143 89.2163713,11.5716437 89.6882702,11.2673921 C90.1601691,10.9631404 90.6792502,10.8110169 91.2455289,10.8110169 C91.8118076,10.8110169 92.3308886,10.9631404 92.8027875,11.2673921 C93.2746865,11.5716437 93.6364702,12.0280143 93.8881496,12.6365176 L99.6452877,27.1924838 L105.166478,12.5404386 Z M117.445226,35.022921 C116.595808,35.022921 115.895835,34.7747195 115.345286,34.2783089 C114.794738,33.7818983 114.519467,33.0693196 114.519467,32.1405515 L114.519467,13.5973074 C114.519467,12.6685393 114.794738,11.9639671 115.345286,11.4835698 C115.895835,11.0031725 116.595808,10.7629774 117.445226,10.7629774 C118.294644,10.7629774 119.002482,11.0031725 119.568761,11.4835698 C120.135039,11.9639671 120.418175,12.6685393 120.418175,13.5973074 L120.418175,32.1405515 C120.418175,33.0693196 120.135039,33.7818983 119.568761,34.2783089 C119.002482,34.7747195 118.294644,35.022921 117.445226,35.022921 Z M117.445226,6.48746259 C116.375589,6.48746259 115.526183,6.19122201 114.896985,5.59873198 C114.267786,5.00624195 113.953192,4.22961125 113.953192,3.2688166 C113.953192,2.30802195 114.267786,1.53939776 114.896985,0.962920972 C115.526183,0.386444182 116.375589,0.098210111 117.445226,0.098210111 C118.483404,0.098210111 119.324944,0.386444182 119.969873,0.962920972 C120.614801,1.53939776 120.937261,2.30802195 120.937261,3.2688166 C120.937261,4.22961125 120.622666,5.00624195 119.993468,5.59873198 C119.364269,6.19122201 118.514864,6.48746259 117.445226,6.48746259 Z M139.539423,10.7629774 C140.357382,10.6989244 141.0023,10.8750675 141.474199,11.2914118 C141.946098,11.7077562 142.182044,12.3322633 142.182044,13.164952 C142.182044,14.0296672 141.977558,14.6701874 141.568579,15.0865317 C141.1596,15.5028761 140.420302,15.7750971 139.350665,15.9032031 L137.934975,16.0473216 C136.078839,16.2394805 134.718218,16.8800006 133.85307,17.9689012 C132.987922,19.0578019 132.555354,20.4189072 132.555354,22.0522581 L132.555354,32.1405515 C132.555354,33.0693196 132.272219,33.7818983 131.70594,34.2783089 C131.139662,34.7747195 130.431824,35.022921 129.582406,35.022921 C128.732988,35.022921 128.033015,34.7747195 127.482466,34.2783089 C126.931917,33.7818983 126.656647,33.0693196 126.656647,32.1405515 L126.656647,13.549268 C126.656647,12.6525263 126.931917,11.9639671 127.482466,11.4835698 C128.033015,11.0031725 128.717258,10.7629774 129.535216,10.7629774 C130.353174,10.7629774 131.013823,10.995166 131.517182,11.45955 C132.020541,11.9239341 132.272216,12.5884738 132.272216,13.453189 L132.272216,15.3747687 C132.869955,13.9656032 133.758685,12.8767189 134.938432,12.1080832 C136.118179,11.3394475 137.431612,10.9070964 138.878768,10.8110169 L139.539423,10.7629774 Z M162.671793,28.2973921 C163.206612,28.2973921 163.639179,28.5055611 163.969509,28.9219055 C164.299838,29.3382498 164.465,29.898705 164.465,30.6032877 C164.465,31.5961089 163.883,32.4287851 162.718983,33.1013413 C161.649345,33.7098446 160.438156,34.1982412 159.085379,34.5665458 C157.732602,34.9348505 156.442765,35.119 155.215827,35.119 C151.503556,35.119 148.562097,34.0301157 146.391362,31.8523145 C144.220626,29.6745133 143.135275,26.6960946 143.135275,22.916969 C143.135275,20.5149823 143.607167,18.3852528 144.550965,16.5277165 C145.494763,14.6701802 146.823925,13.2290098 148.538491,12.2041622 C150.253057,11.1793145 152.195678,10.6668984 154.366414,10.6668984 C156.442769,10.6668984 158.251688,11.1312755 159.793224,12.0600437 C161.33476,12.9888119 162.53022,14.3018782 163.379638,15.9992821 C164.229056,17.6966859 164.653759,19.6983114 164.653759,22.0042186 C164.653759,23.3813576 164.056029,24.0699168 162.860552,24.0699168 L148.939603,24.0699168 C149.128363,26.2797445 149.741822,27.9050644 150.78,28.9459252 C151.818177,29.9867861 153.328231,30.5072087 155.310207,30.5072087 C156.316924,30.5072087 157.205654,30.3791047 157.976422,30.1228928 C158.74719,29.8666809 159.62019,29.5143948 160.595448,29.066024 C161.539246,28.5536002 162.231354,28.2973921 162.671793,28.2973921 Z M154.507982,14.8943737 C152.903526,14.8943737 151.621553,15.4067899 150.662025,16.4316375 C149.702498,17.4564851 149.128363,18.9296815 148.939603,20.8512708 L159.604465,20.8512708 C159.541546,18.897655 159.069654,17.4164521 158.188776,16.4076177 C157.307898,15.3987834 156.080979,14.8943737 154.507982,14.8943737 Z" id="Combined-Shape-Copy" stroke="#4E56A6"></path>
                </g>
                <g id="Jelly" style="transform: translateY(-2.35208%);">
                    <path d="M46.7606724,33.2469068 C45.9448607,34.4803214 45.3250477,36 43.6664081,36 C40.8749581,36 40.7240285,31.6956522 37.9310842,31.6956522 C35.1381399,31.6956522 35.2890695,36 32.4976195,36 C29.7061695,36 29.55524,31.6956522 26.7622957,31.6956522 C23.9693513,31.6956522 24.1202809,36 21.3288309,36 C18.537381,36 18.3864514,31.6956522 15.5935071,31.6956522 C12.8005628,31.6956522 12.9514923,36 10.1600424,36 C9.2827466,36 8.66625943,35.5748524 8.14660082,34.9917876 C6.14914487,31.5156333 5,27.4421238 5,23.0869565 C5,10.3363825 14.8497355,0 27,0 C39.1502645,0 49,10.3363825 49,23.0869565 C49,26.7327091 48.1947338,30.1810893 46.7606724,33.2469068 Z" id="Body-Copy-2" fill="#FB70A9"></path>
                    <g id="Legs" transform="translate(12.000000, 27.000000)">
                        <mask id="mask-2" fill="white">
                            <use xlink:href="#path-100"></use>
                        </mask>
                        <use id="Combined-Shape" fill="#4E56A6" xlink:href="#path-100"></use>
                        <mask id="mask-4" fill="white">
                            <use xlink:href="#path-300"></use>
                        </mask>
                        <use id="Combined-Shape" fill-opacity="0.298513986" fill="#000000" xlink:href="#path-300"></use>
                    </g>
                    <path d="M46.7606724,33.2469068 C45.9448607,34.4803214 45.3250477,36 43.6664081,36 C40.8749581,36 40.7240285,31.6956522 37.9310842,31.6956522 C35.1381399,31.6956522 35.2890695,36 32.4976195,36 C29.7061695,36 29.55524,31.6956522 26.7622957,31.6956522 C23.9693513,31.6956522 24.1202809,36 21.3288309,36 C18.537381,36 18.3864514,31.6956522 15.5935071,31.6956522 C12.8005628,31.6956522 12.9514923,36 10.1600424,36 C9.2827466,36 8.66625943,35.5748524 8.14660082,34.9917876 C6.14914487,31.5156333 5,27.4421238 5,23.0869565 C5,10.3363825 14.8497355,0 27,0 C39.1502645,0 49,10.3363825 49,23.0869565 C49,26.7327091 48.1947338,30.1810893 46.7606724,33.2469068 Z" id="Body-Copy-4" fill="#FB70A9"></path>
                    <path d="M42,35.5400931 C47.765228,26.9635183 47.9142005,17.4501539 42.4469174,7 C46.4994826,11.151687 49,16.849102 49,23.1355865 C49,26.7676093 48.1653367,30.203003 46.6789234,33.2572748 C45.8333297,34.4860445 45.1908898,36 43.4716997,36 C42.8832919,36 42.4080759,35.8226537 42,35.5400931 Z" id="Combined-Shape" fill="#E24CA6"></path>
                    <g id="Eyes-Copy-2" transform="translate(0.000000, 6.000000)">
                        <path d="M25.8205128,22.8461538 C33.4710351,22.8461538 36.6923077,18.4078931 36.6923077,12.1048951 C36.6923077,5.80189712 31.8248393,0 25.8205128,0 C19.8161863,0 14.9487179,5.80189712 14.9487179,12.1048951 C14.9487179,18.4078931 18.1699905,22.8461538 25.8205128,22.8461538 Z" id="Oval" fill="#FFFFFF"></path>
                        <g id="Pupil" transform="translate(18.820513, 3.461538)">
                            <ellipse id="Oval" fill="#030776" cx="4.07692308" cy="4.5" rx="4.07692308" ry="4.5"></ellipse>
                            <ellipse id="Oval" fill="#FFFFFF" cx="3.3974359" cy="3.46153846" rx="2.03846154" ry="2.07692308"></ellipse>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by service-paradis** [comment] 2021-07-22 17:13
Duplicate of #3549

**Closed by service-paradis** 2021-07-22 17:13 UTC
Labels: new icon

**Comment by antharuu** [comment] 2021-07-22 17:15
> Duplicate of #3549

Oh sorry about that. :confounded:

**Comment by service-paradis** [comment] 2021-07-22 17:29
> Oh sorry about that. 😖

No problem 😄
