### ISSUE TITLE
Request: matplotlib

### ISSUE THREAD

**Issue by oneonlee** [simple-icons/simple-icons#7474] opened 2022-06-03 17:03 UTC
### Brand Name

matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

24,882 https://www.similarweb.com/website/matplotlib.org/#overview

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by mondeja** [comment] 2022-06-05 11:17
Duplicate of #3410

**Closed by mondeja** 2022-06-05 11:17 UTC
Labels: new icon, duplicate
