### ISSUE TITLE
Request: Balsamiq Wireframes

### ISSUE THREAD

**Issue by CandidDeer** [simple-icons/simple-icons#7503] opened 2022-06-14 11:46 UTC
### Brand Name

Balsamiq Wireframes

### Website

https://balsamiq.com/wireframes/

### Popularity Metric

https://www.similarweb.com/de/website/balsamiq.com/#overview

### Official Resources for Icon and Color

https://balsamiq.com/company/brandassets/

### Contributing

No

**Comment by service-paradis** [comment] 2022-06-14 20:19
Duplicate of #5587

**Closed by service-paradis** 2022-06-14 20:19 UTC
Labels: new icon
