### ISSUE TITLE
Clarify Amazon and AWS icon names

### ISSUE THREAD

**Issue by sisp** [simple-icons/simple-icons#7242] opened 2022-03-19 14:02 UTC
### Brand Name

Amazon / AWS

### Official Resources for Icon and Color

not relevant

### Additional Comments

A couple of AWS icons use the "Amazon" brand name instead of "AWS" which I think is not optimal. Instead, I suggest to call AWS icons "AWS \<Service\>" and the files `aws<service>.svg` whereas Amazon products remain as they are. This would mean a breaking change though unless aliases are introduced.

What do you think?

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-03-19 15:10
I also saw this, but the the AWS vs Amazon names are based on how Amazon uses them. For example, for Lumberyard, Amazon calls it "Amazon Lumberyard" on [the product page](https://aws.amazon.com/lumberyard/). For Lambda, Amazon calls it "AWS Lambda" on [the product page](https://aws.amazon.com/lambda/).

**Comment by sisp** [comment] 2022-03-19 15:29
You're right. Oh wow, I didn't know, that's strange. Well, I guess the icons should use the official names even when they're inconsistent/unexpected.

**Comment by sisp** [comment] 2022-03-19 15:42
Nevertheless, searching for AWS right now does not show the icons of AWS services currently in the collection: https://simpleicons.org/?q=AWS Is there a way to give them an alias so they are found?

**Comment by sisp** [comment] 2022-03-19 15:51
I just noticed I could have opened a blank issue, didn't see the link below the templates.

**Comment by sachinraja** [comment] 2022-03-19 17:15
> Is there a way to give them an alias so they are found?

Yes, but I don't think they're factored into the website search results at the moment. Can you confirm @jorgeamadosoria? Also thanks for creating this issue @sisp, it's always good to have people looking out for these things.

**Comment by mondeja** [comment] 2022-03-20 16:46
> > Is there a way to give them an alias so they are found?
> 
> Yes, but I don't think they're factored into the website search results at the moment. Can you confirm @jorgeamadosoria? Also thanks for creating this issue @sisp, it's always good to have people looking out for these things.

I can confirm it, aliases are not taken into account searching in the website. For example, AEW icon has an `All Elite Wrestling` `aka` alias but is not found in the website searching for that name: https://simpleicons.org/?q=All%20Elite%20Wrestling

Opened https://github.com/simple-icons/simple-icons-website/issues/197 to track it

**Comment by jorgeamadosoria** [comment] 2022-03-22 02:37
> simple-icons/simple-icons-website#197

alias are ignored currently on the website. It should be added on the search box, it would greatly improved the functionality.
unfortunately I have a PR frozen in the website (https://github.com/simple-icons/simple-icons-website/pull/154) and it is quite big. I won't work on the website until that PR is either approved or rejected, because correcting conflicts there is a huge pain, and I won't add to it if I can help it. @sachinraja @mondeja  if you want to review that PR, we can speed this along.

**Comment by sachinraja** [comment] 2022-03-22 03:29
Would love to get that merged, but I'm not familiar with the files it touches and the website code in general so it would take a bit of time for me to do.

**Comment by jorgeamadosoria** [comment] 2022-03-22 05:22
I did, but I can't do that if I don't get a go ahead from another maintainer.

**Comment by mondeja** [comment] 2022-05-08 19:21
The aliases are now taken into account in the website as of https://github.com/simple-icons/simple-icons-website/pull/206. So do you still want to add aliases for Amazon icons?

**Comment by sachinraja** [comment] 2022-05-18 23:12
bumping this @sisp

**Comment by sisp** [comment] 2022-05-19 09:14
Sorry for the delay. Yes, I think aliases would be very helpful. I'll submit a PR.

**Comment by sisp** [comment] 2022-05-19 09:22
See #7427.

**Closed** 2022-05-21 01:23 UTC
Labels: icon outdated
