### ISSUE TITLE
Add Excalidraw Icon

### ISSUE THREAD

**Issue by esize** [simple-icons/simple-icons#9778] opened 2023-10-24 04:45 UTC
### Brand Name

Excalidraw

### Website

https://excalidraw.com/

### Popularity Metric

The project GitHub has 56.8K stars https://github.com/excalidraw/excalidraw

### Official Resources for Icon and Color

https://github.com/excalidraw/excalidraw-logo

**Comment by service-paradis** [comment] 2023-10-24 11:34
Duplicate of #7344

**Closed by service-paradis** 2023-10-24 11:34 UTC
Labels: new icon
