### ISSUE TITLE
Icon Request: OutSystems

### ISSUE THREAD

**Issue by basdejong95** [simple-icons/simple-icons#9879] opened 2023-11-20 11:46 UTC
### Brand Name

OutSystems

### Website

https://outsystems.com/

### Popularity Metric

The similarweb rank is 66.669: See https://www.similarweb.com/website/outsystems.com/

### Official Resources for Icon and Color

https://www.outsystems.com/media-kit/

**Comment by PeterShaggyNoble** [comment] 2023-11-20 12:11
Thanks for the request, @basdejong95 👍🏻 Would you like to take this one on yourself?

Note that [their brand guidelines](https://www.outsystems.com/-/media/files/generic/press-kit/brand-guidelines.pdf) explicitly forbid the use of the circle icon on its own so we would need to use the full logo:
> Do not use the ring by itself*
> _* OutSystems ring can exclusively be used by itself on Product icons and some pre-approved_

**Comment by service-paradis** [comment] 2023-11-20 18:00
Duplicate of #9554

**Closed by service-paradis** 2023-11-20 18:00 UTC
Labels: new icon
