### ISSUE TITLE
Saab, Lancia, Rover

### ISSUE THREAD

**Issue by pristis** [simple-icons/simple-icons#5319] opened 2021-03-19 16:16 UTC
Hello!

I just want to request Saab, Lancia and Rover (different from Land Rover) to be included in icons list. You can check it here:
Saab: https://worldvectorlogo.com/logo/saab-scania
Lancia: https://worldvectorlogo.com/logo/lancia-1
Rover: https://worldvectorlogo.com/logo/rover-2

Thanks!

**Comment by adamrusted** [comment] 2021-03-19 16:33
Thanks for your request @pristis!

Just had a quick look at this, Lancia is out of our scope based on its [Alexa Rank](https://www.alexa.com/siteinfo/lancia.com), and I don't think Rover has its own domain any more that we can compare using that metric. Saab seems to be in scope, so that should be good for us to add, though we try to use an official source (media pack, website, or PDF from the company themselves) as opposed to WorldVectorLogo wherever possible. I'm not currently at my PC to check the Saab website, but these brands usually have an SVG in their header, or a decent press pack we can use as a source.

**Comment by PeterShaggyNoble** [comment] 2021-04-09 16:27
- Saab _Automobiles_ has been defunct since 2012 and Saab _AB_ currently seem to cater exclusively to the defence "industry". We decied in #2777 against adding any brands that are solely in the business of war.
- Lancia is a duplicate of #4681 but if you can make a case for its popularity beyond its Alex ranks, I'd love to be able to include it.
- Rover, as a brand, was discontinued in 2005.

So, on the surface of things, I don't think we can add any of these at the time being. _However_, we could argue that there are still plenty of Saabs and Rovers still on the roads and try to make a case to add them as "legacy" brands.

**Comment by adamrusted** [comment] 2023-08-17 12:15
Closing as no justification given for inclusion since Apr 2021!

**Closed by adamrusted** 2023-08-17 12:15 UTC
Labels: new icon, in discussion
