### ISSUE TITLE
Icon Request: Mantine

### ISSUE THREAD

**Issue by Id-Yuu** [simple-icons/simple-icons#8566] opened 2023-04-24 20:02 UTC
### Brand Name

Mantine

### Website

https://mantine.dev/

### Popularity Metric

The mantine.dev web rank is 96,429. See https://www.similarweb.com/website/mantine.dev/#overview

### Official Resources for Icon and Color

SVG : https://user-images.githubusercontent.com/122996864/234102271-78bb4d09-cf56-4d61-8e4e-359af2f67b70.svg
color : #339af0

### Additional Comments

Other SVG : 
- https://user-images.githubusercontent.com/122996864/234103072-4cfccaca-ee05-46ca-bb0c-707152afc79c.svg
- https://user-images.githubusercontent.com/122996864/234103298-15e7aa21-3d0d-479e-b399-9aa1d105b000.svg

### Contributing

No

**Comment by service-paradis** [comment] 2023-04-26 12:21
Duplicate of #7670

**Closed by service-paradis** 2023-04-26 12:21 UTC
Labels: new icon
