### ISSUE TITLE
dailydotdev

### ISSUE THREAD

**Issue by asrvd** [simple-icons/simple-icons#7402] opened 2022-05-10 09:24 UTC
### Brand Name

daily.dev

### Website

https://daily.dev/

### Popularity Metric

31,774

### Official Resources for Icon and Color

png: https://github.com/dailydotdev/daily/blob/master/assets/logo.png

### Contributing

Yes

**Comment by Anmol-Baranwal** [comment] 2023-03-25 18:00
I really want this icon. Could someone please add it?

**Comment by PeterShaggyNoble** [comment] 2023-12-12 20:17
Duplicate of #9825

**Closed by PeterShaggyNoble** 2023-12-12 20:17 UTC
Labels: new icon

**Comment by Anmol-Baranwal** [comment] 2023-12-13 05:09
How can an issue created earlier be marked as a duplicate of an issue created later on.

> I'm not trying to do anything controversial; it just seems funny 😅
![image](https://github.com/simple-icons/simple-icons/assets/74038190/ebb0c809-9c24-4c01-b688-1c110a75682e)

At least, we can use the icon now :)
