### ISSUE TITLE
Request to add: Vailbot

### ISSUE THREAD

**Issue by AimarBustamante** [simple-icons/simple-icons#11497] opened 2024-07-20 02:38 UTC
### Brand Name

Vailbot

### Website

https://valibot.dev/

### Popularity Metric

https://valibot.dev/

### Official Resources for Icon and Color

SVG: https://github.com/fabian-hiller/valibot/blob/main/brand/valibot-icon.svg
Other Icons: https://github.com/fabian-hiller/valibot/tree/main/brand

### Additional Comments

The icon has a variant for both light and dark mode

**Comment by uncenter** [comment] 2024-07-20 02:49
Duplicate of #10591. Please search existing issues before opening new ones.

**Closed by uncenter** 2024-07-20 02:49 UTC
Labels: new icon
