### ISSUE TITLE
Request: gRPC Icon

### ISSUE THREAD

**Issue by yiaw** [simple-icons/simple-icons#7081] opened 2022-01-20 07:24 UTC
### Brand Name

gRPC Icon

### Website

https://grpc.io/

### Popularity Metric

the gRPC google proto buffer https://github.com/grpc

### Official Resources for Icon and Color

![grpc-icon](https://user-images.githubusercontent.com/47405340/150292183-e3d566b3-0017-4052-8152-3640a593f549.png)

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-01-20 13:50
duplicate of #6275 (you can still submit a PR for it)

**Closed by sachinraja** 2022-01-20 13:50 UTC
Labels: new icon
