### ISSUE TITLE
Request: 1C

### ISSUE THREAD

**Issue by JuliaPodmarkova** [simple-icons/simple-icons#12059] opened 2024-10-18 15:22 UTC
### Brand Name

1C

### Website

https://1c.ru/

### Popularity Metric

The SimilarWeb rank: 8589.
https://www.similarweb.com/website/1c.ru/

### Official Resources for Icon and Color

https://github.com/JuliaPodmarkova/JuliaPodmarkova/blob/main/1C%20logo.png

**Comment by GeorgVolkov** [comment] 2024-10-28 19:02
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by uncenter** [comment] 2024-12-05 03:00
Duplicate of #7494.

**Closed by uncenter** 2024-12-05 03:00 UTC
Labels: new icon
