### ISSUE TITLE
Icon Request: Disney

### ISSUE THREAD

**Issue by waffledork** [simple-icons/simple-icons#6494] opened 2021-09-08 10:53 UTC
Can we get a Disney icon? Ideally a Disney+ icon but a Disney one will suffice as well.

**Comment by adamrusted** [comment] 2021-09-08 16:32
Duplicate of #2309. Disney are VERY protective of their brands, and we cannot risk any legal activity against this project or its contributors.

**Closed** 2021-09-08 16:32 UTC
