### ISSUE TITLE
Prefect icon request

### ISSUE THREAD

**Issue by Jebushdd** [simple-icons/simple-icons#8527] opened 2023-04-09 02:46 UTC
### Brand Name

Prefect

### Website

https://www.prefect.io/

### Popularity Metric

11700 stars in GitHub [Prefect repo](https://github.com/PrefectHQ/prefect)

### Official Resources for Icon and Color

https://camo.githubusercontent.com/17035c27db10ca9bebf8f7f3ea49108c03db57f8c832c426ecc25264967b420e/68747470733a2f2f737065656c6f61642e636f6d2f75706c6f6164732f767a70524f685053746f2e706e67

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw4NDg8NDRAPDQ0ODQ0NDg0NDRAPDw0PFREWFhURFRUYHCgsGBolGxUVIjEhJSksOi4uFx8zOD8sNygtLisBCgoKDg0OGBAQFS0lHx0xLS0rMS0rKy4rLSstLTAtLS0tLy0tLS8rKy0tLS0tLSsrKystLS0tLSsrKystLS0tLf/AABEIAR0AsQMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAAAgEDBQYHBAj/xABCEAACAQIDAwcICAQGAwAAAAAAAQIDEQQFIQYSMRMjQVFhcYEUIjJScpGx0QczQ2JzobLhQlOC8ReSosHS8CRjwv/EABsBAAIDAQEBAAAAAAAAAAAAAAACAwUGBAEH/8QANREAAgECAggEBgEDBQAAAAAAAAECAxEEgQUSITFhkcHRIkFRcRMyobHh8BQVQlMjYpKi8f/aAAwDAQACEQMRAD8A7iAAAAAAAAAAAAAGNx+b0MPpKV59FOOr8eoaMZSdoq7EqVYUo685JL1ZkjG5hm9DD6TlefqRV349RrGY7RVq3mw5mHSotNyXtfKxhWyxoaOvtqPJd+3Mz2L08l4cPG/F9F3t7GZzHaOvV82HMw9WNm33y+VinAZ/iKGm9ykPUn8+JimxGyyjhqajq6qt+5lJ/NxDn8T4rv79N1uFrG/5btBQxCtfkp+pN/CXBmZOSNmTy3aHEYey3uUpr7Od9F2PicNbRnnSeT79+Zd4XTv9teOa6rtlE6QBg8r2iw+I03uSqcNyb0v2S4MzhVzpyg9WSszQUqsKsdanJNcP3Z7PaAAAhIAAAAAAAAAAAAAAAAAAYzMM4oYf0pb0/Ujq/wBhowlJ2irsjq1YUo69SSSXmzJmNzDN6GH9KW9PohHV/saxmG0Nav5sOZh0qDTcl7X9jDljR0ffbUeS79uZn8Xp9Lw4eN+L6Lvb2ZmMx2irVrxhzMOlRd3L+r+xhmyGxWy0p0o01aKsjPVq1StLXqSbfHp5L2VkS2I2Q2K2SpCEtiNkNiNjpDJDNititiNjWGJbMtle0mJwtoqXK0l9nPVJdj4r4dhh3IrbCdKNRas1dE1KrOlLWpyafA6ZlW0uGxNo73I1eHJ1Ho32S4MzxxJszGU7T4rCWjvcrSX2dRtpLslxXw7CqxGiPOi8n0ffmX2F015V45rt25HVQNeyjarC4q0d7kar05Oo0k32S4P8n2GwlPUpTpvVnGzLynVhVjrQkmuH7+QAAIyQAAAADGZjnFDD+lLem+EI6v8AY8O09XEwhHkbqk0+UlHiupaGoFhhcEqkdeUtnouvoUOktMSw83Spw2+r3ZLz9L7r+pl8w2hr1rxg+Rj0qDu5f1f2MQDYjZbU6cYLVirIy9atUrS1qkm3x6eS9lZEtitkNiNkqQhLYrZDYjY1hiWxXIVsVsewwzYjYrZDY1hkDYjZDYrY9hiWxGyGxWx0hiWxGyGxGxkhiWzNZNtXi8HaO9y1JfZVG2kuyXGPw7DBNiNhUowqR1ZxuuJLSqTpy1oSs/392nWcl2swmLtHe5Gq9Nyo0k392fB/k+w2M4A2ZzJdrcXg7R3uWorTkqrbSX3ZcY/DsKXE6E86Esn0ffmXmH0v5Vo5rt25HYwNG/xIofyKv+dfICu/pmL/AMT5ruWP8/Df5F9TeTC5hkFCvdxXJVPXitL93yM0BxwqSg7xdiatQp1o6lSKa49PR8Uc8zLJsRh7uUd6n0zhd2X+3iYtyOrmDzLZzD17yiuRqP8Ajgrq/cWdDSK3VVmu3bkZ7FaBa8WHlk+j78zQmxGzJZpkeIw13KO9TX2sNdP/AJMS5FvTlGa1ou6KKpSnSlqzi0+P79hmxWxWxGySx4M2I2DkVtjpDIlsVshsRsawxLYrZDYjY6QxLYrYrZDY9hiWytshsVsZIZEtiNkNiNjpDDNititiNjWGHuSVXAawx9FAAHzo2gAAAAGv5psxhsReUVyNV678FdX7Y/KxsAElOrOm7wdmRVqNOtHVqRTXHp6Pijl2a5DicLeUob9NfaQvLT4rxMO5HaTXc32Uw2J3pQXIVXrvwXmt9sflYt8PpWO6qs127ciixOhGttCWT6PvzObNiNmVzjZ7E4S8pw36S+1p3krfe6V4mGci6pyjUjrRd1wKWpSnTlqzVnxGbEbIbEbJbHgzYjZDYjY6QxLYrZDYjY1hiWxWxWyGx7DA2K2K2K2OkMS2I2Q2K5DWGGuSVXAawx9JAAHzY2IAAAAAAAAAAAAGt5vsjhcTeUF5PV478FeDfbDh7rGyGLzXOsPhFz07StdU4+dN+HRx4uxNh51YzXwm78O3chxEaUqb+NbVXr38sjmmc7OYrB3lOG/SX2tO8oW+90rxMG2bpm+2deteGHXk9N6byd6k17XR4e84/DPK1KpOMudgq01aT85LefCXzuavD1qigvjpJ8Oq7fQzE6FKpOSwzbS9ej3vPmzamxGzxYPNKNfSMrT9SekvDr8D0tnfC0ldHNKEou0lZjNiNkNiNj2CwzYjZDYjY6QxLYrZDYjY6QyRLYrZDYrY1h0ibklW8A1gsfTQAB8yNeAAAAAAY3Ms3oYZc9O0rXUFeUn4dHiNGMpO0VdiTqRpx1ptJer2GSMZmecYfCrnppTtdU4+dN+HR3uxqea7WV6t40OYh1xe9Uku/o8Pea1N3bb1bd23q2+tlrh9Ft7artwXftfIpMVpuK2UI34vdkt7ztmbDm+2FeteOH5iHXF71SS7+jw95rEpNttttt3bbu2+tsmTK5MuqNGFJWgrfv1KKtXqVpa1SV39Ml5ZCtmi43Lk5zcJWbnN2lw4vpN5bNUqu8pe1L4ndRpQqXUkdGEnKDk0/Q1+rhpw9KLt1rVe89mDzmrTspPlodUn5y7pfMyJRVwlOfFWfXHRiywEoO9KfP8AehYfGjNWqRMjhcxpVvRdpepLSX7+B6GzWquWyWsGpdj0Y1HMa1Hzaico9VXj4SPFWnT2VYW4rcRSw0ZbacsnvNgbEbPNh8fTq+i7S9WWj/cubOyDUldO6IHFxdmrEtiNkNiNkqR7YZsRsGyBrHtibkAB6en06AGPzDNKOHXOys7XUFeU34HzCMXJ2irs1NSpCnFym0kvN7EZAx2YZtQw31s7SfCmtZPwNZzLaatUvGlzMeuLUqkl39Hh7zX2+L4tu7b4t9ZZ0NGt7ajtwXcocVp2K8OHjfi92S3vNrMzeabU1qt40eZh917033vo8Pea7N8W9W3dt8W+seTKpMt6NKFNWgrFBWr1K8tapK7+3svLIWRXJjSK5HQhELIrkxpMrkyREiQrZqd7uXZOa/1M2pmpU351Rf8Auk/zZ1Yd2mdeG/uyHJIJO86CAkk9GrrqepJAAeWrl8JcLwfZw9wsJYilx5+Hf5y/74ntIOd4aF9aOx8O276EnxZWs9q4ldLGQnonafqS0kWtldWlGfpJPv6BYwlHhK69Wrr7n87jx14/Nt9u3Z5HjUXuLSSI69BJKIAEEgB2nMtpKtRuNLmoa6x1qSXb1eHvMFLrererb4tjFcmZSlShTVoqxT18RVxE9erK78uHt6ZfcWTEkTJiSJ0RiSZXIaTK2SIdCyEkyZMrkyRDpESZVJjSZWyREiFbNQg+dqLrlP8AUbc2ade1aXtzX5snpu0kduFV1M9QEEliSgAAAAAEABJAHvyjJ8TjZ8nhqU60tN5xVow7ZSekfEWUlFOTdkvPyPYpydkeAyeTZHi8fLcw9GVWztKp6NOHtTei7uJ0bZ76MqNK1THz5eej5Gk3Gmvalxl+Xib9h8PTowjTpQjTpxVowpxUYxXYkUGM0/Sh4aC1n67kur+mZZUdHSe2o7cPM5P/AIVY7+fhf89b/gB18Cq/r2L/ANv/ABO3+BR9Pqzl7K5MaRXJlgjAoWTK5DSZXJkiHQsmVyY0iuTJEOhZFcmPIqkyREiFkyuQ0mVyZIhxWzTartUk+qpJ/wCo3BmnYj05+3L4sdndg98sj2ki03dJ9iJLNO+0ckgD04DAVsTUVLD051ZvhGnG7t1vqXazxtJXZ6lfYjznryzK8RjKnJYalOrPpUFpFdcm9IrtbR0LZz6MLWqZhPt8noS/KdT/AGj7zouAwNHDU1SoU4Uaa/hpxSV+t9b7WUWM07RpeGj4n/1/OXMsKGjpy2zdl9fxmc/2d+jCEbVMwnyj4+T0ZNQXZKfF9yt3s6Fg8JSoQVOhThSpx4QpxUYrwR6QMvisbXxTvVlf0Xksuu8tqVCFJWiu4AAHKSgAAAHLJFcmNJiSNWj5shJMrkxpMSTJESCSK5MaRXJkqHQsmVyY0mVyY6HQsiuTHkVSZKhyGadX9Ofty+Jt7NUjQnVrOnShOrUnOSjTpxc5yd3oories78HvlkW4Z+auy6PXgsHVrzVOhTnUqS4QpxcpPtsujtN42V+i+tNKpmMvJ4NpqhTcZVn7UtVHwv4HTspyjD4KHJ4alClHpaV5TfXKT1k+848RpyhRgo0/FL6ZvtzLOno+c3eexfU53s79GEnapmEtyOj8noyTm+yc+C7o370dHyzLMPhKfJYalCjDpUFrJ9cnxk+1nuAzWLx9fFP/Uls9FsXLvctKOHp0l4V3AAA4yYAAAAAAAAAAAA5TJlchpMrka2J84QsmVyY0mVyJEOLJlchpMrkSIcWTK5MeTKpEiHQsiuQ0mVyJEOhJs7Hs1keFwVGPk1GFOVSEZVKnGpUb1e9N6tXfDgug43LgzvGB+ppfhU/0optOtqnTSext3+he6GS1qj9up6AADNl8AAAAAAAAAAAAAAAAAAAAcmkyuTHkVSZrkj5yhZFcmPIqkyRDoiTK5MaRVJkiQ6IkyqQ0mVyZIh0RJlUhpMrkyVEiQs+DO84D6ml+FT/AEo4HJ6M75gPqaX4VP8ASik098lP3f2ReaG31Mup6AADNl6AAAAAAAAAAAAAAAAAAAAcjkVyY0mVyNgj50LJlcmNJlcyRIdCyZXJjSK5MkQ6FkVyY0mVyZIiRIWTK5MaTK5MkSHQsno+475gPqaX4VP9KOAyejO/YD6ml+FT/Sij0/8AJS939kXmht9TLqegAAzZeAAAAAAAAAAAAAAAAAAAAHIJMrkPJlUmbFHztCyZXJjSZXJkiHQsmVsaTK5EiJEhZMrkNIrkyRDoWTK5DSZXJkqHFk9H3Hf8B9TS/Cp/pR8/SejPoHAfU0vwqf6UUWn/AJKXvL7Iu9D76mXU9AABmi8AAAAAAAAAAAAAAAAAAAAOOyZXJjSZXJmzSPniFkVyY0mVyZIiRCyZXJjSZXIkSHQsiuTGkJZtqKTcm7KKV231JEiHEkyt66LVvRJcWzcMl2ExWItPEf8Ai03raa3qsl2R/h/q9xvmTbN4TBJcjTTqdNWp59Twf8PcrHBiNLUKGxPWfot2b/8ASzw+ja1TbLwrjv5d7HO8l2DxeKtKuvJKXXUXOSXZDo8beJ1qlTUIxguEYqKvxslYsAzeMx1TFNa9rLclxL3D4WnQTUfPeAABxnSAAAAAAAAAAAAAAAAAAAAcbkVSGkxJG0R89SEkyuTGkyKdOVSShCMpzlooQi5SfckSIkRVJiRhKUlGKcpSdoxinKUn1JLibllGwtaraeKlyMf5cbSqNd/CP5m6ZXk+HwkbUKcYtqzm/OqS75PXwK/EaVo0tkfE+G7n2uW2H0VWqbZeFcd/Lyz28DQsn2ExFa08U/J6fHc0lVa7uC8fcbzlGQ4bBLmKaU7WdSb3qj/qfDuVkZYCjxOPrYjZJ2Xoti/OZe4fBUaG2K2+r3/jKwAAHGdYAAAAAAAAAAAAAAAAAAAAAAAAAAABxeTIpUZ1ZKFOMqk3wgouUn4I3LC7HU5Vqm/Vk6dOSioRhuyab0Tld/D3G14HA0cNDdoU400+Nlq+1vi/E0VfSlKnsgrvkv32Mth9D1p7aj1Vzb9vzt4Gl5VsPOVp4ufJx48jBqU33y4L8zcctyvD4WO7QpxhfjLjOXfJ6s94FNXxdav88tnot3773L/D4Kjh/kjt9XtfPtZcAAAOY6gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2Q==

### Contributing

Yes

**Comment by madkinsz** [comment] 2023-04-25 03:42
Duplicate of https://github.com/simple-icons/simple-icons/issues/6101 and note that is not our current official icon please see https://www.prefect.io/newsroom/logos/

**Comment by service-paradis** [comment] 2024-01-18 14:02
Closing as already added in #8772

**Closed by service-paradis** 2024-01-18 14:02 UTC
Labels: new icon
