### ISSUE TITLE
Add Sanity.io Icon

### ISSUE THREAD

**Issue by SneakySensei** [simple-icons/simple-icons#8036] opened 2022-11-15 12:43 UTC
### Brand Name

Sanity.io

### Website

https://www.sanity.io/

### Popularity Metric

Global rank on [Similarweb ](https://www.similarweb.com/website/sanity.io/#overview)is 57,179.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-11-15 14:36
Duplicate of #6443

**Closed by service-paradis** 2022-11-15 14:36 UTC
Labels: new icon
