### ISSUE TITLE
Request: HDFC Bank

### ISSUE THREAD

**Issue by DiegoPeter2021** [simple-icons/simple-icons#6040] opened 2021-06-28 16:36 UTC
**Brand Name:** HDFC Bank
**Website:** https://www.hdfcbank.com/
**Alexa rank:** 205
**Official resources for icon and color:** First color on the logo: `#ee2529`, second color on the logo: `#004c8f`. See the SVG file on Wikimedia Commons: https://commons.wikimedia.org/wiki/File:HDFC_Bank_Logo.svg

**Comment by adamrusted** [comment] 2021-06-28 16:54
Duplicate of #5900.

**Closed** 2021-06-28 16:54 UTC
Labels: new icon

**Comment by DiegoPeter2021** [comment] 2021-06-28 17:43
Found here at #6042. See the pull request!
