### ISSUE TITLE
Request icon for ServiceNow

### ISSUE THREAD

**Issue by traxeon** [simple-icons/simple-icons#10944] opened 2024-05-13 12:22 UTC
### Brand Name

ServiceNow

### Website

https://servicenow.com

### Popularity Metric

https://www.similarweb.com/website/servicenow.com
Rank#: 14,008 global, 6134 national, #328 industry

### Official Resources for Icon and Color

https://www.servicenow.com/trademarks.html

### Additional Comments

See trademark link for more details.

**Comment by service-paradis** [comment] 2024-05-13 12:42
Duplicate of #8506

**Closed by service-paradis** 2024-05-13 12:42 UTC
Labels: new icon
