### ISSUE TITLE
Prefect Icon

### ISSUE THREAD

**Issue by ItsLuized** [simple-icons/simple-icons#8319] opened 2023-02-07 05:53 UTC
### Brand Name

Prefect

### Website

https://www.prefect.io/

### Popularity Metric

Prefect has 11k stars on their github repository. See https://github.com/prefecthq/prefect
The similar web rank is 251,725. See https://www.similarweb.com/website/prefect.io

### Official Resources for Icon and Color

None

### Additional Comments

Prefect is a modern workflow orchestration tool for coordinating all of your data tools. Orchestrate and observe your dataflow using Prefect's open source Python library, the glue of the modern data stack. Scheduling, executing and visualizing your data workflows has never been easier.

### Contributing

No

**Comment by service-paradis** [comment] 2023-02-07 13:31
Duplicate of #6101

**Closed by service-paradis** 2023-02-07 13:31 UTC
Labels: new icon
