### ISSUE TITLE
Update: Western Digital

### ISSUE THREAD

**Issue by donpro2009** [simple-icons/simple-icons#10389] opened 2024-02-01 00:12 UTC
### Brand Name

Western Digital

### Official Resources for Icon and Color

None

### Additional Comments

https://www.westerndigital.com/

**Comment by PeterShaggyNoble** [comment] 2024-02-01 00:24
Duplicate of #6935

**Comment by PeterShaggyNoble** [comment] 2024-02-08 12:12
Coming back to this one again, I see that it was not a request to _add_ Western Digital but to _update_ it.

**Closed** 2024-03-14 12:31 UTC
Labels: good first issue, update icon/data
