### ISSUE TITLE
Request: Disney+

### ISSUE THREAD

**Issue by mattclair** [simple-icons/simple-icons#7018] opened 2022-01-02 16:52 UTC
### Brand Name

Disney+

### Website

https://www.disneyplus.com/

### Popularity Metric

Alexa Rank: 181

### Official Resources for Icon and Color

https://dmedmedia.disney.com/disney-plus/images

### Contributing

No

**Comment by adamrusted** [comment] 2022-01-03 18:06
Duplicate of #2309, #3493, #3693, #5327, #5443, #6352.
Disney are _super_ strict about their brands, and as such we will not be adding them to this project.

**Closed by adamrusted** 2022-01-03 18:06 UTC
Labels: new icon
