### ISSUE TITLE
Request for Appium logo

### ISSUE THREAD

**Issue by ankiprawira** [simple-icons/simple-icons#7480] opened 2022-06-06 10:49 UTC
### Brand Name

Appium

### Website

https://appium.io/

### Popularity Metric

Appium Similarweb rank is 189,843

### Official Resources for Icon and Color

![appium-seeklogo com](https://user-images.githubusercontent.com/74639605/172146868-733d4f35-5471-4ba9-b0d1-c253cbceb2e8.svg)
Color : #662d91

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-06-06 15:05
Duplicate of #3385

**Closed by service-paradis** 2022-06-06 15:05 UTC
Labels: new icon
