### ISSUE TITLE
Add icon for Cupra 

### ISSUE THREAD

**Issue by danielohling** [simple-icons/simple-icons#10381] opened 2024-01-30 22:03 UTC
### Brand Name

Cupra

### Website

https://www.cupraofficial.com/

### Popularity Metric

The similar web rank is 611,109. See https://www.cupraofficial.com/

### Official Resources for Icon and Color

https://www.behance.net/gallery/137822497/CUPRA-Brand-Guidelines, https://fabrikbrands.com/cupra-logo-history-symbol-meaning-and-brand-story/
![Cupra](https://github.com/simple-icons/simple-icons/assets/37549508/91575d18-2d23-4839-b042-f4c347c69d55)

**Comment by PeterShaggyNoble** [comment] 2024-01-30 22:25
Duplicate of #8351

**Closed** 2024-01-30 22:24 UTC
Labels: new icon
