### ISSUE TITLE
Whatsapp Business icon

### ISSUE THREAD

**Issue by j4mbee** [simple-icons/simple-icons#3956] opened 2020-11-19 11:51 UTC
**Name:** Whatsapp Business
**Website:** https://www.whatsapp.com/business/
**Alexa rank:** 65

**Official resources for icon and color:** https://static.whatsapp.net/rsrc.php/v3/y9/r/8_ehD5HHcy3.png

**Comment by PeterShaggyNoble** [comment] 2021-01-07 11:51
Thanks for the request, @j4mbee.

However, from [their brand centre](https://whatsappbrand.com/):

> Never use the WhatsApp Business app icon to promote your business presence on WhatsApp

Given that that's what most people would probably want to use it for, I don't think we can add this one to our library. What do the other @simple-icons/maintainers think?

**Comment by fbernhart** [comment] 2021-01-07 12:03
I would say: What the users of Simple Icons do with the icons we provide in the end, is up to them. So I wouldn't mind adding it.

**Comment by ericcornelissen** [comment] 2021-01-07 12:39
This is somewhat of a gray zone. On the one hand I agree with @fbernhart, on the other hand, just like we follow other guidelines, this guideline do give an indication of the intended usage, which to me seems like: this is just the app icons and the normal WhatsApp logo is what you should always use otherwise. But please do correct me if I'm wrong in that regard.

Moreover, I'm not sure if the Alexa rank of WhatsApp itself is a good indication of the popularity of WhatsApp Business. I'm quite certain the former has a lot more users than the latter. I still think it's fine, but if it turns out only a handful of businesses actually use it I don't think it's worth adding.

**Comment by PeterShaggyNoble** [comment] 2021-01-07 12:42
Yep, that was my interpretation, too; that the "B" icon is for their own use only and everyone else should use the standard one.

With regards to popularity, >100m download on [Google Play](https://play.google.com/store/apps/details?id=com.whatsapp.w4b&hl=en_IE&gl=US) should put it within our scope.

**Comment by PeterShaggyNoble** [comment] 2021-02-26 11:02
Anyone else want to weigh in on this one so we can get it resolved?

**Comment by service-paradis** [comment] 2021-04-12 12:48
Since we provide guidelines now, we might consider adding it.

**Comment by PeterShaggyNoble** [comment] 2021-04-12 16:35
Possibly 🤔 I'd still be opposed to it, but always happy to follow the consensus.

**Comment by PratyushJayachandran** [comment] 2023-07-30 03:58
@adamrusted This is a duplicate of #8024 which I have already created a PR for #8875

**Closed** 2023-11-24 14:33 UTC
Labels: new icon, in discussion
