### ISSUE TITLE
Icon request: Hugging Face

### ISSUE THREAD

**Issue by ghosh-r** [simple-icons/simple-icons#6167] opened 2021-07-25 11:25 UTC
**Brand Name:** Hugging Face
**Website:** https://huggingface.co
**Alexa rank:** 24,865
  

**Official resources for icon and color:**  https://huggingface.co/front/assets/huggingface_logo.svg

**Comment by service-paradis** [comment] 2021-08-03 13:15
Duplicate of #6074

**Closed by service-paradis** 2021-08-03 13:15 UTC
Labels: new icon

**Comment by talhaanwarch** [comment] 2022-06-22 20:27
@service-paradis where can i find it this icon. i am unable to find it
