### ISSUE TITLE
Add EndeavourOS

### ISSUE THREAD

**Issue by gr0sz** [simple-icons/simple-icons#10376] opened 2024-01-30 04:38 UTC
### Brand Name

EndeavourOS

### Website

https://endeavouros.com/

### Popularity Metric

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=endeavouros.com

### Official Resources for Icon and Color

Logo SVGs with/without text available on their official repo: https://github.com/endeavouros-team/endeavouros-theming 

### Additional Comments

EndeavourOS is certainly an outlier amongst Arch-based distros, being more stable than Manjaro yet retaining the same degree of customization Arch is known for.
Something similar to #9221c2 would be a good fit for the badge background color.

**Comment by service-paradis** [comment] 2024-01-30 12:53
Duplicate of #7926

**Closed by service-paradis** 2024-01-30 12:53 UTC
Labels: new icon
