### ISSUE TITLE
Icon request : emotion

### ISSUE THREAD

**Issue by leedo97y** [simple-icons/simple-icons#8851] opened 2023-06-21 17:15 UTC
### Brand Name

emotion

### Website

https://emotion.sh/docs/introduction

### Popularity Metric

16.5k stars and 1.1k forks. See [https://github.com/emotion-js/emotion](https://github.com/emotion-js/emotion)

### Official Resources for Icon and Color

png file : [https://github.com/emotion-js/emotion/blob/main/emotion.png](https://github.com/emotion-js/emotion/blob/main/emotion.png)

svg : None

color : #D26AC2

### Additional Comments

There are only png files.
And I brought the color from here [https://github.com/emotion-js/emotion/blob/main/site/util/style-constants.ts](https://github.com/emotion-js/emotion/blob/main/site/util/style-constants.ts)

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-06-21 18:49
Duplicate of #8150

**Closed by service-paradis** 2023-06-21 18:49 UTC
Labels: new icon
