### ISSUE TITLE
Request: Touch Designer

### ISSUE THREAD

**Issue by CamKHardin** [simple-icons/simple-icons#12077] opened 2024-10-21 19:31 UTC
### Brand Name

Touch Designer

### Website

https://derivative.ca/UserGuide/TouchDesigner

### Popularity Metric

Similarweb rank is 150,142

### Official Resources for Icon and Color

None

**Comment by GeorgVolkov** [comment] 2024-10-28 19:02
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by uncenter** [comment] 2024-12-05 02:59
Duplicate of #9632.

**Closed by uncenter** 2024-12-05 02:59 UTC
Labels: new icon
