### ISSUE TITLE
ServiceNow

### ISSUE THREAD

**Issue by TurboJJJ** [simple-icons/simple-icons#11610] opened 2024-08-13 06:10 UTC
### Brand Name

ServiceNow

### Website

https://www.servicenow.com

### Popularity Metric

Growing helpdesk tool

### Official Resources for Icon and Color

https://www.servicenow.com/content/dam/servicenow-assets/public/en-us/images/og-images/favicon.ico

### Additional Comments

SericeNow provides a Helpdesk tool, like Jira or TopDesk

**Comment by service-paradis** [comment] 2024-08-13 12:16
Duplicate of #8506

**Closed by service-paradis** 2024-08-13 12:16 UTC
Labels: new icon
