### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by shubamsumbria** [simple-icons/simple-icons#7069] opened 2022-01-16 11:14 UTC
### Brand Name

matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

None

### Official Resources for Icon and Color

None

### Additional Comments

None

### Contributing

No

**Comment by sachinraja** [comment] 2022-01-19 03:37
duplicate of #3410

**Closed by sachinraja** 2022-01-19 03:37 UTC
Labels: new icon, duplicate
