### ISSUE TITLE
MPLAB Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8671] opened 2023-05-19 17:00 UTC
### Brand Name

MPLAB X IDE (Microchip Technologies)

### Website

https://www.microchip.com/en-us/tools-resources/develop/mplab-x-ide

### Popularity Metric

This is popular in Embedded Systems Domain. The similarweb global rank is 36,440.

### Official Resources for Icon and Color

https://seeklogo.com/free-vector-logos/mplab

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-19 20:12
Duplicate of #5844

**Closed by service-paradis** 2023-05-19 20:12 UTC
Labels: new icon
