### ISSUE TITLE
Icon for Hardhat

### ISSUE THREAD

**Issue by aaankeet** [simple-icons/simple-icons#8545] opened 2023-04-14 17:23 UTC
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

**Hardhat Rank  On**  [Similarweb](https://www.similarweb.com/website/hardhat.org/#overview).
```
Global Rank : 357,078
Country Rank: 133,760
Category Rank: 1,759
```
5.6K Stars on [Github.com](https://github.com/NomicFoundation/hardhat)

### Official Resources for Icon and Color

**Hardhat svg icon**: https://hardhat.org/_next/static/media/hardhat-logo-dark.484eb916.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-04-21 17:23
Duplicate of #8140

**Closed by service-paradis** 2023-04-21 17:23 UTC
Labels: new icon
