### ISSUE TITLE
Request: Seaborn Icon 

### ISSUE THREAD

**Issue by Anonymous7code** [simple-icons/simple-icons#6557] opened 2021-09-16 11:50 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

The Github repo stars are 8.8k

### Official Resources for Icon and Color

https://github.com/mwaskom/seaborn/blob/master/doc/_static/logo-wide-lightbg.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2021-09-17 14:04
Duplicate of #6324, but you can surely open a new PR if you want to contribute since the previous assignee did not.

**Closed by service-paradis** 2021-09-17 14:04 UTC
Labels: new icon
