### ISSUE TITLE
Icon Request: pnpm

### ISSUE THREAD

**Issue by juanpicado** [simple-icons/simple-icons#5507] opened 2021-04-22 05:34 UTC
**Brand Name:** pnpm
**Website:** https://pnpm.io/
**Alexa rank:** 2,875,768
  

**Official resources for icon and color:**
  

https://github.com/pnpm/pnpm.github.io/blob/main/static/img/logos/pnpm-standard-no-text.svg

**Comment by PeterShaggyNoble** [comment] 2021-04-22 06:57
Duplicate of #5482

It will be available in Sunday's release.

**Closed by PeterShaggyNoble** 2021-04-22 06:57 UTC
Labels: new icon
