### ISSUE TITLE
Request: Amazon Music

### ISSUE THREAD

**Issue by JuergenB** [simple-icons/simple-icons#7566] opened 2022-07-05 14:53 UTC
### Brand Name

Amazon Music

### Website

https://music.amazon.com/

### Popularity Metric

7.6M visits

Needed for podcast icons

https://www.similarweb.com/website/music.amazon.com/#overview

### Official Resources for Icon and Color

none

### Contributing

Yes

**Comment by JuergenB** [comment] 2022-07-06 11:56
The last one, I agree with your view that it looks best. Plus, this is something a I have seen other podcasting platforms use, albeit with a black background. I’m not sure what Amazon’s official color for Amazon Music is.
On Jul 6, 2022, 3:35 AM -0400, Sigurd Spieckermann ***@***.***>, wrote:

What would be the icon? I see the following options:

  *   https://d5fx445wy2wpk.cloudfront.net/static/logo.svg (from the navbar of the desktop website, a bit verbose)
  *   https://d5fx445wy2wpk.cloudfront.net/static/logo_stacked.svg (from the navbar of the mobile website, a bit verbose)
  *   https://d5fx445wy2wpk.cloudfront.net/icons/amznMusic_favicon.png (the favicon of the website - completely different than the other icons, no SVG)
  *   https://de.wikipedia.org/wiki/Amazon_Music#/media/Datei:Amazon_Music_logo.svg (from Wikipedia, seems to be the official icon for Amazon Music smartphone apps, looks best IMO)

**Comment by service-paradis** [comment] 2023-08-14 12:38
Duplicate of #3163

**Closed by service-paradis** 2023-08-14 12:38 UTC
Labels: new icon, in discussion
