### ISSUE TITLE
Akka

### ISSUE THREAD

**Issue by vcaballero-salle** [simple-icons/simple-icons#8686] opened 2023-05-26 13:55 UTC
### Brand Name

Akka

### Website

https://akka.io/

### Popularity Metric

653,264

### Official Resources for Icon and Color

https://akka.io/resources/images/akka_icon_full_color.svg

### Additional Comments

There are no other variants of this icon

### Contributing

No

**Comment by vcaballero-salle** [comment] 2023-08-28 12:30
@adamrusted , sorry I mistakenly said that I can contribute, but I don't have the skillset do to so.

**Comment by adamrusted** [comment] 2023-08-28 12:43
No stress, let me unassign you :)

**Comment by PeterShaggyNoble** [comment] 2023-12-02 00:26
Duplicate of #6605

**Closed by PeterShaggyNoble** 2023-12-02 00:26 UTC
Labels: new icon
