### ISSUE TITLE
Please ADD Matplotlib Icons

### ISSUE THREAD

**Issue by cv-jaeha** [simple-icons/simple-icons#6847] opened 2021-11-11 14:19 UTC
### Brand Name

Matplotlib

### Official Resources for Icon and Color

site : https://matplotlib.org/
color : FF9933

### Contributing

Yes

**Comment by service-paradis** [comment] 2021-11-12 13:50
Duplicate of #3410

**Closed by service-paradis** 2021-11-12 13:50 UTC
Labels: icon outdated, duplicate
