### ISSUE TITLE
Cura

### ISSUE THREAD

**Issue by swhasans** [simple-icons/simple-icons#8277] opened 2023-01-21 07:55 UTC
### Brand Name

Ultimaker Cura

### Website

https://ultimaker.com/software/ultimaker-cura

### Popularity Metric

The Similarweb rank is 45,560. See https://www.similarweb.com/website/ultimaker.com/#overview

### Official Resources for Icon and Color

logoColor: '#0da5dc', from icon. 

### Additional Comments

- The Ultimaker brand does not offer multiple versions of its Cura logo.
- As far as I know, the Cura logo is not available under a license.
- Using the Ultimaker trademark or any of its distinctive features is prohibited, however, it's unclear if the same applies to the Cura logo.

### Contributing

No

**Comment by adamrusted** [comment] 2023-07-24 17:37
Duplicate of #7657

**Closed by adamrusted** 2023-07-24 17:37 UTC
Labels: new icon
