### ISSUE TITLE
Add PixelFed icon

### ISSUE THREAD

**Issue by abbluiz** [simple-icons/simple-icons#8999] opened 2023-07-12 02:52 UTC
### Brand Name

Pixelfed

### Website

https://github.com/pixelfed/pixelfed

### Popularity Metric

GitHub star count is pratically 5,000 at https://github.com/pixelfed/pixelfed

### Official Resources for Icon and Color

https://github.com/pixelfed/brand-assets

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-07-12 14:02
Duplicate of #7269

**Closed by service-paradis** 2023-07-12 14:02 UTC
Labels: new icon
