### ISSUE TITLE
Request: Scrapy

### ISSUE THREAD

**Issue by hyeokju1313** [simple-icons/simple-icons#6453] opened 2021-09-02 05:28 UTC
### Brand Name
Scrapy

### Website
<https://scrapy.org>

### Popularity Metric
<https://github.com/scrapy/scrapy> - 41.4k stars on Github

### Official Resources for Icon and Color
<https://github.com/scrapy/scrapy/tree/master/artwork>

### Additional Comments
No response

### Contributing
No

**Comment by service-paradis** [comment] 2021-09-02 12:58
Duplicate of #6337

**Closed by service-paradis** 2021-09-02 12:58 UTC

**Comment by keyiflerolsun** [comment] 2021-09-07 05:57
yes, this is very big library
