### ISSUE TITLE
Request for the Hugging Face icon

### ISSUE THREAD

**Issue by yassine-rd** [simple-icons/simple-icons#9415] opened 2023-08-25 18:14 UTC
### Brand Name

Hugging Face

### Website

https://huggingface.co/

### Popularity Metric

100k+ Github Stars. See : https://github.com/huggingface

### Official Resources for Icon and Color

svg : https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.svg
color : #FFD21E, #FF9D00, #6B7280 from the brand assets

### Additional Comments

There are two variants of this icon.

variant 2 : https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo-with-title.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-08-25 18:22
Duplicate of #6074

**Closed by service-paradis** 2023-08-25 18:22 UTC
Labels: new icon
