### ISSUE TITLE
Update: Nokia Icon

### ISSUE THREAD

**Issue by adsingh14** [simple-icons/simple-icons#8468] opened 2023-03-25 17:17 UTC
### Brand Name

Nokia

### Official Resources for Icon and Color

Icon: [Official logo link](https://www.nokia.com/themes/custom/onenokia_reskin/logo.svg)

Color: `#005aff`

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-03-27 13:04
Duplicate of #8391

**Closed by service-paradis** 2023-03-27 13:04 UTC
Labels: icon outdated, duplicate
