### ISSUE TITLE
Request: HoYoLab

### ISSUE THREAD

**Issue by FOREVEREALIZE** [simple-icons/simple-icons#11430] opened 2024-07-07 14:03 UTC
### Brand Name

HoYoLab

### Website

https://hoyolab.com

### Popularity Metric

The SimilarWeb ranking is 915 (see [here](https://similarweb.com/website/hoyolab.com))

### Official Resources for Icon and Color

None

### Additional Comments

To be clear I am not referring to HoYoVerse/miHoYo's logo, I am referring to HoYoLab's logo (Mimo) that can be seen as favicon on [hoyolab.com](https://hoyolab.com).

**Comment by uncenter** [comment] 2024-09-18 00:46
Oops, just noticed this is a duplicate of #8390.

**Closed by uncenter** 2024-09-18 00:46 UTC
Labels: new icon
