### ISSUE TITLE
Request: Autocode icon

### ISSUE THREAD

**Issue by Edwin15857** [simple-icons/simple-icons#8009] opened 2022-11-01 16:14 UTC
### Brand Name

Autocode

### Website

https://autocode.com

### Popularity Metric

The similarweb rank is 126,700. See: https://www.similarweb.com/website/autocode.com/

### Official Resources for Icon and Color

svg: https://autocode.com/
color: #FFFFFF, #000000, from the main page of Autocode's website in the editor demo.

### Additional Comments

There are two logos for the company. The second logo's SVG is `https://autocode-static-assets.s3.us-west-2.amazonaws.com/content/autocode/release/static/branding/autocode-logo-wordmark-191612d1.svg`

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-11-02 13:41
Duplicate of #7247

**Closed by service-paradis** 2022-11-02 13:41 UTC
Labels: new icon
