### ISSUE TITLE
Solana

### ISSUE THREAD

**Issue by anvme** [simple-icons/simple-icons#9665] opened 2023-09-30 23:15 UTC
### Brand Name

Solana

### Website

https://solana.com

### Popularity Metric

#9 Blockchain

### Official Resources for Icon and Color

svg https://solana.com/src/img/branding/solanaLogoMark.svg

**Comment by service-paradis** [comment] 2023-10-02 12:19
Duplicate of #7415

**Closed by service-paradis** 2023-10-02 12:19 UTC
Labels: new icon
