### ISSUE TITLE
StackHawk Icon Request

### ISSUE THREAD

**Issue by aaronkwhite-sh** [simple-icons/simple-icons#7954] opened 2022-10-13 15:35 UTC
### Brand Name

StackHawk

### Website

https://stackhawk.com

### Popularity Metric

The Similiarweb rank is 421,693. See https://www.similarweb.com/website/stackhawk.com/#overview

### Official Resources for Icon and Color

![stackhawk](https://user-images.githubusercontent.com/59268514/195641228-3b8cfc56-95f6-42d5-8e68-dd47ebb8bc93.svg)

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-10-13 16:28
Duplicate of #5554

**Closed by service-paradis** 2022-10-13 16:28 UTC
Labels: new icon
