### ISSUE TITLE
Phoenix Framework Icon Request

### ISSUE THREAD

**Issue by marth141** [simple-icons/simple-icons#6976] opened 2021-12-22 20:02 UTC
Phoenix Framework is a pretty widely used tool for making live websites within the Elixir community.

**Comment by marth141** [comment] 2021-12-22 20:04
https://img.shields.io/badge/phoenixframework-E95122?style=for-the-badge&logo=phoenixframework&logoColor=white

**Comment by marth141** [comment] 2021-12-22 22:00
Should also be the same icon for Liveview, which is part of Phoenix

**Comment by mondeja** [comment] 2021-12-23 13:43
- Alexa rank: [177K](https://www.alexa.com/siteinfo/phoenixframework.org)
- Color: `#E95122`

Thanks for the request @marth141. Do you know about any vector image that we can use as the source?

**Comment by sachinraja** [comment] 2021-12-23 15:38
Duplicate of #4917 (one that I've had open for a while now)

**Closed by sachinraja** 2021-12-23 15:38 UTC
Labels: new icon
