### ISSUE TITLE
Provide an icon for kitsu

### ISSUE THREAD

**Issue by ahmubashshir** [simple-icons/simple-icons#3454] opened 2020-08-16 17:53 UTC
**Name:** Kitsu
**Website:** [kitsu.io](https://kitsu.io)
**Alexa rank:** 130,294
  

**Official resources for icon and color:**
 [https://github.com/hummingbird-me/kitsu-web](https://github.com/hummingbird-me/kitsu-web)

**Comment by NovaGL** [comment] 2020-08-17 01:29
Duplicate of #3355

**Closed by NovaGL** 2020-08-17 01:29 UTC
Labels: new icon
