### ISSUE TITLE
https://homebridge.io/

### ISSUE THREAD

**Issue by tompijls** [simple-icons/simple-icons#4700] opened 2021-01-09 18:44 UTC
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment] 2021-01-09 18:56
Hello @tompijls  
Please provide the needed information from our issue template. Otherwise your request won't be valid.

**Comment by adamrusted** [comment] 2021-01-09 22:15
Closing this as it's a duplicate of #3464, icon is already scheduled for release on Sunday.

**Closed by adamrusted** 2021-01-09 22:15 UTC
Labels: awaiting reply, new icon
