### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11069] opened 2024-05-30 06:10 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It is ranked 37,553 in SimilarWeb. See https://www.similarweb.com/website/matplotlib.org/#overview

### Official Resources for Icon and Color

svg: https://commons.wikimedia.org/wiki/File:Matplotlib_icon.svg

### Additional Comments

Matplotlib is one of the go to libraries for creating plots with Python. It is extensively used for Artificial Intelligence, Machine Learning, Deep Learning projects. It is one of the libraries that comes pre-installed when we access a Google Colab machine.

**Comment by service-paradis** [comment] 2024-05-30 17:35
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed by service-paradis** 2024-05-30 17:35 UTC
Labels: new icon
