### ISSUE TITLE
Fathom Analytics

### ISSUE THREAD

**Issue by pjrvs** [simple-icons/simple-icons#3757] opened 2020-10-23 14:01 UTC
Name: Fathom Analytics
Website: usefathom.com
Alexa: #108,272

Icon: https://usefathom.com/assets/brand/fathom-analytics-sm.svg
Color: #9187FF

**Comment by fbernhart** [comment] 2020-12-08 13:45
Closing this as a duplicate of #3404.

**Closed by fbernhart** 2020-12-08 13:45 UTC
Labels: duplicate, new icon

**Comment by PeterShaggyNoble** [comment] 2021-01-08 17:03
Added in #4289
