### ISSUE TITLE
Request: TypeORM

### ISSUE THREAD

**Issue by davesagraf** [simple-icons/simple-icons#10896] opened 2024-05-05 00:32 UTC
### Brand Name

TypeORM

### Website

https://typeorm.io/

### Popularity Metric

https://www.similarweb.com/website/typeorm.io/

### Official Resources for Icon and Color

https://raw.githubusercontent.com/typeorm/typeorm/master/resources/logo_big.png

### Additional Comments

Hi! 

Love your set of icons, but would like to see TypeORM as well.
You already have Prisma and Drizzle, so that's awesome, but TypeORM is the one I'm missing and would like to use to add to my tech stack portfolio.

Thanks!

**Comment by service-paradis** [comment] 2024-05-06 12:23
Duplicate of #8147

**Closed by service-paradis** 2024-05-06 12:23 UTC
Labels: new icon, vector unavailable

**Comment by davesagraf** [comment] 2024-05-12 11:09
@service-paradis @uncenter 

Hi everyone! 

I've read through the issue [#8147](https://github.com/simple-icons/simple-icons/issues/8147) , and I noticed that you had assigned someone to add TypeORM icon before, but then closed that issue (I'm assuming, those who were assigned, could not complete the task).

I wanted to ask you if I could contribute somehow and add TypeORM icon to your library? What are the requirements and what is the process?

Also, I've noticed the `vector unavailable` tag on this issue.

I'm attaching an `svg` here, which was made from the official TypeORM source `png`. Please, let me know, if the quality and other properties of the file meet your technical requirements, and if so, how could I add to your library and contribute.

Thanks!

![typeorm](https://github.com/simple-icons/simple-icons/assets/82801430/1f67a744-edbb-4c28-9099-0233e771e444)

**Comment by davesagraf** [comment] 2024-05-12 12:24
@service-paradis @uncenter 

Okay, actually I went through the icons source in this repo, and found some requirement patterns inside the SVGs.

I've taken [Amazon Document DB](https://github.com/simple-icons/simple-icons/blob/develop/icons/amazondocumentdb.svg) as the reference, because it's somewhat similar graphically to the TypeORM logo.

I've changed the viewBox to "0 0 24 24", simplified paths, transformed and scaled the original TypeORM SVG to fit the structure and properties of your SVGs.

Now, here's the code of the resulting SVG:
`<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>TypeORM</title><path d="M4.409 5.409Q3.4 4.653 3.437 3.373q.564-.57 1.367-.713a8 8 0 0 1 1.033-.107V3.86q-.615-.031-1.079.364-.379.528-.35 1.185M20.45 3.434q.004 1.222-.942 1.975.001-1.472-1.458-1.489V2.614q1.089-.028 2.035.501a4 4 0 0 1 .365.32"/><path d="M3.437 3.373q-.036 1.28.972 2.036.007 1.808-.015 3.615.01 1.218-.669 2.218a5 5 0 0 1-.592.547q.965.697 1.17 1.883a6 6 0 0 1 .09.881q.023 1.838.016 3.676-.968.72-.972 1.945-.285-.28-.41-.669a4.2 4.2 0 0 1-.183-.82 190 190 0 0 1-.06-4.527q-.04-.71-.426-1.306-.305-.362-.774-.425a13 13 0 0 1 .03-1.276q.658-.119.927-.73a3.5 3.5 0 0 0 .243-1.002q.003-2.264.06-4.527.061-.859.593-1.519m17.013.061q.505.602.592 1.398a173 173 0 0 1 .06 4.435q.005.893.517 1.61.296.258.684.334a13 13 0 0 1 .03 1.276q-.665.096-.957.7-.247.581-.273 1.214a173 173 0 0 1-.061 4.436q-.064.6-.365 1.124-.093.157-.227.273.018-1.237-.942-2.005-.008-1.944.015-3.888.048-1.09.668-1.975a3.7 3.7 0 0 1 .593-.532q-.965-.648-1.17-1.807a6 6 0 0 1-.091-.669q-.023-1.974-.015-3.95.946-.752.942-1.974"/><path fill-rule="evenodd" d="M8.115 5.044q2.522-.007 5.043.016.042.017.076.045.053 1.5.046 3.008l-.015 2.947a.3.3 0 0 1-.046.076 55 55 0 0 1-2.582.045l-2.522-.015a.3.3 0 0 1-.076-.046 147 147 0 0 1-.03-5.954q.031-.084.106-.122m.122.243h4.8v5.651h-4.8z"/><path fill-rule="evenodd" d="M8.784 6.168h3.767v.243H8.784zm0 1.216h.364v.243h-.364zm.486 0h3.28v.243H9.27z"/><path d="M14.009 8.113h1.762v7.473h-1.762v-.243h1.519V8.356h-1.519z"/><path fill-rule="evenodd" d="M8.784 8.72h.364v.243h-.364zm.486 0h3.28v.243H9.27zm-.486 1.337h.364v.243h-.364zm.486 0h3.28v.243H9.27zm-1.155 2.218q2.522-.008 5.043.015.042.017.076.046.053 1.5.046 3.007l-.015 2.947a.3.3 0 0 1-.046.076 55 55 0 0 1-2.582.046l-2.522-.016a.3.3 0 0 1-.076-.045 147 147 0 0 1-.03-5.955q.031-.084.106-.121m.122.243h4.8v5.65h-4.8z"/><path fill-rule="evenodd" d="M8.784 13.399h3.767v.243H8.784zm0 1.215h.364v.243h-.364zm.486 0h3.28v.243H9.27zm-.486 1.337h.364v.243h-.364zm.486 0h3.28v.243H9.27zm-.486 1.336h.364v.244h-.364zm.486 0h3.28v.244H9.27z"/><path d="M4.409 18.23q-.029.727.486 1.23.43.273.942.228v1.306q-1.109.05-2.066-.501a1.7 1.7 0 0 1-.334-.32q.004-1.223.972-1.944m15.099 0q.96.768.942 2.005-.32.381-.79.562-.78.287-1.61.259v-1.307q.662.06 1.139-.395.322-.513.319-1.124"/></svg>`

And here's what it looks like:
![typeorm](https://github.com/simple-icons/simple-icons/assets/82801430/aef48686-0471-4f8f-bdc1-0127d83e7ebb)


Can I open a PR?

Thanks!

**Comment by uncenter** [comment] 2024-05-12 12:56
Go ahead! Note that as per our requirements that SVG isn't completely done - there needs to be only a single `<path>` element and no extra attributes on said `<path>` element.

**Comment by davesagraf** [comment] 2024-05-12 22:02
@uncenter 
Hi again!

I've followed your advice and also all the guidelines from [Contributing to Simple Icons](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)

Here's my `typeorm.svg` now:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>TypeORM</title><path d="M22.592 6.839c0 .9-.008 1.742.004 2.583.006.355.07.708.211 1.038.132.306.349.544.652.692.153.075.315.131.47.204.032.014.067.065.067.099q.008.58 0 1.16c0 .039-.053.097-.094.11a1.82 1.82 0 0 0-1.179 1.22c-.125.387-.137.785-.137 1.187q.002 2.24-.006 4.48c0 .466-.07.926-.225 1.363-.087.241-.227.463-.348.69-.015.031-.05.052-.08.073-.186.137-.365.287-.561.407-.168.103-.354.177-.535.255-.114.048-.236.082-.353.121q-.024.01-.05.014c-.23.028-.46.062-.69.083q-.418.033-.835.052c-.06.003-.122-.02-.183-.026-.104-.01-.129-.07-.127-.168a32 32 0 0 0 0-1.017c0-.104.026-.15.138-.141.118.007.24.012.355-.004q.333-.047.656-.125a3 3 0 0 0 .441-.153.94.94 0 0 0 .456-.409c.125-.208.185-.437.236-.676.057-.263.037-.52.04-.78.007-1.485 0-2.97.008-4.456q.003-.47.078-.935a2.15 2.15 0 0 1 1.092-1.585l.25-.143c.062-.037.054-.107-.016-.144a2.8 2.8 0 0 1-.816-.646 2.1 2.1 0 0 1-.39-.711c-.182-.551-.205-1.12-.203-1.694.002-1.446-.01-2.892 0-4.337a3 3 0 0 0-.072-.666c-.081-.37-.24-.712-.59-.909a2.3 2.3 0 0 0-.468-.177 3 3 0 0 0-.504-.11 4 4 0 0 0-.541-.025c-.112.001-.152-.03-.15-.147.007-.364.004-.728.002-1.092 0-.089.028-.122.117-.119.195.005.39-.007.584.004.273.016.546.035.816.073a3.1 3.1 0 0 1 1.6.714c.252.215.408.479.534.772.15.346.228.71.276 1.082.13.99.03 1.986.073 2.918ZM1.396 6.691c0-.581-.006-1.163.002-1.745.005-.382.008-.77.049-1.149.027-.263.11-.52.18-.778a1.8 1.8 0 0 1 .367-.723c.147-.17.32-.326.508-.449.194-.127.417-.208.63-.305.169-.076.348-.108.53-.141a8.3 8.3 0 0 1 1.576-.125c.089 0 .121.027.12.117q-.004.558 0 1.118c0 .091-.029.126-.123.122a1.6 1.6 0 0 0-.322.003 8 8 0 0 0-.705.127c-.149.035-.291.094-.434.148a.94.94 0 0 0-.46.406c-.124.208-.184.44-.239.68-.068.3.007.588.002.882-.02 1.329-.006 2.658-.011 3.99a10 10 0 0 1-.05 1.098c-.081.724-.385 1.328-1.025 1.727q-.174.103-.346.209c-.023.014-.052.049-.047.068a.14.14 0 0 0 .058.084 2.9 2.9 0 0 1 .844.678c.19.23.312.494.4.78.151.496.16 1.006.165 1.516.008 1.298.002 2.597.003 3.896 0 .144.014.288.012.431 0 .072-.024.143-.027.215q-.004.126.006.253c.003.052.02.104.028.156.044.301.138.583.337.817.132.153.303.252.495.321.201.072.41.1.616.149.246.058.486.044.73.054.066.003.091.03.091.093 0 .392.002.784-.004 1.176 0 .029-.054.081-.083.081-.252.005-.504.01-.755-.002a5 5 0 0 1-.678-.069c-.234-.044-.461-.122-.691-.186a2.15 2.15 0 0 1-.957-.572 1.9 1.9 0 0 1-.376-.54 4.2 4.2 0 0 1-.292-.87 5 5 0 0 1-.104-.964c-.015-1.423-.013-2.846-.022-4.268-.002-.322-.004-.645-.039-.964-.04-.36-.12-.712-.343-1.013a1.5 1.5 0 0 0-.624-.487c-.11-.048-.227-.083-.335-.137-.037-.02-.077-.075-.077-.115q-.006-.56-.003-1.118c0-.1.088-.118.156-.141.372-.13.676-.348.892-.684a2.05 2.05 0 0 0 .343-1.087c.023-.92.03-1.841.044-2.76h-.014Zm6.042.98v-3.11c0-.295.175-.472.472-.472h5.159c.296 0 .473.177.473.472v6.2c0 .32-.17.49-.489.49-1.709 0-3.416-.002-5.125.004-.288 0-.495-.197-.492-.493.007-1.03.003-2.06.003-3.091m.245.002v3.091c0 .208.035.242.24.242h5.125c.215 0 .247-.03.247-.244V4.579c0-.213-.033-.245-.245-.245H7.927c-.21 0-.243.033-.243.247zm-.245 8.39v-3.1c0-.298.173-.474.471-.474h5.159c.3 0 .473.177.473.48v6.184q0 .499-.497.499H7.929c-.32 0-.489-.17-.489-.489zm.245.006v3.109c0 .189.039.228.228.228h5.148c.202 0 .236-.035.236-.239V12.97c0-.197-.038-.234-.233-.234h-5.14c-.205 0-.24.035-.24.243zm8.752-4.058q-.002 2.09.002 4.184c0 .11-.03.143-.141.142a97 97 0 0 0-1.754 0c-.104 0-.12-.04-.12-.13-.001-.093.03-.12.121-.12.5.004 1 0 1.5.004.108 0 .148-.031.148-.145q-.003-3.934 0-7.868c0-.112-.036-.147-.147-.146-.5.005-1 0-1.5.004-.1 0-.122-.034-.122-.128 0-.09.024-.122.118-.121q.89.005 1.779 0c.096 0 .117.033.117.122q-.002 2.101 0 4.202m-5.908-6.336q-1.025 0-2.049-.002c-.04 0-.109-.01-.112-.028-.013-.061-.005-.127 0-.191 0-.01.031-.02.05-.023q.041-.004.084-.002h4.048c.133 0 .194.088.137.208-.011.024-.066.036-.1.036q-.847.002-1.693.001zm.275 1.413c-.587 0-1.174-.004-1.761.003-.13 0-.118-.068-.123-.153-.007-.102.055-.097.123-.097h3.53c.068 0 .13-.004.124.097-.006.086.006.154-.124.153-.59-.008-1.179-.003-1.768-.003Zm.004 1.307c.59 0 1.18.002 1.769-.002.104 0 .118.041.12.13.001.093-.029.12-.12.12a738 738 0 0 0-3.54 0c-.093 0-.121-.029-.119-.121 0-.09.018-.13.12-.13q.887.005 1.77.003m-.009 1.797c-.586 0-1.175-.002-1.761.002-.094 0-.12-.03-.12-.122 0-.093.022-.128.123-.126q1.766.006 3.532 0c.098 0 .124.03.124.125.002.1-.032.124-.128.123q-.885-.003-1.77-.002M8.547 8.64h-.035c-.16 0-.202-.034-.147-.187.045-.129.186-.035.28-.055.028-.004.088.033.092.06.03.172.017.181-.19.181Zm.002-1.799h.034c.167 0 .206.031.148.19-.047.13-.187.034-.283.052-.024.006-.081-.038-.085-.064-.023-.177-.02-.177.186-.177Zm.002 3.351H8.5q-.206.001-.138-.2c.006-.02.038-.04.06-.042.06-.006.118-.002.177-.002.132 0 .19.086.135.208-.007.018-.042.03-.066.034-.038.006-.079.002-.118.002Zm1.976 3.638q1.025.001 2.049-.002c.092 0 .121.027.121.12 0 .09-.018.13-.12.128a880 880 0 0 0-4.098 0c-.096 0-.126-.027-.126-.124s.03-.125.125-.125q1.026.004 2.049.003m.272 1.658c-.586 0-1.173-.004-1.76.003-.135 0-.113-.076-.119-.156-.007-.097.052-.094.119-.094h3.538c.075 0 .127.005.12.103-.007.081.007.15-.12.148-.592-.006-1.185-.002-1.778-.002Zm0 1.551q-.88-.002-1.76.002c-.101 0-.12-.037-.121-.129 0-.091.028-.12.12-.12q1.77.004 3.539 0c.091 0 .122.027.12.12 0 .089-.016.13-.12.128q-.888-.004-1.777-.002Zm.009 1.309q.885.002 1.77-.002c.095 0 .12.033.12.122-.003.086-.016.127-.117.126a743 743 0 0 0-3.549 0c-.092 0-.116-.033-.114-.118.002-.08.006-.131.111-.13q.89.004 1.779.002M8.55 15.24h.025c.177 0 .2.013.157.185-.032.13-.161.042-.245.06-.044.008-.118.033-.128-.06-.021-.179-.016-.184.192-.184Zm-.003 1.554h.047c.14 0 .19.07.141.204-.007.019-.04.036-.062.038-.063.005-.125-.003-.187.003-.101.012-.133-.026-.135-.13-.002-.187.135-.087.196-.115m.002 1.798h-.051c-.135 0-.184-.067-.136-.202.006-.018.038-.038.061-.04.055-.006.112-.002.167-.002.145 0 .192.062.146.2-.007.02-.038.038-.061.042-.042.005-.084.001-.125.001Z"/></svg>`

And that's a part of json I wanted to add to `_data/simple-icons.json`:
`        {
            "title": "TypeORM",
            "hex": "FE0803",
            "source": "https://raw.githubusercontent.com/typeorm/typeorm/master/resources/logo_big.png",
            "license": {
                "type": "MIT"
            }
        },`

Now, I have a problem though.

I've followed all the steps like forking the repo, cloning it, creating a new branch from `develop` and adding changes there.

But when I commit and try to push to a new branch I've just created with `git push --set-upstream origin feat/typeorm_icon`  to open a PR, I get an error:
<img width="1020" alt="Screenshot 2024-05-13 at 01 00 12" src="https://github.com/simple-icons/simple-icons/assets/82801430/29304d11-4411-4cdd-8aa9-9831e2f3eb74">

Do I have to be added as a contributor to this repo first, or am I missing something? 

Thanks!

**Comment by uncenter** [comment] 2024-05-12 22:05
You need to fork this repository and then make a pull request. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request. Also, let's try to keep discussion in the open #8147 issue! (P.S. I also recommend you take a look at https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks for a guide on how to create code blocks instead of inline code like you are doing now.)

**Comment by davesagraf** [comment] 2024-05-12 22:07
@uncenter 
Okay, thank you!
