### ISSUE TITLE
Disney!

### ISSUE THREAD

**Issue by joewalls123** [simple-icons/simple-icons#9248] opened 2023-08-09 13:48 UTC
### Brand Name

Disney

### Website

https://disney.com/

### Popularity Metric

SimilarWeb global rank is 6,053

### Official Resources for Icon and Color

none

### Additional Comments

It's Disney.....

### Contributing

No

**Comment by service-paradis** [comment] 2023-08-09 13:57
Duplicate of https://github.com/simple-icons/simple-icons/issues/2309. Disney are VERY protective of their brands, and we cannot risk any legal activity against this project or its contributors.

**Closed** 2023-08-09 13:57 UTC
Labels: new icon, won't add, duplicate
