### ISSUE TITLE
Pipedream

### ISSUE THREAD

**Issue by fiorins** [simple-icons/simple-icons#11459] opened 2024-07-11 16:30 UTC
### Brand Name

Pipedream

### Website

https://pipedream.com/

### Popularity Metric

The Similarweb rank is 103,321

### Official Resources for Icon and Color

None

**Comment by CodeShakingSheep** [comment] 2024-07-11 17:11
Duplicate of https://github.com/simple-icons/simple-icons/issues/10384.

**Comment by uncenter** [comment] 2024-07-11 17:32
Please search existing issues before opening new ones @fiorins!

**Closed by uncenter** 2024-07-11 17:32 UTC
Labels: new icon
