### ISSUE TITLE
Add FabricMC and QuiltMC

### ISSUE THREAD

**Issue by Jaffe2718** [simple-icons/simple-icons#9486] opened 2023-09-03 13:13 UTC
### Brand Name

FabricMC/QuiltMC

### Website

[FabricMC](https://fabricmc.net/) [QuiltMC](https://quiltmc.org/en/)

### Popularity Metric

The Similarweb rank of FabricMC is 52,126. See https://www.similarweb.com/website/fabricmc.net/
The Similarweb rank of QuiltMC is 404,753. See https://www.similarweb.com/website/quiltmc.org/

### FabricMC
```svg
<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg" role="group">

 <g>
  <title>Layer 1</title>
  <g id="svg_257">
   <rect id="svg_9" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="0" x="8"/>
   <rect id="svg_10" fill="rgba(31, 26, 14, 206)" height="1" width="1" x="9"/>
   <rect id="svg_24" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="1" x="7"/>
   <rect id="svg_25" fill="rgba(155, 144, 123, 255)" height="1" width="1" y="1" x="8"/>
   <rect id="svg_26" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="1" x="9"/>
   <rect id="svg_27" fill="rgba(9, 5, 0, 255)" height="1" width="1" y="1" x="10"/>
   <rect id="svg_40" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="2" x="7"/>
   <rect id="svg_41" fill="rgba(142, 131, 112, 255)" height="1" width="1" y="2" x="8"/>
   <rect id="svg_42" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="2" x="9"/>
   <rect id="svg_43" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="2" x="10"/>
   <rect id="svg_44" fill="rgba(7, 0, 0, 210)" height="1" width="1" y="2" x="11"/>
   <rect id="svg_55" fill="rgba(27, 24, 16, 95)" height="1" width="1" y="3" x="6"/>
   <rect id="svg_56" fill="rgba(124, 114, 96, 194)" height="1" width="1" y="3" x="7"/>
   <rect id="svg_57" fill="rgba(147, 137, 117, 255)" height="1" width="1" y="3" x="8"/>
   <rect id="svg_58" fill="rgba(155, 144, 123, 255)" height="1" width="1" y="3" x="9"/>
   <rect id="svg_59" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="3" x="10"/>
   <rect id="svg_60" fill="rgba(155, 144, 123, 255)" height="1" width="1" y="3" x="11"/>
   <rect id="svg_61" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="3" x="12"/>
   <rect id="svg_62" fill="rgba(20, 20, 10, 25)" height="1" width="1" y="3" x="13"/>
   <rect id="svg_70" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="4" x="5"/>
   <rect id="svg_71" fill="rgba(124, 114, 98, 235)" height="1" width="1" y="4" x="6"/>
   <rect id="svg_72" fill="rgba(191, 179, 155, 255)" height="1" width="1" y="4" x="7"/>
   <rect id="svg_73" fill="rgba(191, 179, 155, 255)" height="1" width="1" y="4" x="8"/>
   <rect id="svg_74" fill="rgba(142, 131, 112, 255)" height="1" width="1" y="4" x="9"/>
   <rect id="svg_75" fill="rgba(123, 114, 98, 255)" height="1" width="1" y="4" x="10"/>
   <rect id="svg_76" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="4" x="11"/>
   <rect id="svg_77" fill="rgba(147, 137, 117, 255)" height="1" width="1" y="4" x="12"/>
   <rect id="svg_78" fill="rgba(81, 74, 59, 163)" height="1" width="1" y="4" x="13"/>
   <rect id="svg_79" fill="rgba(20, 20, 10, 25)" height="1" width="1" y="4" x="14"/>
   <rect id="svg_85" fill="rgba(6, 0, 0, 44)" height="1" width="1" y="5" x="4"/>
   <rect id="svg_86" fill="rgba(93, 85, 70, 255)" height="1" width="1" y="5" x="5"/>
   <rect id="svg_87" fill="rgba(191, 179, 155, 255)" height="1" width="1" y="5" x="6"/>
   <rect id="svg_88" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="5" x="7"/>
   <rect id="svg_89" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="5" x="8"/>
   <rect id="svg_90" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="5" x="9"/>
   <rect id="svg_91" fill="rgba(79, 72, 59, 255)" height="1" width="1" y="5" x="10"/>
   <rect id="svg_92" fill="rgba(168, 157, 136, 255)" height="1" width="1" y="5" x="11"/>
   <rect id="svg_93" fill="rgba(234, 219, 189, 255)" height="1" width="1" y="5" x="12"/>
   <rect id="svg_94" fill="rgba(104, 95, 80, 255)" height="1" width="1" y="5" x="13"/>
   <rect id="svg_95" fill="rgba(40, 35, 22, 102)" height="1" width="1" y="5" x="14"/>
   <rect id="svg_96" fill="rgba(32, 32, 32, 16)" height="1" width="1" y="5" x="15"/>
   <rect id="svg_100" fill="rgba(6, 0, 0, 44)" height="1" width="1" y="6" x="3"/>
   <rect id="svg_101" fill="rgba(93, 85, 70, 255)" height="1" width="1" y="6" x="4"/>
   <rect id="svg_102" fill="rgba(240, 224, 193, 255)" height="1" width="1" y="6" x="5"/>
   <rect id="svg_103" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="6" x="6"/>
   <rect id="svg_104" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="6" x="7"/>
   <rect id="svg_105" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="6" x="8"/>
   <rect id="svg_106" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="6" x="9"/>
   <rect id="svg_107" fill="rgba(234, 219, 189, 255)" height="1" width="1" y="6" x="10"/>
   <rect id="svg_108" fill="rgba(56, 50, 37, 255)" height="1" width="1" y="6" x="11"/>
   <rect id="svg_109" fill="rgba(176, 164, 142, 255)" height="1" width="1" y="6" x="12"/>
   <rect id="svg_110" fill="rgba(104, 95, 80, 255)" height="1" width="1" y="6" x="13"/>
   <rect id="svg_111" fill="rgba(56, 50, 37, 255)" height="1" width="1" y="6" x="14"/>
   <rect id="svg_112" fill="rgba(51, 45, 33, 125)" height="1" width="1" y="6" x="15"/>
   <rect id="svg_115" fill="rgba(6, 0, 0, 44)" height="1" width="1" y="7" x="2"/>
   <rect id="svg_116" fill="rgba(9, 5, 0, 255)" height="1" width="1" y="7" x="3"/>
   <rect id="svg_117" fill="rgba(240, 224, 193, 255)" height="1" width="1" y="7" x="4"/>
   <rect id="svg_118" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="7" x="5"/>
   <rect id="svg_119" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="7" x="6"/>
   <rect id="svg_120" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="7" x="7"/>
   <rect id="svg_121" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="7" x="8"/>
   <rect id="svg_122" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="7" x="9"/>
   <rect id="svg_123" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="7" x="10"/>
   <rect id="svg_124" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="7" x="11"/>
   <rect id="svg_125" fill="rgba(9, 5, 0, 255)" height="1" width="1" y="7" x="12"/>
   <rect id="svg_126" fill="rgba(123, 114, 98, 255)" height="1" width="1" y="7" x="13"/>
   <rect id="svg_127" fill="rgba(79, 72, 59, 255)" height="1" width="1" y="7" x="14"/>
   <rect id="svg_128" fill="rgba(51, 45, 33, 125)" height="1" width="1" y="7" x="15"/>
   <rect id="svg_130" fill="rgba(6, 0, 0, 44)" height="1" width="1" y="8" x="1"/>
   <rect id="svg_131" fill="rgba(93, 85, 70, 255)" height="1" width="1" y="8" x="2"/>
   <rect id="svg_132" fill="rgba(240, 224, 193, 255)" height="1" width="1" y="8" x="3"/>
   <rect id="svg_133" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="8" x="4"/>
   <rect id="svg_134" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="8" x="5"/>
   <rect id="svg_135" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="8" x="6"/>
   <rect id="svg_136" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="8" x="7"/>
   <rect id="svg_137" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="8" x="8"/>
   <rect id="svg_138" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="8" x="9"/>
   <rect id="svg_139" fill="rgba(191, 179, 155, 255)" height="1" width="1" y="8" x="10"/>
   <rect id="svg_140" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="8" x="11"/>
   <rect id="svg_141" fill="rgba(42, 36, 24, 255)" height="1" width="1" y="8" x="12"/>
   <rect id="svg_142" fill="rgba(56, 50, 37, 255)" height="1" width="1" y="8" x="13"/>
   <rect id="svg_143" fill="rgba(34, 28, 17, 45)" height="1" width="1" y="8" x="14"/>
   <rect id="svg_145" fill="rgba(51, 45, 33, 125)" height="1" width="1" y="9" x="0"/>
   <rect id="svg_146" fill="rgba(93, 85, 70, 255)" height="1" width="1" y="9" x="1"/>
   <rect id="svg_147" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="9" x="2"/>
   <rect id="svg_148" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="9" x="3"/>
   <rect id="svg_149" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="9" x="4"/>
   <rect id="svg_150" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="9" x="5"/>
   <rect id="svg_151" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="9" x="6"/>
   <rect id="svg_152" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="9" x="7"/>
   <rect id="svg_153" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="9" x="8"/>
   <rect id="svg_154" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="9" x="9"/>
   <rect id="svg_155" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="9" x="10"/>
   <rect id="svg_156" fill="rgba(9, 5, 0, 255)" height="1" width="1" y="9" x="11"/>
   <rect id="svg_161" fill="rgba(51, 45, 33, 125)" height="1" width="1" y="10" x="0"/>
   <rect id="svg_162" fill="rgba(79, 72, 59, 255)" height="1" width="1" y="10" x="1"/>
   <rect id="svg_163" fill="rgba(176, 164, 142, 255)" height="1" width="1" y="10" x="2"/>
   <rect id="svg_164" fill="rgba(191, 179, 155, 255)" height="1" width="1" y="10" x="3"/>
   <rect id="svg_165" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="10" x="4"/>
   <rect id="svg_166" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="10" x="5"/>
   <rect id="svg_167" fill="rgba(221, 206, 178, 255)" height="1" width="1" y="10" x="6"/>
   <rect id="svg_168" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="10" x="7"/>
   <rect id="svg_169" fill="rgba(201, 187, 163, 255)" height="1" width="1" y="10" x="8"/>
   <rect id="svg_170" fill="rgba(186, 173, 150, 255)" height="1" width="1" y="10" x="9"/>
   <rect id="svg_171" fill="rgba(93, 85, 70, 255)" height="1" width="1" y="10" x="10"/>
   <rect id="svg_172" fill="rgba(34, 28, 17, 45)" height="1" width="1" y="10" x="11"/>
   <rect id="svg_177" fill="rgba(49, 45, 31, 57)" height="1" width="1" y="11" x="0"/>
   <rect id="svg_178" fill="rgba(81, 74, 59, 163)" height="1" width="1" y="11" x="1"/>
   <rect id="svg_179" fill="rgba(123, 114, 98, 255)" height="1" width="1" y="11" x="2"/>
   <rect id="svg_180" fill="rgba(168, 157, 136, 255)" height="1" width="1" y="11" x="3"/>
   <rect id="svg_181" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="11" x="4"/>
   <rect id="svg_182" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="11" x="5"/>
   <rect id="svg_183" fill="rgba(226, 211, 182, 255)" height="1" width="1" y="11" x="6"/>
   <rect id="svg_184" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="11" x="7"/>
   <rect id="svg_185" fill="rgba(168, 157, 136, 255)" height="1" width="1" y="11" x="8"/>
   <rect id="svg_186" fill="rgba(124, 114, 98, 235)" height="1" width="1" y="11" x="9"/>
   <rect id="svg_187" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="11" x="10"/>
   <rect id="svg_194" fill="rgba(32, 32, 32, 16)" height="1" width="1" y="12" x="1"/>
   <rect id="svg_195" fill="rgba(81, 74, 59, 163)" height="1" width="1" y="12" x="2"/>
   <rect id="svg_196" fill="rgba(104, 95, 80, 255)" height="1" width="1" y="12" x="3"/>
   <rect id="svg_197" fill="rgba(168, 157, 136, 255)" height="1" width="1" y="12" x="4"/>
   <rect id="svg_198" fill="rgba(206, 192, 167, 255)" height="1" width="1" y="12" x="5"/>
   <rect id="svg_199" fill="rgba(214, 200, 173, 255)" height="1" width="1" y="12" x="6"/>
   <rect id="svg_200" fill="rgba(176, 164, 142, 255)" height="1" width="1" y="12" x="7"/>
   <rect id="svg_201" fill="rgba(104, 96, 80, 194)" height="1" width="1" y="12" x="8"/>
   <rect id="svg_202" fill="rgba(27, 24, 16, 95)" height="1" width="1" y="12" x="9"/>
   <rect id="svg_211" fill="rgba(20, 20, 10, 25)" height="1" width="1" y="13" x="2"/>
   <rect id="svg_212" fill="rgba(34, 30, 17, 207)" height="1" width="1" y="13" x="3"/>
   <rect id="svg_213" fill="rgba(142, 131, 112, 255)" height="1" width="1" y="13" x="4"/>
   <rect id="svg_214" fill="rgba(176, 164, 142, 255)" height="1" width="1" y="13" x="5"/>
   <rect id="svg_215" fill="rgba(168, 157, 136, 255)" height="1" width="1" y="13" x="6"/>
   <rect id="svg_216" fill="rgba(123, 114, 98, 255)" height="1" width="1" y="13" x="7"/>
   <rect id="svg_217" fill="rgba(24, 18, 8, 128)" height="1" width="1" y="13" x="8"/>
   <rect id="svg_229" fill="rgba(32, 25, 12, 210)" height="1" width="1" y="14" x="4"/>
   <rect id="svg_230" fill="rgba(147, 137, 117, 255)" height="1" width="1" y="14" x="5"/>
   <rect id="svg_231" fill="rgba(79, 72, 59, 255)" height="1" width="1" y="14" x="6"/>
   <rect id="svg_232" fill="rgba(44, 40, 28, 235)" height="1" width="1" y="14" x="7"/>
   <rect id="svg_233" fill="rgba(27, 24, 16, 95)" height="1" width="1" y="14" x="8"/>
   <rect id="svg_246" fill="rgba(42, 36, 24, 255)" height="1" width="1" y="15" x="5"/>
   <rect id="svg_247" fill="rgba(56, 50, 37, 255)" height="1" width="1" y="15" x="6"/>
   <rect id="svg_248" fill="rgba(51, 45, 33, 125)" height="1" width="1" y="15" x="7"/>
  </g>
 </g>
</svg>
```
### QuiltMC
```svg
<svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 913.53 913.53">
    <defs>
        <style>.cls-1{fill:#9722ff}.cls-2{fill:#dc29dd}.cls-3{fill:#27a2fd}.cls-4{fill:#34f}</style>
    </defs>
    <path d="M249.16 128.54a15.28 15.28 0 0 0 15.26 15.27h26v58h-26a15.27 15.27 0 0 0 0 30.53h26v44.5a13.52 13.52 0 0 1-13.52 13.53h-44.5v-26a15.27 15.27 0 0 0-30.54 0v26h-58v-26a15.27 15.27 0 1 0-30.53 0v26H68.77a13.54 13.54 0 0 1-13.53-13.53V68.78a13.53 13.53 0 0 1 13.53-13.53h208.09a13.52 13.52 0 0 1 13.52 13.53v44.48h-26a15.27 15.27 0 0 0-15.22 15.28Z"
          class="cls-1"/>
    <path d="M514.84 128.54a15.27 15.27 0 0 0 15.26 15.27h26v58h-26a15.27 15.27 0 0 0 0 30.53h26v44.5a13.53 13.53 0 0 1-13.52 13.53H334.45a13.52 13.52 0 0 1-13.52-13.53v-44.5h25.94a15.27 15.27 0 1 0 0-30.53h-25.94v-58h25.94a15.28 15.28 0 1 0 0-30.55h-25.94V68.78a13.51 13.51 0 0 1 13.52-13.53h208.09a13.52 13.52 0 0 1 13.52 13.53v44.48h-26a15.27 15.27 0 0 0-15.22 15.28Z"
          class="cls-2"/>
    <path d="M821.73 68.78v208.08a13.52 13.52 0 0 1-13.52 13.53h-44.5v-26a15.27 15.27 0 1 0-30.53 0v26h-58v-26a15.27 15.27 0 1 0-30.53 0v26h-44.5a13.54 13.54 0 0 1-13.53-13.53v-44.5h26a15.27 15.27 0 1 0 0-30.53h-26v-58h26a15.28 15.28 0 0 0 0-30.55h-26v-44.5a13.53 13.53 0 0 1 13.53-13.53h208.06a13.52 13.52 0 0 1 13.52 13.53Z"
          class="cls-3"/>
    <path d="M290.38 334.44v208.09a13.52 13.52 0 0 1-13.52 13.53h-44.5v-26a15.27 15.27 0 0 0-30.54 0v26h-58v-26a15.27 15.27 0 1 0-30.53 0v26H68.77a13.53 13.53 0 0 1-13.53-13.53V334.44a13.54 13.54 0 0 1 13.53-13.52h44.5v26a15.27 15.27 0 0 0 30.53 0v-26h58v26a15.27 15.27 0 0 0 30.54 0v-26h44.5a13.52 13.52 0 0 1 13.54 13.52Z"
          class="cls-2"/>
    <path d="M514.84 394.21a15.25 15.25 0 0 0 15.26 15.26h26v58h-26a15.27 15.27 0 0 0 0 30.53h26v44.5a13.52 13.52 0 0 1-13.52 13.53H498v-26a15.27 15.27 0 1 0-30.53 0v26h-58v-26a15.27 15.27 0 1 0-30.54 0v26h-44.48a13.51 13.51 0 0 1-13.52-13.53V334.44a13.52 13.52 0 0 1 13.52-13.52h208.09a13.53 13.53 0 0 1 13.52 13.52v44.5h-26a15.26 15.26 0 0 0-15.22 15.27Z"
          class="cls-3"/>
    <path d="M821.73 334.44v208.09a13.52 13.52 0 0 1-13.52 13.53H600.12a13.53 13.53 0 0 1-13.53-13.53V498h26a15.27 15.27 0 1 0 0-30.53h-26v-58h26a15.27 15.27 0 1 0 0-30.53h-26v-44.5a13.54 13.54 0 0 1 13.53-13.52h44.5v26a15.27 15.27 0 0 0 30.53 0v-26h58v26a15.27 15.27 0 0 0 30.53 0v-26h44.5a13.52 13.52 0 0 1 13.55 13.52Z"
          class="cls-4"/>
    <path d="M249.16 659.89a15.28 15.28 0 0 0 15.26 15.27h26v58h-26a15.27 15.27 0 0 0 0 30.54h26v44.5a13.52 13.52 0 0 1-13.52 13.53H68.77a13.54 13.54 0 0 1-13.53-13.53V600.13a13.53 13.53 0 0 1 13.53-13.53h44.5v25.95a15.27 15.27 0 1 0 30.53 0V586.6h58v25.95a15.27 15.27 0 1 0 30.54 0V586.6h44.5a13.52 13.52 0 0 1 13.52 13.53v44.48h-26a15.28 15.28 0 0 0-15.2 15.28Z"
          class="cls-1"/>
    <path d="M556.06 600.13v208.08a13.53 13.53 0 0 1-13.52 13.53H334.45a13.52 13.52 0 0 1-13.52-13.53v-44.5h25.94a15.27 15.27 0 1 0 0-30.54h-25.94v-58h25.94a15.28 15.28 0 1 0 0-30.55h-25.94v-44.49a13.51 13.51 0 0 1 13.52-13.53h44.49v25.95a15.27 15.27 0 1 0 30.54 0V586.6h58v25.95a15.27 15.27 0 1 0 30.53 0V586.6h44.5a13.52 13.52 0 0 1 13.55 13.53Z"
          class="cls-4"/>
    <rect width="235.14" height="235.14" x="635.3" y="635.29" class="cls-1" rx="13.53"
          transform="rotate(-45 752.857 752.866)"/>
</svg>
```

### FabricMC

FabricMC is a popular Minecraft modding API that allows for the creation of custom Minecraft mods. It provides a user-friendly development environment for modders and allows for the integration of various modding features and functionality. FabricMC is known for its stability, performance, and compatibility with other Minecraft mods and is widely used by modders and players alike.

### QuiltMC

QuiltMC is a Minecraft modding API that focuses on providing a streamlined development experience for modders. It offers a simplified modding pipeline and provides a range of features and functionality that make modding easier and more efficient. QuiltMC is designed to work seamlessly with other Minecraft mods and is widely used by modders who are looking for a user-friendly and powerful modding tool.

### Contributing

No

**Comment by solonovamax** [comment] 2023-09-08 13:21
Partial duplicate of #7465. I included fabric in there, however removed quilt as at the time it was a lot less popular. I'll edit it right now to add quilt to the issue.

**Comment by solonovamax** [comment] 2023-09-08 13:36
Also, I'm going to copy the SVGs from here over to the other issue.

**Comment by service-paradis** [comment] 2023-09-14 17:37
Closing this one in favor of https://github.com/simple-icons/simple-icons/issues/7465

**Closed by service-paradis** 2023-09-14 17:37 UTC
Labels: new icon
