### ISSUE TITLE
Final Cut Pro X

### ISSUE THREAD

**Issue by FelipeSilva916** [simple-icons/simple-icons#6191] opened 2021-08-02 12:44 UTC
**Brand Name:** Final Cut Pro
**Website:** https://www.apple.com/final-cut-pro/
**Alexa rank:** #55 world wide #31 USA

  

**Official resources for icon and color:**

**Comment by service-paradis** [comment] 2021-08-03 13:21
Duplicate of #5372

**Closed** 2021-08-03 13:21 UTC
Labels: duplicate, new icon
