### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by Corefinder89** [simple-icons/simple-icons#3544] opened 2020-09-09 09:24 UTC
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment] 2020-09-09 23:49
Please fill in the requested information so we can look into your request.

**Comment by Corefinder89** [comment] 2020-09-20 05:26
Name: Selenium
Website: https://www.selenium.dev/
Official resources for icon and color: https://www.selenium.dev/images/selenium_logo_square_green.png

**Comment by mondeja** [comment] 2020-11-16 16:43
This is a duplicate of #3387

**Closed by mondeja** 2020-11-16 16:43 UTC
Labels: new icon
