### ISSUE TITLE
Request: BYJU'S icon

### ISSUE THREAD

**Issue by ilyasbabu** [simple-icons/simple-icons#6943] opened 2021-12-03 15:44 UTC
### Brand Name

BYJU'S

### Website

https://byjus.com/

### Popularity Metric

The alexa rank is 166.4k. https://www.alexa.com/siteinfo/byjus.com

### Official Resources for Icon and Color

https://cdn1.byjus.com/byjusweb/img/home/svg/byjus_logo.svg
https://s3-cdnwhjr.whjr.online/website/creatorspace/byjus-icon.svg

### Contributing

No

**Comment by service-paradis** [comment] 2021-12-03 21:40
Duplicate of #3954

**Closed by service-paradis** 2021-12-03 21:40 UTC
Labels: new icon
