### ISSUE TITLE
Request: Matplotilib

### ISSUE THREAD

**Issue by mvidaldp** [simple-icons/simple-icons#11010] opened 2024-05-23 11:00 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

The Similarweb rank is 37,553. See https://www.similarweb.com/website/matplotlib.org

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/0/01/Created_with_Matplotlib-logo.svg
color: `#ff8530`

**Comment by uncenter** [comment] 2024-05-23 11:03
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed by uncenter** 2024-05-23 11:03 UTC
Labels: new icon
