### ISSUE TITLE
Update: Twitter to X

### ISSUE THREAD

**Issue by guylepage3** [simple-icons/simple-icons#9164] opened 2023-07-30 17:54 UTC
### Brand Name

x

### Official Resources for Icon and Color

SVG below is from https://twitter.com/home

<svg viewBox="0 0 24 24" aria-hidden="true" class="r-1nao33i r-4qtqp9 r-yyyyoo r-16y2uox r-8kz0gk r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp"><g><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></g></svg>

### Contributing

Yes

**Comment by guylepage3** [comment] 2023-07-30 17:54
<svg viewBox="0 0 24 24" aria-hidden="true" class="r-1nao33i r-4qtqp9 r-yyyyoo r-16y2uox r-8kz0gk r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp"><g><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></g></svg>

**Comment by mondeja** [comment] 2023-07-31 04:34
Duplicate of #9099

**Closed by mondeja** 2023-07-31 04:34 UTC
Labels: icon outdated
