### ISSUE TITLE
Infuse

### ISSUE THREAD

**Issue by Mathmxp** [simple-icons/simple-icons#10339] opened 2024-01-22 08:45 UTC
### Brand Name

Infuse

### Website

https://firecore.com/infuse

### Popularity Metric

Similar web rank: 215,163 see https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=firecore.com

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2024-01-22 14:22
Duplicate of #8419

**Closed by service-paradis** 2024-01-22 14:22 UTC
Labels: new icon, vector unavailable
