### ISSUE TITLE
coolify logo

### ISSUE THREAD

**Issue by ItsTarikBTW** [simple-icons/simple-icons#11308] opened 2024-06-22 14:10 UTC
### Brand Name

coolify 

### Website

https://coolify.io

### Popularity Metric

open source deployment software

### Official Resources for Icon and Color

- SVG: https://coolify.io/coolify-transparent.svg
- Color: #8C52FF

**Comment by uncenter** [comment] 2024-06-22 14:11
Duplicate of #11187. Please search for existing issues before creating a new one.

**Closed by uncenter** 2024-06-22 14:11 UTC
Labels: new icon
