### ISSUE TITLE
add react-native icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3881] opened 2020-11-18 09:47 UTC
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by mondeja** [comment] 2020-11-18 15:24
Hello @hasthamalp. Can you fill the fields? If not, your request will not be considered valid.

**Comment by service-paradis** [comment] 2020-11-19 01:08
Closing as duplicate of #3573

**Closed by service-paradis** 2020-11-19 01:08 UTC
Labels: new icon
