### ISSUE TITLE
Adding of Seaborn

### ISSUE THREAD

**Issue by realshubhamraut** [simple-icons/simple-icons#9549] opened 2023-09-14 02:30 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

## Seaborn
Seaborn is the one of the most popular library used with Python, Its becoming very popular nowadays, Thanks

### Official Resources for Icon and Color

https://seaborn.pydata.org/_images/logo-mark-lightbg.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-09-14 11:56
Duplicate of #6324

**Closed by service-paradis** 2023-09-14 11:56 UTC
Labels: new icon
