### ISSUE TITLE
Ubiquiti Icon Request.

### ISSUE THREAD

**Issue by hjdhjd** [simple-icons/simple-icons#3449] opened 2020-08-14 13:50 UTC
**Name:** Ubiquiti
**Website:** www.ui.com
**Alexa rank:** 3539
  

**Official resources for icon and color:**
  
  https://www.ui.com/marketing/#logos

**Comment by NovaGL** [comment] 2020-08-15 02:54
Duplicate of #3014

**Closed by NovaGL** 2020-08-15 02:54 UTC
Labels: new icon
