### ISSUE TITLE
Request: Google Colaboratory Icon

### ISSUE THREAD

**Issue by kubinka0505** [simple-icons/simple-icons#4138] opened 2020-11-27 20:18 UTC
**Name:** Google Colaboratory
**Website:** https://colab.research.google.com/
**Alexa rank:** 1
  

**Official resources for icon and color:** Ripped directly from the site (`.colab-large-icon`)
Click for the image in the table to get `SVG`.

| Colored | Black & White |
|:-:|:-:|
| <img src="https://cdn.discordapp.com/attachments/267356180064501760/781971950486290432/Google_Colaboratory.svg" width=250> | <img src="https://cdn.discordapp.com/attachments/267356180064501760/781976025331662910/Google_Colaboratory_Black.svg" width=250> |

Colors:
- `--colab-logo-dark` → `--google-orange-600` → `rgb(232, 113, 10)` → `#E8710A`
- `--colab-logo-light` → `--google-yellow-600` → `rgb(249, 171, 0)` → `#F9AB00`

**Comment by fbernhart** [comment] 2020-11-27 23:06
Duplicate of #3313

**Closed** 2020-11-28 00:28 UTC
Labels: duplicate, new icon

**Comment by fbernhart** [comment] 2020-11-28 00:44
@service-paradis There is another duplicate here: #3655

**Comment by service-paradis** [comment] 2020-11-28 17:50
> @service-paradis There is another duplicate here: #3655

Thank you @fbernhart  :)
