### ISSUE TITLE
Icon Request: URI

### ISSUE THREAD

**Issue by novojitdas** [simple-icons/simple-icons#6313] opened 2021-08-16 10:03 UTC
Organization Name: URI
Website: https://www.urionlinejudge.com.br/
Alexa rank: 108,039

Official resources for icon and color:

https://www.urionlinejudge.com.br/judge/img/5.0/logo.130615.png?1591503281

**Comment by PeterShaggyNoble** [comment] 2021-08-16 11:45
Duplicate of #3423

**Closed by PeterShaggyNoble** 2021-08-16 11:45 UTC
Labels: new icon
