### ISSUE TITLE
Filamentphp icon

### ISSUE THREAD

**Issue by RawanD201** [simple-icons/simple-icons#11849] opened 2024-09-25 17:12 UTC
### Brand Name

Filamantphp

### Website

https://filamentphp.com/

### Popularity Metric

![Screenshot from 2024-09-25 20-11-22](https://github.com/user-attachments/assets/15d0cbb4-46a5-407d-b318-47fd78c1e2a1)
![Screenshot from 2024-09-25 20-08-33](https://github.com/user-attachments/assets/85de04d2-d3c0-486d-a200-438bed5e8ee4)

### Official Resources for Icon and Color

![Screenshot from 2024-09-25 20-12-32](https://github.com/user-attachments/assets/d4ddb3b2-be18-42e6-a8b3-41a865c17cd8)

**Comment by uncenter** [comment] 2024-09-25 17:16
Duplicate of #10344. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-09-25 17:16 UTC
Labels: new icon
