### ISSUE TITLE
Davinchi Resolve

### ISSUE THREAD

**Issue by sionkimsion** [simple-icons/simple-icons#8617] opened 2023-05-07 12:29 UTC
### Brand Name

Davinci Resolve

### Website

https://www.blackmagicdesign.com/products/davinciresolve

### Popularity Metric

960,532

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/DaVinci_Resolve_17_logo.svg/2048px-DaVinci_Resolve_17_logo.svg.png

color : #000000

### Additional Comments

Can i use transparent color for simple-icons or shields.io?

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-11 12:52
Duplicate of #6062

**Closed by service-paradis** 2023-05-11 12:52 UTC
Labels: new icon
