### ISSUE TITLE
skoda

### ISSUE THREAD

**Issue by support27** [simple-icons/simple-icons#3178] opened 2020-06-05 10:46 UTC
**Name:roger**
**Website:support27**
**Official resources for icon and color:**
  

https://www.skoda-auto.com/

**Comment by PeterShaggyNoble** [comment] 2020-06-05 11:19
Duplicate of #2059

This one is already available:

![ŠKODA](https://user-images.githubusercontent.com/15157491/83870765-b5dd5a80-a726-11ea-9ece-f82f80dc798e.png)

**Closed by PeterShaggyNoble** 2020-06-05 11:19 UTC
Labels: new icon

**Comment by support27** [comment] 2020-06-05 16:45
just a thought... perhaps rename ŠKODA to skoda. searching for skoda 
gives no results and without knowing the special character code would 
never appear... or add a second search variable with just skoda.

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------

**Comment by PeterShaggyNoble** [comment] 2020-06-05 16:47
That will be addressed in #3180, @support27.

**Comment by support27** [comment] 2020-06-05 16:50
awesome!

Best Regards,



Roger @ support27



www.support27.com

info@support27.com

+1 (800) 674-9364


------ Original Message ------
