### ISSUE TITLE
TypeORM icon request plz..

### ISSUE THREAD

**Issue by hakseon-yoo** [simple-icons/simple-icons#8411] opened 2023-03-10 03:54 UTC
### Brand Name

TypeORM

### Website

https://typeorm.io/

### Popularity Metric

https://typeorm.io/

### Official Resources for Icon and Color

sorry.. i dont know..

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-03-10 15:52
Duplicate of #8147

**Closed** 2023-03-10 15:53 UTC
Labels: new icon, duplicate
