### ISSUE TITLE
Add SpigotMC icon

### ISSUE THREAD

**Issue by Picono435** [simple-icons/simple-icons#9299] opened 2023-08-16 15:10 UTC
### Brand Name

SpigotMC

### Website

https://www.spigotmc.org

### Popularity Metric

The Similarweb rank is 16,149. See here https://www.similarweb.com/website/spigotmc.org.

### Official Resources for Icon and Color

png: https://static.spigotmc.org/img/spigot.png
color: #ed8106

### Contributing

No

**Comment by service-paradis** [comment] 2023-08-16 17:29
Duplicate of #6704

**Closed by service-paradis** 2023-08-16 17:29 UTC
Labels: new icon
