### ISSUE TITLE
Request: Disney+ icon

### ISSUE THREAD

**Issue by tretabyte** [simple-icons/simple-icons#7570] opened 2022-07-06 09:31 UTC
### Brand Name

Disney+

### Website

https://www.disneyplus.com

### Popularity Metric

The Similarweb rank is 99 https://www.similarweb.com/website/disneyplus.com/

### Official Resources for Icon and Color

https://www.deviantart.com/kiofficialart/art/Disney-app-design-by-KIOfficialArt-795076763

### Contributing

No

**Comment by service-paradis** [comment] 2022-07-06 13:57
Duplicate of #2309, #3493, #3693, #5327, #5443, #6352 and #7430.

Disney are super strict about their brands, and as such we will not be adding them to this project.

**Closed** 2022-07-06 13:57 UTC
Labels: new icon, won't add, duplicate
