### ISSUE TITLE
Request n8n icon

### ISSUE THREAD

**Issue by macrochel** [simple-icons/simple-icons#9136] opened 2023-07-28 16:12 UTC
### Brand Name

n8n

### Website

n8n.io

### Popularity Metric

The Similarweb web rank is 677 

### Official Resources for Icon and Color

svg: http://www.w3.org/2000/svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-07-28 18:33
Duplicate of #7993

**Closed by service-paradis** 2023-07-28 18:33 UTC
Labels: new icon
