### ISSUE TITLE
Request: tcs

### ISSUE THREAD

**Issue by bhupeshmahara** [simple-icons/simple-icons#6932] opened 2021-12-02 06:09 UTC
### Brand Name

Tata Consultancy Services

### Website

https://www.tcs.com

### Popularity Metric

Tata Consultancy Services aka TCS is the largest MNC in India.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment] 2023-12-06 09:49
Duplicate of #5323

**Closed by PeterShaggyNoble** 2023-12-06 09:49 UTC
Labels: new icon
