### ISSUE TITLE
Requesting icon for Appium

### ISSUE THREAD

**Issue by mikesalvia** [simple-icons/simple-icons#8594] opened 2023-05-01 18:00 UTC
### Brand Name

Appium

### Website

http://appium.io/docs/en/2.0/

### Popularity Metric

The Similarweb rank is 324,995.

![Screen Shot 2023-05-01 at 1 53 14 PM](https://user-images.githubusercontent.com/6209204/235500957-f7e5ff84-6113-459d-ba0e-e2d15f631929.png)

### Official Resources for Icon and Color

svg: ![Appium](https://user-images.githubusercontent.com/6209204/235501703-5d0b1cf7-f4a2-4f4a-b930-c568d03ef267.svg)
png: 
![appium-logo-7A2DD5B4E3-seeklogo com](https://user-images.githubusercontent.com/6209204/235501973-93f330ca-47e8-44ff-ba76-471825280a60.png)
png: 
![appium-logo-white](https://user-images.githubusercontent.com/6209204/235502245-dac85913-2d31-4af4-9390-421b321cac9e.png)

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-01 19:31
Duplicate of #3385

**Closed by service-paradis** 2023-05-01 19:31 UTC
Labels: new icon, duplicate
