### ISSUE TITLE
Missing WhatsApp Business icon

### ISSUE THREAD

**Issue by bhaveshxrawat** [simple-icons/simple-icons#8024] opened 2022-11-09 16:10 UTC
### Brand Name

WhatsApp Business

### Website

https://business.whatsapp.com/

### Popularity Metric

The Similarweb rank is 142. See https://www.similarweb.com/app/google-play/com.whatsapp.w4b/statistics/

### Official Resources for Icon and Color

Icon: https://play-lh.googleusercontent.com/ebs6ftYUkOKlDY0M174OpvargwbDyHUVAnO_G5aE0dL5GBQKCtfh3adN5H3ZMThXogDi=w480-h960

### Additional Comments

The official website of WhatsApp Business doesn't show the actual logo, for the actual logo, please refer to https://play.google.com/store/apps/details?id=com.whatsapp.w4b

### Contributing

Yes

**Comment by LitoMore** [comment] 2022-11-13 09:32
We need vector resources to process. It would be good if we could find a vector one somewhere.

**Comment by umairkhalid-devsinc** [comment] 2022-11-16 08:49
@LitoMore I have created PR for Whatsapp Business Icon. please reveiw and let me know in case on any query

**Comment by adamrusted** [comment] 2023-07-30 04:02
Duplicate of #3956

**Closed by adamrusted** 2023-07-30 04:02 UTC
Labels: new icon
