### ISSUE TITLE
Add a Mongoose icon

### ISSUE THREAD

**Issue by Gusarovv** [simple-icons/simple-icons#8314] opened 2023-02-05 17:20 UTC
### Brand Name

Mongoose

### Website

https://mongoosejs.com

### Popularity Metric

Rank is **94,017**. See www.similarweb.com/website/mongoosejs.com

### Official Resources for Icon and Color

png: https://www.pngfind.com/mpng/immihmi_mongoose-js-logo-hd-png-download/
color: `#a03333`, from the website header

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-02-06 15:09
Duplicate of #5594

**Closed by service-paradis** 2023-02-06 15:09 UTC
Labels: new icon
