### ISSUE TITLE
Request: PrimeNG

### ISSUE THREAD

**Issue by mukundkumra** [simple-icons/simple-icons#10951] opened 2024-05-14 09:35 UTC
### Brand Name

PrimeNG

### Website

https://primeng.org/

### Popularity Metric

The similar web rank is 81,307. See https://www.similarweb.com/website/primeng.org/
It has ~9.5k stars on Github. See https://github.com/primefaces/primeng

### Official Resources for Icon and Color

svg: https://github.com/primefaces/primeicons/blob/master/raw-svg/prime.svg

**Comment by mukundkumra** [comment] 2024-05-14 09:39
SVG Source: https://github.com/primefaces/primeicons/blob/master/raw-svg/prime.svg

**Comment by service-paradis** [comment] 2024-05-14 17:57
Duplicate of https://github.com/simple-icons/simple-icons/issues/5603

**Closed by service-paradis** 2024-05-14 17:57 UTC
Labels: new icon
