### ISSUE TITLE
Request: Hardhat

### ISSUE THREAD

**Issue by siddhantshahH1** [simple-icons/simple-icons#7505] opened 2022-06-14 21:10 UTC
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

According to Similarweb rank-  
Global Rank: 208,740
Country Rank: 246,476
Category Rank: 2342

### Official Resources for Icon and Color

https://pbs.twimg.com/profile_images/1317925773425168384/XQkaoFRg_400x400.jpg

### Contributing

Yes

**Comment by sisp** [comment] 2022-06-15 11:34
I took the liberty of fixing the Similarweb rank numbers formatting in the OP. :wink:

**Comment by sisp** [comment] 2022-06-15 11:36
There is an [official SVG icon](https://github.com/NomicFoundation/hardhat/blob/5e5af74e9a48a2e2a392b6824f90877cd8f26fb5/docs/src/assets/hardhat-logo.svg) which can be used instead of the JPEG image linked above.

**Comment by sachinraja** [comment] 2022-06-15 14:03
Duplicate of #7026

**Closed by sachinraja** 2022-06-15 14:03 UTC
Labels: new icon
