### ISSUE TITLE
Request Express js Icon

### ISSUE THREAD

**Issue by Joylish** [simple-icons/simple-icons#4354] opened 2020-12-14 09:46 UTC
**Name:** express js
**Website:** expressjs.com
**Alexa rank:** https://www.alexa.com/siteinfo/expressjs.com
  
![image](https://user-images.githubusercontent.com/52230415/102065933-84172000-3e3c-11eb-8c0f-c9c2d351c35a.png)

**Official resources for icon and color:**
  
  
![image](https://user-images.githubusercontent.com/52230415/102066021-a3ae4880-3e3c-11eb-96c1-3f8f28d6d785.png)

**Comment by mondeja** [comment] 2020-12-14 11:24
Duplicate of #2924

**Closed by mondeja** 2020-12-14 11:24 UTC
Labels: new icon
