### ISSUE TITLE
ExpressJS | Dialogflow Icon

### ISSUE THREAD

**Issue by Abduttayyeb** [simple-icons/simple-icons#4342] opened 2020-12-13 18:51 UTC
**Name: DialogFlow**
**Website: dialogflow.cloud.google.com**
**Alexa rank: 121,064**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment] 2020-12-13 19:02
Duplicate of #3444

**Closed by service-paradis** 2020-12-13 19:02 UTC
Labels: new icon
