### ISSUE TITLE
Request: Icon request for Matplotlib

### ISSUE THREAD

**Issue by kimbank** [simple-icons/simple-icons#6861] opened 2021-11-15 11:18 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

The Alexa rank is 12,034. See [https://www.alexa.com/siteinfo/matplotlib.org](https://www.alexa.com/siteinfo/matplotlib.org)

The number of GitHub stars is 14,535. See [https://github.com/matplotlib/matplotlib](https://github.com/matplotlib/matplotlib)

### Official Resources for Icon and Color

svg: https://matplotlib.org/_static/logo2.svg
color: *None*

### Contributing

Yes

**Comment by service-paradis** [comment] 2021-11-15 13:55
Duplicate of #6847, #6556, #6421, #5606, #5321 and #3410

**Closed by service-paradis** 2021-11-15 13:55 UTC
Labels: new icon, duplicate
