### ISSUE TITLE
Request: Polygon Blockchain

### ISSUE THREAD

**Issue by lucaslokchan** [simple-icons/simple-icons#7572] opened 2022-07-08 02:51 UTC
### Brand Name

Polygon

### Website

https://polygon.technology/

### Popularity Metric

Rank: 39,672
link: https://www.similarweb.com/website/polygon.technology

### Official Resources for Icon and Color

svg: https://polygon.technology/_nuxt/img/polygon-logo.99647ca.svg
color: #733fe4

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-07-13 17:40
Duplicate of #6918

**Closed by service-paradis** 2022-07-13 17:40 UTC
Labels: new icon
