### ISSUE TITLE
Request: Paytm Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#4285] opened 2020-12-07 15:04 UTC
**Name:** Paytm
**Website:** https://paytm.com/
**Alexa rank:** 1,356
  

**Official resources for icon and color:** https://paytm.com/

**Comment by service-paradis** [comment] 2020-12-07 15:35
Duplicate of #3788

**Closed by service-paradis** 2020-12-07 15:35 UTC
Labels: new icon

**Comment by PeterShaggyNoble** [comment] 2021-01-07 16:33
Added in #4643
