### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by EthanRCT** [simple-icons/simple-icons#8264] opened 2023-01-16 19:26 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

Global Rank: 32,045
https://www.similarweb.com/website/matplotlib.org/#overview

Not sure exactly how to find GitHub stars
https://github.com/topics/matplotlib?o=desc&s=stars

### Official Resources for Icon and Color

https://matplotlib.org/stable/gallery/misc/logos2.html

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-01-16 20:23
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed by service-paradis** 2023-01-16 20:23 UTC
Labels: new icon, duplicate
