### ISSUE TITLE
Fusion360

### ISSUE THREAD

**Issue by HasanTheSyrian** [simple-icons/simple-icons#8279] opened 2023-01-23 12:17 UTC
### Brand Name

Autodesk Fusion360

### Website

https://www.autodesk.com/products/fusion-360/overview?term=1-YEAR&tab=subscription

### Popularity Metric

Global rank is #2100

https://www.similarweb.com/website/autodesk.com/#overview

### Official Resources for Icon and Color

https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/lockup-610x66/dark-theme/fusion-360-lockup-white-673x74.png

### Contributing

Yes

**Comment by ripzerotwo** [comment] 2023-02-02 00:16
Do you want an Autodesk logo or fusion360 logo to be added?

**Comment by HasanTheSyrian** [comment] 2023-02-02 07:32
fusion360

**Comment by PeterShaggyNoble** [comment] 2023-12-05 21:20
Duplicate of #6054

**Closed by PeterShaggyNoble** 2023-12-05 21:20 UTC
Labels: new icon
