### ISSUE TITLE
Request: Wakatime icon

### ISSUE THREAD

**Issue by guibranco** [simple-icons/simple-icons#3481] opened 2020-08-21 20:56 UTC
**Name:** Wakatime
**Website:** https://wakatime.com
**Alexa rank:** 36,610
  

**Official resources for icon and color:**  https://wakatime.com/legal/logos-and-trademark-usage

**Comment by guibranco** [comment] 2020-08-23 20:05
@NovaGL pull request created!

**Comment by adamrusted** [comment] 2021-01-02 17:42
This is a duplicate of #2962, which was closed by #2975. Going to close this issue.

**Closed by adamrusted** 2021-01-02 17:42 UTC
Labels: good first issue, new icon
