### ISSUE TITLE
TouchDesigner

### ISSUE THREAD

**Issue by gwangyu-lee** [simple-icons/simple-icons#12287] opened 2024-12-05 03:41 UTC
### Brand Name

TouchDesigner

### Website

https://derivative.ca/

### Popularity Metric

Derivative.ca is ranked in 144,802. See https://similarweb.com/website/derivative.ca

### Official Resources for Icon and Color

SVG: https://brandfetch.com/derivative.ca

**Comment by uncenter** [comment] 2024-12-05 03:43
Duplicate of #9632. Please search for existing issues before opening new ones.

**Closed by uncenter** 2024-12-05 03:43 UTC
Labels: new icon
