### ISSUE TITLE
Authentik idp

### ISSUE THREAD

**Issue by ankycooper** [simple-icons/simple-icons#10760] opened 2024-04-03 04:58 UTC
### Brand Name

Authentik 

### Website

goauthentik.io

### Popularity Metric

851,571 https://www.similarweb.com/website/goauthentik.io/#overview

### Official Resources for Icon and Color

svg: https://github.com/goauthentik/authentik/tree/main/web/icons

### Additional Comments

Multiple logs and icons

**Comment by uncenter** [comment] 2024-04-04 11:01
Duplicate of #10345.

**Closed by uncenter** 2024-04-04 11:01 UTC
Labels: new icon
