### ISSUE TITLE
Add AutoHotkey

### ISSUE THREAD

**Issue by bBSempai** [simple-icons/simple-icons#3855] opened 2020-11-12 17:39 UTC
**Name:** AutoHotkey (AHK)
**Website:** https://www.autohotkey.com/
**Alexa rank:** #23007
  

**Official resources for icon and color:**
  

![AHK](https://user-images.githubusercontent.com/64588227/98975263-e6c68480-253b-11eb-9750-22dfeebf4321.png)
![scite4](https://user-images.githubusercontent.com/64588227/98975388-0c538e00-253c-11eb-9e73-cca16e51766a.png)

**Comment by service-paradis** [comment] 2020-11-12 19:27
Looks like to me the logo is 
![image](https://user-images.githubusercontent.com/12817388/98986600-2157ff00-24f3-11eb-972a-16d8fce1323f.png)

**Comment by bBSempai** [comment] 2020-11-13 13:29
Oh yeah sorry for that! 
But it feels too wide as a logo to use it somewhere

Anyways, any chance it can be added to the website?

**Comment by PeterShaggyNoble** [comment] 2021-01-07 10:54
I agree with @service-paradis that we should use the "AHK" or, if we can get away with it, just the "A" as they do in their favicon. Might be tricky to monochromise, though, while maintaining the integrity of the logo.

**Comment by bBSempai** [comment] 2021-01-16 17:56
![autohotkey](https://user-images.githubusercontent.com/64588227/104819198-fa4ede00-5851-11eb-82d0-660e63ce7bf1.png)
Would this work? @PeterShaggyNoble @service-paradis 
Made it from this:
![AutoHotKey-1](https://user-images.githubusercontent.com/64588227/104819219-13f02580-5852-11eb-8365-24f75f6dc1e1.png)
Thanks

**Comment by PeterShaggyNoble** [comment] 2021-01-18 10:04
That works for me, @bBSempai. Although, to maintain the original intent of it being a key, I think the "A" should be knocked out of the square. Assuming the other @simple-icons/maintainers agree with that treatment, would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and open a PR for this? For the colour, I'd suggest `#334455`, which is the most prominent one on their siet.

**Comment by bBSempai** [comment] 2021-01-20 18:20
Yes, i'd love to! Although I didn't quite get you at the "the 'A' should be knocked out of the square" part. How must the icon look like?

**Comment by PeterShaggyNoble** [comment] 2021-01-21 09:52
Something like this, @bBSempai:

![](https://user-images.githubusercontent.com/15157491/105334043-54db9780-5bce-11eb-834a-109978e44836.png)

**Comment by adamrusted** [comment] 2021-01-21 11:32
Given the treatment on their [Facebook page](https://www.facebook.com/AutoHotkey/photos/a.455934534445306/998365490202205/), could we look at something like the below?

![image](https://user-images.githubusercontent.com/1830867/105345526-47c5a500-5bdc-11eb-8e17-7b4fe984c064.png)

**Comment by fbernhart** [comment] 2021-01-21 13:21
Here would be my suggestion based on the [SVG](https://www.autohotkey.com/static/ahk_logo_no_text.svg) in their [website](https://www.autohotkey.com/) header. It still resembles keys in my opinion:

![image](https://user-images.githubusercontent.com/70264417/105356179-5ec3c180-5bf3-11eb-88d4-3607936c2d4a.png)

**Comment by bBSempai** [comment] 2021-01-21 15:31
The whole of AHK should be the most authentic icon although it is pretty long and short and might just not be efficient for 24x24. On the other hand the A has been used as their favicon on their [website](https://www.autohotkey.com/) and is also better as an icon.

**Comment by fbernhart** [comment] 2021-01-21 16:56
Let's pin @Lexikos, the owner and one of the maintainers of the [official AutoHotkey repo](https://github.com/Lexikos/AutoHotkey_L). 

Is there any official monochrome version of the AutoHotkey logo? And if not, which of the above would be the preferred monochrome treatment?

**Comment by bBSempai** [comment] 2021-01-25 11:40
He hasn't been active since August ;_(

**Comment by PeterShaggyNoble** [comment] 2021-01-27 16:51
Dang! The next step may be to create an issue/discussion in their repo asking for clarification.

**Comment by bBSempai** [comment] 2021-01-28 17:07
![image](https://user-images.githubusercontent.com/64588227/106172874-4e928000-61b9-11eb-9ca2-ea24e846652b.png)
WHERE IS THE ISSUE TAB IM WEAK

**Comment by PeterShaggyNoble** [comment] 2021-01-28 17:20
Looks like they're disabled 🙁 Guess we'll have to go with our own best interpretation, so.

**Comment by Lexikos** [comment] 2021-01-31 02:19
There is no official monochrome logo, as far as I am aware. I suppose "official" is whatever is on the website (which I leave to others to maintain), or embedded in the program and documentation.

The first graphic in the first comment appears to be an unofficial reproduction of the program icon. The "H" in the icon is not part of any font, but was drawn with two vertical lines (with rounded caps) and a slightly diagonal one. I did it that way because none of the fonts I tried matched the 16-colour icon originally used in AutoHotkey.exe.

The second graphic is for a different (related) project, SciTE4AutoHotkey.

The use of "H" in the icon far predates the favicon on the website, and I think would look more familiar than "A". The main program icon uses "H", and the tray icon uses "H" most of the time, changing to "S" when hotkeys are suspended.

>  Guess we'll have to go with our own best interpretation, so.

Sounds fine to me.

**Comment by fbernhart** [comment] 2021-01-31 06:53
Thanks for your feedback @Lexikos!

In this case I would suggest another version. Based on the version of  @adamrusted with the "AHK" letters on one key, I would give it the same style as my suggestion. So that the outer part of the key and the letters "AHK" are paths.

I don't have a PC available right now to give it a try. But maybe @adamrusted could give it a try. 😊

**Comment by adamrusted** [comment] 2021-02-01 21:20
@fbernhart sorry - I've missed this comment. Will give it a look tomorrow morning - hopefully we can get this one merged!

**Comment by adamrusted** [comment] 2021-02-02 21:07
How's this look @fbernhart @Lexikos?

![autohotkey](https://user-images.githubusercontent.com/1830867/106662754-b0c4f980-659a-11eb-9727-dd3f380d8ab0.png)

**Comment by fbernhart** [comment] 2021-02-02 21:14
Looks great to me! 😊 What do you think @PeterShaggyNoble ?

**Comment by bBSempai** [comment] 2021-02-02 21:21
Well I did what @PeterShaggyNoble asked including the hex:

![autohotkey](https://user-images.githubusercontent.com/64588227/106663712-1bd9f480-65ca-11eb-9550-fb9e2949041d.png)

Was going to put up a PR and upload this here and noticed @adamrusted put it here already😅

**Comment by adamrusted** [comment] 2021-02-02 21:25
> Was going to put up a PR and upload this here and noticed @adamrusted put it here already😅

I've not put a PR together - happy for you to do it. I'll edit my original post to include the path, should that be chosen as the preferred one 👍🏻

**Comment by bBSempai** [comment] 2021-02-02 21:43
Sure! I did it. Also edited my post and included the path.
Thankyou!

**Closed** 2021-02-24 11:56 UTC
Labels: new icon
