### ISSUE TITLE
Icon Request: Docusaurus icon

### ISSUE THREAD

**Issue by grand-rick001** [simple-icons/simple-icons#8417] opened 2023-03-13 09:34 UTC
### Brand Name

Docusaurus

### Website

https://docusaurus.io/

### Popularity Metric

- The Similar Web rank is 197,874. See https://www.similarweb.com/website/docusaurus.io/
- The number of GitHub stars is 42.8k. See https://github.com/facebook/docusaurus

### Official Resources for Icon and Color

svg: https://github.com/facebook/docusaurus/blob/main/website/static/img/docusaurus.svg
color: `#25c19f`

### Contributing

Yes

**Comment by grand-rick001** [comment] 2023-03-13 09:36
Please assign me this issue.

**Comment by LitoMore** [comment] 2023-05-22 05:58
@grand-rick001 We never use `Assignees` for managing tasks.

You can always open a pull request.

**Comment by PeterShaggyNoble** [comment] 2023-12-05 18:56
Duplicate of #5212

**Closed by PeterShaggyNoble** 2023-12-05 18:56 UTC
Labels: new icon
