### ISSUE TITLE
Sanity

### ISSUE THREAD

**Issue by Sushant5776** [simple-icons/simple-icons#7956] opened 2022-10-14 10:36 UTC
### Brand Name

Sanity

### Website

https://sanity.io

### Popularity Metric

It is one of the popular CMS (Content Management System) used across the web. Many great projects include it!

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by service-paradis** [comment] 2022-10-14 16:05
Duplicate of #6443

**Closed by service-paradis** 2022-10-14 16:05 UTC
Labels: new icon
