### ISSUE TITLE
ejs

### ISSUE THREAD

**Issue by developomp** [simple-icons/simple-icons#7031] opened 2022-01-07 05:07 UTC
### Brand Name

ejs

### Website

https://ejs.co

### Popularity Metric

alexa rank: https://www.alexa.com/siteinfo/ejs.co
github (6k): https://github.com/mde/ejs

### Official Resources for Icon and Color

svg: https://ejs.co/favicon.svg

### Contributing

No

**Comment by sachinraja** [comment] 2022-01-19 03:47
duplicate of #6132

**Closed by sachinraja** 2022-01-19 03:47 UTC
Labels: new icon
