### ISSUE TITLE
Request for adding icon for haproxy.

### ISSUE THREAD

**Issue by ShikharY10** [simple-icons/simple-icons#8348] opened 2023-02-14 19:09 UTC
### Brand Name

Haproxy

### Website

https://www.haproxy.org/

### Popularity Metric

HAproxy's Global Ranking on SimilarWeb is 247,177. [See here](https://www.similarweb.com/website/haproxy.com/#overview)

### Official Resources for Icon and Color

![haproxy-icon](https://user-images.githubusercontent.com/65106263/218832894-195a8101-5210-4d0a-aa9c-e34d1fb34931.svg)

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-02-14 19:55
Duplicate of #8339

**Closed by service-paradis** 2023-02-14 19:55 UTC
Labels: new icon
