### ISSUE TITLE
Requesting for the Addition of a icon

### ISSUE THREAD

**Issue by k-arthik-r** [simple-icons/simple-icons#9693] opened 2023-10-07 07:14 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

No time

### Official Resources for Icon and Color

No time

### Additional Comments

No time

**Comment by adamrusted** [comment] 2023-10-07 07:18
Duplicate of #3410.

**Closed** 2023-10-07 07:18 UTC
Labels: new icon
