### ISSUE TITLE
Materialize

### ISSUE THREAD

**Issue by matipretz** [simple-icons/simple-icons#9602] opened 2023-09-20 23:38 UTC
### Brand Name

Materialize

### Website

https://materializecss.com/

### Popularity Metric

The Similarweb rank is 278,035. See https://www.similarweb.com/website/materializecss.com/#overview

### Official Resources for Icon and Color

svg: https://materializecss.com/res/materialize.svg
![materialize](https://github.com/simple-icons/simple-icons/assets/30426732/b8515ef8-d13e-4132-8f80-00d45d9661bd)

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-09-21 02:51
Duplicate of #3203.

**Closed** 2023-09-21 02:51 UTC
Labels: new icon
