### ISSUE TITLE
Request to add Hardhat(Popular Ethereum Developement tool) Icon.

### ISSUE THREAD

**Issue by SaikrishnaReddy1919** [simple-icons/simple-icons#8008] opened 2022-11-01 12:28 UTC
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

- The similar web rank is : 216,628, see [webrank-hardhat](https://www.similarweb.com/website/hardhat.org/#overview)
- It has almost 5k stars (4.6k) on github. Check [here](https://github.com/NomicFoundation/hardhat)
- And this tool has created by Nomic Labs which is becoming the Nomic Foundation, a non-profit organization dedicated to Ethereum’s developer platform, on a mission to empower developers to decentralize the world. Check [this](https://medium.com/nomic-foundation-blog/introducing-the-nomic-foundation-an-ethereum-public-goods-organization-31012af67df9) to know more about Nomic Labs.

### Official Resources for Icon and Color

I just found this : 
https://github.com/NomicFoundation/hardhat/blob/main/docs/public/buidler-plugin-badge.svg.

### Additional Comments

- It should be considered because it's the top and one most of the most used tool to develop, test and deploy smart contracts among all web3 developers around the globe 💯 .

- Check the statistics of the **hardhat** package [here](https://snyk.io/advisor/npm-package/hardhat)

### Contributing

No

**Comment by service-paradis** [comment] 2022-11-02 13:41
Duplicate of #7026

**Closed by service-paradis** 2022-11-02 13:41 UTC
Labels: new icon
