### ISSUE TITLE
Icon request for HuggingFace

### ISSUE THREAD

**Issue by TheProjectsGuy** [simple-icons/simple-icons#9256] opened 2023-08-11 05:59 UTC
### Brand Name

HuggingFace

### Website

https://huggingface.co/

### Popularity Metric

The [SimilarWeb rank](https://www.similarweb.com/website/huggingface.co/#overview) is 2,302.
The website is becoming increasingly useful for showcasing scientific advancements through HuggingFace spaces and also maintaining core libraries like HuggingFace transformers and diffusers (for the ML community).

Bio from [website](https://huggingface.co/brand)
> Hugging Face is the collaboration platform for the machine learning community.

> The Hugging Face Hub works as a central place where anyone can share, explore, discover, and experiment with open-source ML. HF empowers the next generation of machine learning engineers, scientists, and end users to learn, collaborate and share their work to build an open and ethical AI future together.

> With the fast-growing community, some of the most used open-source ML libraries and tools, and a talented science team exploring the edge of tech, Hugging Face is at the heart of the AI revolution.

### Official Resources for Icon and Color

All assets can be downloaded from [HuggingFace](https://huggingface.co/brand)

- SVG Logo: https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.svg
- PNG: https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.png
- Color: #FFD21E (for face)

### Additional Comments

There are two variants of this icon (as seen on the [brand page](https://huggingface.co/brand)). I request the smaller, square icon (with only the face).

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-08-11 17:10
Duplicate of #6074

**Closed by service-paradis** 2023-08-11 17:10 UTC
Labels: new icon, duplicate
