### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11089] opened 2024-06-02 06:53 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics. Its [parent website](https://pydata.org/) has a Similarweb ranking of 23,305. Its [GitHub repo](https://github.com/mwaskom/seaborn) has got 12k stars and star history is on a consistently upward trajectory.

### Official Resources for Icon and Color

svg: https://seaborn.pydata.org/_static/logo-wide-lightbg.svg

### Additional Comments

It is one of the pre-installed data visualization libraries along with Matplotlib in Google Colab

**Comment by anhthang** [comment] 2024-06-02 07:38
duplicates #6324

**Comment by ancilcleetus** [comment] 2024-06-02 12:05
@anhthang [#6324](https://github.com/simple-icons/simple-icons/issues/6324) is an open issue for almost 3 years. Many people have requested for that icon in past 3 years and everyone is getting the same reply "duplicate of #6324".

Then, why Seaborn icon is not added ? What is the reason ? It is a very popular Python library and used as one of the go to libraries for creating visually pleasing plots. Python developers, Data Scientists and Machine Learning Engineers use Matplotlib and Seaborn on a daily basis. If you are going to close my request, at least add that icon and close [#6324](https://github.com/simple-icons/simple-icons/issues/6324) also.

**Comment by uncenter** [comment] 2024-06-02 12:49
> @anhthang [#6324](https://github.com/simple-icons/simple-icons/issues/6324) is an open issue for almost 3 years. Many people have requested for that icon in past 3 years and everyone is getting the same reply "duplicate of #6324".
> 
> Then, why Seaborn icon is not added ? What is the reason ? It is a very popular Python library and used as one of the go to libraries for creating visually pleasing plots. Python developers, Data Scientists and Machine Learning Engineers use Matplotlib and Seaborn on a daily basis. If you are going to close my request, at least add that icon and close [#6324](https://github.com/simple-icons/simple-icons/issues/6324) also.

Please don't speak in that disrespectful tone. If you want the icon added, feel free to read through our [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) add raise a PR to add the icon.

**Comment by uncenter** [comment] 2024-06-02 12:49
Duplicate of https://github.com/simple-icons/simple-icons/issues/6324.

**Closed by uncenter** 2024-06-02 12:49 UTC
Labels: new icon

**Comment by ancilcleetus** [comment] 2024-06-02 15:08
@uncenter I didn't mean to be disrespectful. I just want to know the reason for not adding it for 3 years. I checked all the past raised issues, but I couldn't find a reason. Only reason mentioned is "Duplicate of #6324". If you can enlighten me, it will be helpful. I'm ready to contribute to create this icon, but I just want to know whether the issue is because of some technical problems related to svg logo file.

**Comment by uncenter** [comment] 2024-06-02 15:12
There is no specific reason against it if you read through the comments on the issue. The only blocker is that it isn't the easiest logo to add as it doesn't really work as a monochrome icon.

**Comment by ancilcleetus** [comment] 2024-06-02 15:17
@uncenter Ok. Got it. Thanks for the info. In fact, matplotlib logo also has this problem, I guess.
