### ISSUE TITLE
MediaWiki

### ISSUE THREAD

**Issue by pisceskaze** [simple-icons/simple-icons#9041] opened 2023-07-18 08:51 UTC
### Brand Name

MediaWiki

### Website

https://mediawiki.org

### Popularity Metric

https://www.similarweb.com/website/mediawiki.org - `#37,518 @ 15:45 07/18/2023 (GMT+7)`
https://github.com/wikimedia/mediawiki - `3.5K Stars @ the same date and time`

#### Original MediaWiki logo since 2020:
- [Original size](https://upload.wikimedia.org/wikipedia/commons/a/a6/MediaWiki-2020-icon.svg)
  - Has 24 petals and should be used for logos ranging from 25px to 100px, according to the [guideline](https://www.mediawiki.org/wiki/Manual:MediaWiki_logo_guidelines#Icon_sizes).
- [Large](https://upload.wikimedia.org/wikipedia/commons/8/8c/MediaWiki-2020-large-icon.svg)
  - Has 30 petals and should be used for logo sizes larger than 100px, according to the [guideline](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:MediaWiki_logo_guidelines#Icon_sizes).
- [Small](https://upload.wikimedia.org/wikipedia/commons/c/c6/MediaWiki-2020-small-icon.svg)
  - Has 16 petals and should be used in ultra-small logos (less than 25px in size), according to the [guideline](https://www.mediawiki.org/wiki/Special:MyLanguage/Manual:MediaWiki_logo_guidelines#Icon_sizes).

The colors used for the gradient are `#9b59a4`, `#ff6758`, and `#ffbe57`.

#### Color variants version
- White: [Here](https://upload.wikimedia.org/wikipedia/commons/c/ca/MediaWiki-2020-icon-%28white%29.svg) - `#ffffff`
- Black: [Here](https://upload.wikimedia.org/wikipedia/commons/3/3f/MediaWiki-2020-icon-%28black%29.svg) - `#000000`

### Additional Comments

Release with [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0) license. Created by [Serhio Magpie](https://commons.wikimedia.org/wiki/User:Serhio_Magpie).

There are a total of 3 different sizes versions of this logo alone, each for different usages, which are also released with the same license type.

This is a well-known software for making professional websites in wiki format created by Wikimedia Foundation. And also, I have to mention that there are [2 other requests](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+is%3Aopen+MediaWiki) than mine, and still no process since there.

### Contributing

Yes

**Comment by pisceskaze** [comment] 2023-07-19 11:50
Damn, my first pull ever.

**Comment by service-paradis** [comment] 2023-07-21 14:35
Duplicate of #5805

**Closed** 2023-07-21 17:05 UTC
Labels: new icon, duplicate
