### ISSUE TITLE
Add Matlab Icon

### ISSUE THREAD

**Issue by lnpsiqueira** [simple-icons/simple-icons#7355] opened 2022-04-25 13:05 UTC
### Brand Name

Matlab

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

https://www.mathworks.com/products/matlab.html

### Official Resources for Icon and Color

https://www.mathworks.com/products/matlab.html

### Contributing

No

**Comment by sachinraja** [comment] 2022-04-26 23:27
Duplicate of #5835

**Comment by sachinraja** [comment] 2022-04-26 23:28
See https://github.com/simple-icons/simple-icons/issues/5835#issuecomment-853626958

**Closed by sachinraja** 2022-04-26 23:27 UTC
Labels: new icon
