### ISSUE TITLE
Request: Gitbook Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3957] opened 2020-11-19 13:41 UTC
**Name:** Gitbook
**Website:** https://www.gitbook.com/
**Alexa rank:** 13,945
  

**Official resources for icon and color:** https://www.gitbook.com/

**Comment by mondeja** [comment] 2020-11-19 13:48
There is an SVG version of the logo at https://uploads-ssl.webflow.com/5c349f90a3cd4515d0564552/5c66e5b48238e30e170da3be_logo.svg

**Comment by service-paradis** [comment] 2020-11-19 19:27
Duplicate of https://github.com/simple-icons/simple-icons/issues/3694
Official SVG can be found at http://styleguide.gitbook.com/icons

**Closed by service-paradis** 2020-11-19 19:27 UTC
Labels: good first issue, new icon
