### ISSUE TITLE
Request: HoYoLAB

### ISSUE THREAD

**Issue by slashedzer0** [simple-icons/simple-icons#8786] opened 2023-06-11 16:45 UTC
### Brand Name

HoYoLAB

### Website

https://www.hoyolab.com/home

### Popularity Metric

The Similarweb rank is 698. See https://www.similarweb.com/website/hoyolab.com/

### Official Resources for Icon and Color

svg: None
color: None

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-06-12 12:45
Duplicate of #8390

**Closed by service-paradis** 2023-06-12 12:45 UTC
Labels: new icon
