### ISSUE TITLE
Matplotlib logo

### ISSUE THREAD

**Issue by software-babooi** [simple-icons/simple-icons#9095] opened 2023-07-24 12:06 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org

### Popularity Metric

It is also best used library for data science.

### Official Resources for Icon and Color

I think we dont know the exact color of matplotlib

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-07-28 13:33
Duplicate of #3410

**Closed by adamrusted** 2023-07-28 13:33 UTC
Labels: new icon
