### ISSUE TITLE
Request: Tableau

### ISSUE THREAD

**Issue by danielmarostica** [simple-icons/simple-icons#3412] opened 2020-08-03 01:08 UTC
**Name:** Tableau
**Website:** https://www.tableau.com/
**Alexa rank:** 2,144
  

**Official resources for icon and color:**
https://worldvectorlogo.com/logo/tableau-software

**Comment by PeterShaggyNoble** [comment] 2020-08-04 16:42
Thanks for the request, @danielmarostica :+1:

There's an SVG available at https://github.com/tableau/tableau-viz-lwc/blob/master/force-app/main/default/lwc/tableauViz/tableauViz.svg

For the colour, I'd guess from their website that orange is the primary so we could either go with `#ff6d02` from the stylesheet or   `#e8762d`, which is used for the centre `+` in that SVG.

**Comment by danielmarostica** [comment] 2020-08-05 16:55
I'm sorry, but, why does it have to be monochromatic?

I want something like this: https://iconify.design/icon-sets/logos/python.html

Colorful :)

**Comment by PeterShaggyNoble** [comment] 2021-01-04 11:05
Sorry for the delay, @danielmarostica; been on a bit of a hiatus.

Simple Icons is a monochrome icon library so, if you're in need of a full colour icon, you could use the one I linked above or request it from an icon library that _does_ support full colour icons.

**Comment by PeterShaggyNoble** [comment] 2021-01-04 11:07
As it turns out, this was a dupe of #1188 and was added in #1843 - sorry for not spotting that originally.

**Closed** 2021-01-04 11:09 UTC
Labels: duplicate, new icon
