### ISSUE TITLE
Crates.io Icon

### ISSUE THREAD

**Issue by GreenYun** [simple-icons/simple-icons#8167] opened 2022-12-26 21:01 UTC
### Brand Name

crates.io

### Website

https://crates.io/

### Popularity Metric

The Similarweb rank is 95,895, see https://www.similarweb.com/website/crates.io

### Official Resources for Icon and Color

png: https://github.com/rust-lang/crates.io/blob/master/public/assets/cargo.png

OR

png: https://github.com/rust-lang/crates.io/blob/master/public/assets/crate.svg

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment] 2023-12-05 20:12
Duplicate of #1485

**Closed by PeterShaggyNoble** 2023-12-05 20:12 UTC
Labels: new icon
