### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by dark-teal-coder** [simple-icons/simple-icons#7428] opened 2022-05-19 21:22 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/3.5.0/index.html

### Popularity Metric

https://matplotlib.org ranks 24,882 globally. See https://www.similarweb.com/website/matplotlib.org/#overview. 

### Official Resources for Icon and Color

https://matplotlib.org/3.5.0/gallery/misc/logos2.html

### Additional Comments

I want to create a GitHub badge of Matplotlib but can't find the logo on https://simpleicons.org/.

### Contributing

No

**Comment by sisp** [comment] 2022-05-20 14:16
I've actually looked at the Matplotlib SVG icon a while ago. The problem is that it has an excessive number of path points which aren't actually needed. They seem to be the result of Matplotlib's own conversion of a plot to an SVG image. The SVG icon is generated using a [Python script](https://github.com/matplotlib/matplotlib/blob/main/tools/make_icons.py) which uses Matplotlib itself and is then exported as an SVG image. In my opinion, the SVG icon needs to be redrawn properly based on the icon specs in the script.

**Comment by service-paradis** [comment] 2022-05-20 16:24
Duplicate of #3410

**Closed by service-paradis** 2022-05-20 16:24 UTC
Labels: new icon, duplicate

**Comment by dark-teal-coder** [comment] 2022-05-20 17:31
I have the .svg file here: https://github.com/dark-teal-coder/dark-teal-coder/blob/main/images/matplotlib.svg

See if it's useful. How to add it to https://simpleicons.org?

**Comment by dark-teal-coder** [comment] 2022-05-30 07:33
All the SVG images found:

Matplotlib
https://matplotlib.org/_static/logo2_compressed.svg
Wikimedia
https://upload.wikimedia.org/wikipedia/commons/8/84/Matplotlib_icon.svg
GitHub repo
https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/mpl-data/images/matplotlib.svg
