### ISSUE TITLE
Zabbix icon

### ISSUE THREAD

**Issue by crazynds** [simple-icons/simple-icons#8193] opened 2023-01-02 20:25 UTC
### Brand Name

zabbix

### Website

https://www.zabbix.com/

### Popularity Metric

https://www.similarweb.com/pt/website/zabbix.com/#overview
Global rank: 64,314

### Official Resources for Icon and Color

https://assets.zabbix.com/img/favicon.ico

#D40000

### Contributing

No

**Comment by service-paradis** [comment] 2023-01-09 15:00
Duplicate of #7326

**Closed by service-paradis** 2023-01-09 15:00 UTC
Labels: new icon, duplicate
