### ISSUE TITLE
qBittorrent

### ISSUE THREAD

**Issue by ggonmar** [simple-icons/simple-icons#9785] opened 2023-10-27 12:38 UTC
### Brand Name

qBittorrent

### Website

https://www.qbittorrent.org/

### Popularity Metric

I'm unable to open an account on similarweb, but it's one of the most popular torrent clients at the moment.

### Official Resources for Icon and Color

https://en.wikipedia.org/wiki/File:New_qBittorrent_Logo.svg

**Comment by service-paradis** [comment] 2023-10-27 15:18
Duplicate of #8321

**Closed by service-paradis** 2023-10-27 15:18 UTC
Labels: new icon
