### ISSUE TITLE
Request: edX Icon

### ISSUE THREAD

**Issue by duythanhvn** [simple-icons/simple-icons#3564] opened 2020-09-14 18:33 UTC
**Name:** edX 
**Website:** https://www.edx.org/
**Alexa rank:** https://www.alexa.com/siteinfo/edx.org
  

**Official resources for icon and color:** https://www.edx.org/media-kit

**Comment by NovaGL** [comment] 2020-09-15 03:10
Duplicate of #3340

**Closed by NovaGL** 2020-09-15 03:10 UTC
Labels: new icon
