### ISSUE TITLE
A new icon request for yuque.com

### ISSUE THREAD

**Issue by mumu-pika** [simple-icons/simple-icons#7819] opened 2022-09-19 03:15 UTC
### Brand Name

yuque

### Website

https://www.yuque.com/

### Popularity Metric

The Similarweb rank is 6033.  See: https://www.similarweb.com/website/yuque.com/#overview

![image](https://user-images.githubusercontent.com/79960449/190943965-d4258f10-a480-43c6-8f06-485bfdf39d87.png)

"Yu Que" is a "professional cloud knowledge base", incubated from Ant Financial, an innovative product under the concept of experience technology, and has become the standard for 100,000 Alibaba employees to write documents and accumulate knowledge. At the beginning of its birth, Yuque just hoped to provide engineers with a useful tool for writing technical documents and achieve the small goal of "writing documents with Markdown". But in the process of product development, we found that everyone, every team, and every organization around us has a lot of knowledge, but there has been a lack of a useful tool to keep this knowledge not only in everyone's brain or computer It can also be recorded, shared and communicated.

### Official Resources for Icon and Color

svg: https://gw.alipayobjects.com/zos/bmw-prod/735cefc9-f976-4c87-8b48-85f713f5b713.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-09-19 13:52
Duplicate of #7623

**Closed by service-paradis** 2022-09-19 13:52 UTC
Labels: new icon
