### ISSUE TITLE
Zabbix

### ISSUE THREAD

**Issue by BeeTwenty** [simple-icons/simple-icons#11281] opened 2024-06-19 13:56 UTC
### Brand Name

Zabbix

### Website

https://zabbix.com

### Popularity Metric

https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=zabbix.com

### Official Resources for Icon and Color

none

**Comment by service-paradis** [comment] 2024-06-19 14:05
Duplicate of #7326

**Closed by service-paradis** 2024-06-19 14:05 UTC
Labels: new icon
