### ISSUE TITLE
Request: Showwcase

### ISSUE THREAD

**Issue by el-ang** [simple-icons/simple-icons#7667] opened 2022-08-12 14:05 UTC
### Brand Name

[Showwcase](https://showwcase.com)

### Website

[showwcase.com](https://showwcase.com)

### Popularity Metric

The Similarweb rank is 430,640. See [showwcase.com Traffic Analytics & Market Share | Similarweb](https://www.similarweb.com/website/showwcase.com)

### Official Resources for Icon and Color

svg:
  - [Showwcase Navigation Bar Logo](https://showwcase.com#appbar)
  - [![Showwcase Landing Page Logo](https://assets.showwcase.com/landing-page/svg/footer-logo.svg)](https://assets.showwcase.com/landing-page/svg/logo.svg)
  - [![Showwcase Landing Page Footer Logo](https://assets.showwcase.com/landing-page/svg/footer-logo.svg)](https://assets.showwcase.com/landing-page/svg/footer-logo.svg)

color: `#202021`

### Additional Comments

For this icon/logo, I took some css color from it's property and review any logo color theme used at the page favicon and all logo available at any platform this organization has relation with. At this point, I input the color of the css property that commonly used and seen every day peoples access and use this social platform application by this organization.

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-17 18:28
Duplicate of #6950

**Comment by LitoMore** [comment] 2023-05-19 20:06
Closing since this is duplicated.

**Closed by LitoMore** 2023-05-19 20:06 UTC
Labels: new icon, duplicate
