### ISSUE TITLE
Cloudinary icon add

### ISSUE THREAD

**Issue by Manav-Khandurie** [simple-icons/simple-icons#9880] opened 2023-11-20 12:59 UTC
### Brand Name

Cloudinary

### Website

https://cloudinary.com/

### Popularity Metric

https://share.similarweb.com/sharePost?params=eyJwYWdlSWQiOiJvVmQ5eGhzS1Z3QS1kRWRUUU1XQlgiLCJ0aXRsZSI6ImNsb3VkaW5hcnkuY29tIFJhbmtpbmcgYnkgVHJhZmZpYyIsImRlc2NyaXB0aW9uIjoiV2Vic2l0ZSByYW5raW5nIGhlbHBzIGV2YWx1YXRlIHRoZSB2YWx1ZSBvZiBhIGJ1c2luZXNzLiBPdmVyIHRoZSBsYXN0IHRocmVlIG1vbnRocywgY2xvdWRpbmFyeS5jb20ncyBnbG9iYWwgcmFua2luZyBoYXMgZGVjcmVhc2VkIGZyb20gOCw0OTkgdG8gOCw0NTcuIiwicmVkaXJlY3RVcmwiOiJodHRwczovL3d3dy5zaW1pbGFyd2ViLmNvbS93ZWJzaXRlL2Nsb3VkaW5hcnkuY29tLyNyYW5raW5nIn0=

Global Rank
#8,457

Country Rank
#6,048

Category Rank
#189

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2023-11-20 17:59
Duplicate of #8327

**Closed by service-paradis** 2023-11-20 17:59 UTC
Labels: new icon, good first issue
