### ISSUE TITLE
Zabbix

### ISSUE THREAD

**Issue by tonytech83** [simple-icons/simple-icons#9814] opened 2023-11-04 14:14 UTC
### Brand Name

Zabbix icon

### Website

https://www.zabbix.com/

### Popularity Metric

The Similarweb rang is 62,505. See https://www.similarweb.com/website/zabbix.com/#overview

### Official Resources for Icon and Color

svg: https://www.vectorlogo.zone/util/preview.html?image=/logos/zabbix/zabbix-icon.svg
color: #c72229

**Comment by adamrusted** [comment] 2023-11-04 15:18
Unfortunately, we cannot use VectorLogoZone as an official source. Is there an official source we can make use of?

**Comment by tonytech83** [comment] 2023-11-04 19:50
Maybe it's not a good idea to make a logo at all if you can't use this from VectorLogoZone , because only there I found simple "Z" as logo. I think that official is "ZABBIX" -> https://upload.wikimedia.org/wikipedia/commons/6/6f/Zabbix_logo.svg

Thank you!

**Comment by service-paradis** [comment] 2023-11-07 13:44
Duplicate of #7326

**Closed by service-paradis** 2023-11-07 13:44 UTC
Labels: new icon
