### ISSUE TITLE
Proteus Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8666] opened 2023-05-19 16:48 UTC
### Brand Name

Proteus Design Suite (Labcenter electronics)

### Website

https://www.labcenter.com/

### Popularity Metric

It is only popular for electronics students and professionals. The similarweb global rank is 274,077.

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-19 20:13
Duplicate of #8082

**Closed by service-paradis** 2023-05-19 20:13 UTC
Labels: new icon
