### ISSUE TITLE
TypeORM Icon

### ISSUE THREAD

**Issue by mabuhanifa** [simple-icons/simple-icons#8953] opened 2023-07-07 21:52 UTC
### Brand Name

TypeORM

### Website

https://typeorm.io

### Popularity Metric

https://www.similarweb.com/website/typeorm.io/#overview

### Official Resources for Icon and Color

https://typeorm.io

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-07-10 15:53
Duplicate of #8147

**Closed by service-paradis** 2023-07-10 15:53 UTC
Labels: new icon
