### ISSUE TITLE
Request: Modrinth

### ISSUE THREAD

**Issue by akiyuee** [simple-icons/simple-icons#7688] opened 2022-08-21 11:37 UTC
### Brand Name

Modrinth

### Website

https://modrinth.com

### Popularity Metric

SW Rank: #40,587 - https://www.similarweb.com/website/modrinth.com/#overview

### Official Resources for Icon and Color

ico: https://modrinth.com/favicon.ico
color: #30b27b

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-08-29 14:37
Duplicate of #7488

**Closed by service-paradis** 2022-08-29 14:37 UTC
Labels: new icon
