### ISSUE TITLE
Add Daily.dev icon

### ISSUE THREAD

**Issue by Evavic44** [simple-icons/simple-icons#7445] opened 2022-05-25 19:26 UTC
### Brand Name

Daily

### Website

https://daily.dev/

### Popularity Metric

The Similarweb rank is 31,774. See https://www.similarweb.com/website/daily.dev/#overview

#### Black
![daily-black](https://user-images.githubusercontent.com/62628408/170349915-eb5cc36c-4e11-4253-9c9e-a4f8eb0f93dd.svg)
#### White
![daily-white](https://user-images.githubusercontent.com/62628408/170349921-b5e0c77d-8b16-4a7c-806c-ba977c8fd249.svg)

## Color code
`#151618` `#999A9D`

### Additional Comments

There are two variants to these icons. Black + grey on white background, and white + grey on black background.

Daily.dev is a fast-rising platform for developers and technical writers. 

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-05-25 23:44
Duplicate of #7402

**Closed by sachinraja** 2022-05-25 23:44 UTC
Labels: new icon, potential duplicate
