### ISSUE TITLE
MathWorks MATLAB

### ISSUE THREAD

**Issue by The-Kriz** [simple-icons/simple-icons#8171] opened 2022-12-27 14:20 UTC
### Brand Name

MathWorks 

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

Global Rank
#4,412

Total Visits
14.6M

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/2/21/Matlab_Logo.png

Sea Serpent 

Hex color: | #49c3c3
RGB: | 73 195 195
CMYK: | 63 0 0 24
Pantone: | PMS 3262 C

Vivid Yellow

Hex color:  #ffdd0d
RGB: | 255 221 13
CMYK: | 0 13 95 0
Pantone: | PMS 108 C

Bulgarian Rose 

Hex color: | #450b0e
RGB: | 69 11 14
CMYK: | 0 84 80 73
Pantone: | PMS 188 C

Spanish Orange 

Hex color: | #e86e05
RGB: | 232 110 5
CMYK: | 0 53 98 9
Pantone: | PMS 1585 C

International Orange 

Hex color: | #be2909
RGB: | 190 41 9
CMYK: | 0 78 95 25
Pantone: | PMS 485 C

Black 

Hex color: | #000000
RGB: | 0 0 0
CMYK: | 0 0 0 100
Pantone: | PMS Process Black C

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-01-09 15:03
Duplicate of #5835

**Closed by service-paradis** 2023-01-09 15:03 UTC
Labels: new icon
