### ISSUE TITLE
ActionScript

### ISSUE THREAD

**Issue by davy-blavette** [simple-icons/simple-icons#10364] opened 2024-01-26 11:13 UTC
### Brand Name

ActionScript

### Website

https://fr.wikipedia.org/wiki/ActionScript

### Popularity Metric

Low but again use with Unity

### Official Resources for Icon and Color

#fb382d
https://upload.wikimedia.org/wikipedia/commons/4/45/Farm-Fresh_page_white_actionscript.png

**Comment by PeterShaggyNoble** [comment] 2024-01-26 11:52
Thanks for the request, @davy-blavette. However, ActionScript doesn't have an official logo or icon that we could use. There is a file type icon but those are beyond the scope of our library and the icon you linked to above is an unofficial, custom icon from another library.

Also, this is somewhat a duplicate of #89

**Closed by PeterShaggyNoble** 2024-01-26 11:52 UTC
Labels: new icon
