### ISSUE TITLE
Request: Apache Tomcat icon

### ISSUE THREAD

**Issue by ckaridis** [simple-icons/simple-icons#4307] opened 2020-12-10 18:44 UTC
**Name:**  Apache Tomcat
**Website:** http://tomcat.apache.org/
**Alexa rank:** 2,308 (for apache.com)
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment] 2020-12-10 18:55
Duplicate of https://github.com/simple-icons/simple-icons/issues/3879

**Closed by service-paradis** 2020-12-10 18:55 UTC
Labels: new icon
