### ISSUE TITLE
Databricks icons

### ISSUE THREAD

**Issue by rodneyjoyce** [simple-icons/simple-icons#4090] opened 2020-11-21 00:54 UTC
Databricks
https://databricks.com
13702  https://www.alexa.com/siteinfo/databricks.com
<img width="592" alt="DAT_Stacked_Lock_up_Full_Color@2x" src="https://user-images.githubusercontent.com/3522966/99863031-5dc0e480-2bf0-11eb-8e87-926c09a8ef0d.png">

**Comment by rodneyjoyce** [comment] 2020-11-21 00:55
Note: Just the top icon is needed, thanks!

**Comment by fbernhart** [comment] 2020-11-21 02:25
Quoting https://brand.databricks.com/Styleguide/Guide/#page/59EE8808-1DA4-41D6-95E62D23B4073806

> Request permission
> If you would like to use Databricks materials, please contact brand@databricks.com and provide the following information:
> 
> - Your name and title
> - Company name and location 
> - Description of request

Color: I would choose red `#FF3621`, as defined here: https://brand.databricks.com/Styleguide/Guide/#page/D8C1B406-2E65-42F8-8311A1B1B5B8C735

**Comment by NovaGL** [comment] 2020-11-24 08:51
Duplicate of #3442 

Feel free to create a PR though

**Closed by NovaGL** 2020-11-24 08:51 UTC
Labels: new icon
