### ISSUE TITLE
Request: Lancia

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#8474] opened 2023-03-27 07:02 UTC
### Brand Name

Lancia

### Website

https://lancia.com

### Popularity Metric

The Similarweb rank is 901,269. See https://www.similarweb.com/website/lancia.com

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/ru/b/ba/Lancia_Logo.svg
color: `#002371` taken from the site header

### Contributing

Yes

**Comment by PeterShaggyNoble** [comment] 2023-11-29 19:29
Duplicate of #4681

**Closed** 2023-11-29 19:29 UTC
Labels: new icon
