### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11434] opened 2024-07-08 06:36 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It is ranked 37,553 in SimilarWeb. See https://www.similarweb.com/website/matplotlib.org/#overview

### Official Resources for Icon and Color

24x24 Monochrome SVG created as per [Contribution Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity) is given below:

![matplotlib-icon-white-24x24](https://github.com/simple-icons/simple-icons/assets/25684256/350698f7-9c4e-40bd-83f4-52869c3760f1)

### Additional Comments

Matplotlib is one of the go to libraries for creating plots with Python. It is extensively used for Artificial Intelligence, Machine Learning, Deep Learning projects. It is one of the libraries that comes pre-installed when we access a Google Colab machine.

**Comment by uncenter** [comment] 2024-07-08 07:04
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed** 2024-07-08 07:04 UTC
Labels: new icon
