### ISSUE TITLE
Request: Play Framework

### ISSUE THREAD

**Issue by seanmaaa** [simple-icons/simple-icons#6604] opened 2021-09-27 00:54 UTC
### Brand Name

Play Framework

### Website

https://www.playframework.com

### Popularity Metric

The Alexa rank is 179,954. See https://www.alexa.com/siteinfo/playframework.com
12K Stars on Github. See https://github.com/playframework/playframework

### Official Resources for Icon and Color

Official resources for icon and color: Available on play framework git repository.
https://github.com/playframework/playframework.com/tree/master/public/images/logos

Color : #7FCD42 (from site's header)

### Contributing

Yes

**Comment by service-paradis** [comment] 2021-09-27 12:36
Duplicate of #6068

Thank you for your request @seanmaaa. I'm closing this one in favor of the older #6068, but feel free to contribute :)

**Closed by service-paradis** 2021-09-27 12:36 UTC
Labels: new icon
