### ISSUE TITLE
Request: Keras

### ISSUE THREAD

**Issue by danielmarostica** [simple-icons/simple-icons#3411] opened 2020-08-03 01:05 UTC
**Name:** Keras
**Website:** keras.io
**Alexa rank:** 23,543
  

**Official resources for icon and color:**
https://commons.wikimedia.org/wiki/File:Keras_logo.svg

**Comment by PeterShaggyNoble** [comment] 2020-08-04 16:36
Thanks for the request, @danielmarostica :+1:

To my eye, at least, the corners of the `K` in the source file you provided look somewhat different to those in [the logo on their website](https://keras.io/img/logo.png) but my eye isn't always the best judge of these things so let's see if any of the other @simple-icons/maintainers agree. If they do, there are, unfortunately, no vector versions available on their website (that I could find) or in their GitHub repos so we may need to recreate this manually.

For the colour, I'd suggest `#d00000` from their website's stylesheet.

**Comment by ericcornelissen** [comment] 2020-08-04 21:02
I can confirm that there are some notable differences between [the logo on their website](https://keras.io/img/logo.png) and [the SVG version of the logo on Wikimedia](https://commons.wikimedia.org/wiki/File:Keras_logo.svg) as shown ⬇️ 

![image](https://user-images.githubusercontent.com/3742559/89344613-ce2e0f00-d6ae-11ea-900c-edf78160b6c2.png)

<sup>The overlay - larger and transparent K - is the vector</sup>

**Comment by danielmarostica** [comment] 2020-08-05 16:02
It would be simple to vectorize it. 

Will it be accepted if I do this? Where should I upload it btw?

**Comment by ericcornelissen** [comment] 2020-08-06 10:49
> It would be simple to vectorize it.
> 
> Will it be accepted if I do this? Where should I upload it btw?

Yes, in the absence of an official vector version we look for someone that can provide a vectorized version of the logo. If you think you can do that @danielmarostica, go ahead an submit a Pull Request. You can read more about the details in [the Contributing Guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md).

**Comment by NovaGL** [comment] 2020-08-06 10:53
This has already been merged. How is it different than this logo? #1793

**Comment by ericcornelissen** [comment] 2020-08-06 10:58
Oops, can't believe we missed that :sweat_smile: Thanks for pointing this out @NovaGL! Looks like [Keras is already available on Simple Icons](https://simpleicons.org/?q=Keras) (and not sourced from Wikimedia)

**Closed by ericcornelissen** 2020-08-06 10:58 UTC
Labels: awaiting reply, new icon
