### ISSUE TITLE
Request: Texas Instruments

### ISSUE THREAD

**Issue by HashemLovesYou** [simple-icons/simple-icons#6885] opened 2021-11-20 23:37 UTC
### Brand Name

Texas Instruments

### Website

https://www.ti.com/

### Popularity Metric

Alexa rank 9,121 as per [](https://www.alexa.com/siteinfo/ti.com)

### Official Resources for Icon and Color

[](https://www.ti.com/etc/designs/ti/images/ui/ic-logo.svg)
color CC0000

### Additional Comments

only include the logo not the text

### Contributing

No

**Comment by HashemLovesYou** [comment] 2021-11-21 01:51
Not a dupe of either

**Comment by service-paradis** [comment] 2021-11-22 14:00
Thank you @HashemLovesYou for the request. Next time, please include the brand name in the issue title.

Using the logo only is, unfortunately, not an option according to their [guidelines](https://www.ti.com/legal/terms-conditions/trademarks/signature-and-logo.html):
> Please use the preferred or alternate signature, not TI's logo alone.

In fact, I wonder if we can really add this brands in our collection since they asks for explicit attribution as stated in https://www.ti.com/legal/terms-conditions/trademarks/attribution-of-marks-in-literature.html.

I will ask other @simple-icons/maintainers opinion on this potential addition.

**Comment by HashemLovesYou** [comment] 2021-11-22 15:22
My bad. Thanks for the consideration

**Comment by sachinraja** [comment] 2021-11-22 20:53
I agree with @service-paradis, I don't think we can add this.

**Comment by mondeja** [comment] 2021-11-23 10:17
I agree too. Closing as is out of our scope, feel free to reopen it if you consider it 👍🏼

**Closed by mondeja** 2021-11-23 10:17 UTC
Labels: new icon, awaiting reply, in discussion

**Comment by jorgeamadosoria** [comment] 2021-11-23 16:23
> Thank you @HashemLovesYou for the request. Next time, please include the brand name in the issue title.
> 
> Using the logo only is, unfortunately, not an option according to their [guidelines](https://www.ti.com/legal/terms-conditions/trademarks/signature-and-logo.html):
> 
> > Please use the preferred or alternate signature, not TI's logo alone.
> 
> In fact, I wonder if we can really add this brands in our collection since they asks for explicit attribution as stated in https://www.ti.com/legal/terms-conditions/trademarks/attribution-of-marks-in-literature.html.
> 
> I will ask other @simple-icons/maintainers opinion on this potential addition.

In my reading of the trademark, I think that (arguably) doesn't apply to us but rather the end user. Since we are not referring to their services or products, we don't have to add the attributions they request, but anyone who does use it are legally bound to do it.

So I think we are in the clear adding this icon. However, the use may be complicated for the end user if they don't read the guidelines (and who does that, anyways?)

**Comment by mondeja** [comment] 2021-11-23 17:04
As I can understand here, the problem is that the logo can't be used separated of the wordmark, right?

**Comment by jorgeamadosoria** [comment] 2021-11-23 22:52
> As I can understand here, the problem is that the logo can't be used separated of the wordmark, right?

also, that it can't be used without attribution
