### ISSUE TITLE
Request: Disney+ Icon

### ISSUE THREAD

**Issue by rooneyaut** [simple-icons/simple-icons#7235] opened 2022-03-18 14:13 UTC
### Brand Name

Disney+

### Website

https://www.disneyplus.com

### Popularity Metric

#115 Similarweb rank

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-03-19 02:02
Duplicate of #2309

...and many others. Disney is super strict about their brands, and so we will not be adding them to this project.

**Comment by sachinraja** [comment] 2022-03-19 02:03
Duplicate of #2309

**Closed by sachinraja** 2022-03-19 02:02 UTC
Labels: new icon
