### ISSUE TITLE
Request: Hedera

### ISSUE THREAD

**Issue by nakshatrasinghh** [simple-icons/simple-icons#7422] opened 2022-05-17 06:10 UTC
### Brand Name

Hedera

### Website

https://hedera.com/

### Popularity Metric

Global Rank
#148,457

Country Rank
#100,808

Category Rank
#1,045

### Official Resources for Icon and Color

color: #010101

### Contributing

No

**Comment by service-paradis** [comment] 2022-05-23 19:00
Duplicate of #6112

**Closed by service-paradis** 2022-05-23 19:00 UTC
Labels: new icon
