### ISSUE TITLE
black icon

### ISSUE THREAD

**Issue by 12rambau** [simple-icons/simple-icons#8511] opened 2023-04-05 10:06 UTC
### Brand Name

black

### Website

https://github.com/psf/black

### Popularity Metric

the project has ~32k stars on github

### Official Resources for Icon and Color

png: https://raw.githubusercontent.com/psf/black/main/docs/_static/logo2-readme.png

### Additional Comments

this is the most used python linter, I find the prettier project in the icon list, why not this one ?

### Contributing

I don't have the time at the moment

**Comment by adamrusted** [comment] 2023-07-24 11:51
Duplicate of #4928

**Closed by adamrusted** 2023-07-24 11:51 UTC
Labels: new icon

**Comment by 12rambau** [comment] 2023-07-24 12:02
sorry for the noise I was sure to have checked

**Comment by adamrusted** [comment] 2023-07-24 12:03
No worries! I'm on my second pass of issues today, and didn't spot it initially!
