### ISSUE TITLE
Request: flightradar24

### ISSUE THREAD

**Issue by Adhithya8055** [simple-icons/simple-icons#11352] opened 2024-06-29 05:35 UTC
### Brand Name

FlightRadar24

### Website

https://www.flightradar24.com/

### Popularity Metric

Global : 511

### Official Resources for Icon and Color

unknown

**Comment by adamrusted** [comment] 2024-06-29 05:44
Duplicate of #8337

**Closed by adamrusted** 2024-06-29 05:44 UTC
Labels: new icon
