### ISSUE TITLE
Request: InertiaJS

### ISSUE THREAD

**Issue by farhan15r** [simple-icons/simple-icons#7620] opened 2022-07-24 13:13 UTC
### Brand Name

InertiaJS

### Website

https://inertiajs.com/

### Popularity Metric

https://avatars.githubusercontent.com/u/47703742?s=200&v=4

### Official Resources for Icon and Color

.

### Contributing

No

**Comment by service-paradis** [comment] 2022-07-24 20:39
Duplicate of #7371

**Closed by service-paradis** 2022-07-24 20:39 UTC
Labels: new icon
