### ISSUE TITLE
Missing Zeplin icon

### ISSUE THREAD

**Issue by mosttafa** [simple-icons/simple-icons#10924] opened 2024-05-09 11:58 UTC
### Brand Name

Zeplin

### Website

https://zeplin.io/

### Popularity Metric

The similarweb rank is 68,172. See:  https://www.similarweb.com/website/zeplin.io/#overview

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2024-05-09 23:28
Duplicate of #4978

**Closed by service-paradis** 2024-05-09 23:28 UTC
Labels: new icon
