### ISSUE TITLE
Request: Deepsource

### ISSUE THREAD

**Issue by MichaelHinrichs** [simple-icons/simple-icons#11603] opened 2024-08-11 22:52 UTC
### Brand Name

Deepsource

### Website

https://deepsource.com/

### Popularity Metric

https://www.similarweb.com/website/deepsource.com/#overview

### Official Resources for Icon and Color

![Deepsource_logo](https://github.com/user-attachments/assets/6e1867f3-d0c3-4968-81b3-adca85649fe2)

**Comment by uncenter** [comment] 2024-12-05 03:07
Duplicate of #7149, and the Similarweb rank is still out of scope here.

**Closed by uncenter** 2024-12-05 03:07 UTC
Labels: new icon
