### ISSUE TITLE
Create EJS icon

### ISSUE THREAD

**Issue by user2695** [simple-icons/simple-icons#7412] opened 2022-05-14 08:47 UTC
### Brand Name

EJS

### Website

https://ejs.co/

### Popularity Metric

347,374

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-05-16 17:54
Duplicate of #6132

**Closed by service-paradis** 2022-05-16 17:54 UTC
Labels: new icon

**Comment by user2695** [comment] 2022-05-19 11:13
I am seeing duplicate labels everywhere but not the ejs icon. Can you help me a bit here?

**Comment by service-paradis** [comment] 2022-05-19 17:42
The EJS were not added yet to the project. #6132 is the request for it. There is no need to have multiple issue requesting the same icon. This is why this one was marked as duplicate.
