### ISSUE TITLE
Icon Request: Sanity

### ISSUE THREAD

**Issue by LucaArgentieri** [simple-icons/simple-icons#7775] opened 2022-09-13 19:03 UTC
### Brand Name

Sanity

### Website

https://www.sanity.io/

### Popularity Metric

[61,141](https://www.similarweb.com/it/website/sanity.io/)

### Official Resources for Icon and Color

![116-1166936_sanity-io-logo-png-transparent-png](https://user-images.githubusercontent.com/57524787/189987831-9cee69a9-5d28-4c69-89a3-a7cfd2b866ea.png)

Transparent background

### Contributing

Yes

**Comment by adamrusted** [comment] 2022-09-17 13:32
The favicon, and further down the homepage just uses the 'S' - could you get away with that?

**Comment by service-paradis** [comment] 2022-09-19 13:53
Duplicate of #6443

**Closed by service-paradis** 2022-09-19 13:53 UTC
Labels: new icon
