### ISSUE TITLE
Add Atlantis

### ISSUE THREAD

**Issue by chenrui333** [simple-icons/simple-icons#10173] opened 2023-12-22 05:15 UTC
### Brand Name

Atlantis

### Website

https://www.runatlantis.io/

### Popularity Metric

As of 2023-12-22,

The Similarweb (global) rank is 1,109,741. See https://www.similarweb.com/website/opentofu.org
The number of Github stars is 6.8k. See https://github.com/runatlantis/atlantis

soon to be cncf sandbox project, https://github.com/cncf/sandbox/issues/60

### Official Resources for Icon and Color

This is the website logo, https://www.runatlantis.io/hero.png

**Comment by adamrusted** [comment] 2023-12-22 11:04
@chenrui333 - the URL you've linked to for SimilarWeb is OpenTofu, not Atlantis.

**Comment by service-paradis** [comment] 2023-12-22 13:02
Duplicate of #9703

**Closed by service-paradis** 2023-12-22 13:02 UTC
Labels: new icon

**Comment by chenrui333** [comment] 2023-12-22 15:14
good to know #9703!
