### ISSUE TITLE
Request: Blue Origin

### ISSUE THREAD

**Issue by RicoOrtiz** [simple-icons/simple-icons#10762] opened 2024-04-03 18:48 UTC
### Brand Name

Blue Origin

### Website

https://www.blueorigin.com/

### Popularity Metric

The similarweb rank is 184,242. This is show at https://www.similarweb.com/website/blueorigin.com/#overview

### Official Resources for Icon and Color

https://logowik.com/blue-origin-logo-vector-svg-pdf-ai-eps-cdr-free-download-9573.html
Origin Gothic and Barlow fonts
Blue color:  HEX code, #0033DD, or RGB: R0, G51, B25

**Comment by service-paradis** [comment] 2024-04-03 19:56
Duplicate of #6248
Permission is required to add this one.

**Closed by service-paradis** 2024-04-03 19:56 UTC
Labels: new icon
