### ISSUE TITLE
Request for Workday Icon

### ISSUE THREAD

**Issue by eddielanderos** [simple-icons/simple-icons#10660] opened 2024-03-17 06:50 UTC
### Brand Name

Workday

### Website

https://www.stickpng.com/img/icons-logos-emojis/tech-companies/workday-app-logo

### Popularity Metric

https://www.stickpng.com/img/icons-logos-emojis/tech-companies/workday-app-logo

### Official Resources for Icon and Color

none

### Additional Comments

Thank you

**Comment by PeterShaggyNoble** [comment] 2024-03-17 09:20
Duplicate of #7833

**Closed** 2024-03-17 09:20 UTC
Labels: new icon
