### ISSUE TITLE
Create a Code of Conduct

### ISSUE THREAD

**Issue by davidklebanoff** [simple-icons/simple-icons#1384] opened 2019-04-27 22:45 UTC
Simple Icons has grown substantially over the years. The time has come to codify our values and standards of conduct for Maintainers, Contributors, and visitors alike.

**Comment by ericcornelissen** [comment] 2019-05-03 10:41
@mnn, may I ask why you reacted to this issue with a _thumbs down_?

**Comment by birjolaxew** [comment] 2019-05-03 14:34
@ericcornelissen I can't respond on his behalf, but I am also generally not a fan of CoC's. All of this is of course my own personal opinion.

Codification (as in the case of codifying the moral compass of a community into a written code of conduct) doesn't come without a cost. By the nature of how complex it is, morality can't be accurately converted to rules. The rules must either be so general that they cover things we morally consider ok, or be specific enough that they cover things we morally consider bad. This wouldn't be so bad if everyone agreed that the code of conduct isn't 100% accurate, but the mere act of writing down rules almost always changes the attitude towards them from one of "don't do bad things" to "don't do things that are against the rules (which try to describe what bad things are)".

You can avoid this cost by not codifying the moral compass of the community; this is how most communities work. Alternatively, if you wish to have a CoC, you can make the CoC so general that it basically just says "don't do bad things", which is essentially the same thing.

It is of course up for debate when the positives of codifying the rules of conducts outweigh the negatives, but for most smaller projects that I have seen adopt a CoC, it has been a solution to a problem that didn't exist.

I think that this is an important debate to have, but if the CoC will simply be of the "don't do bad things" variant then I will personally question whether there is a need for them in the first place. Is there a problem that this is trying to solve?

**Comment by mnn** [comment] 2019-05-03 16:24
Solid response from @birjolaxew, much better articulated than mine is.

---
My general opinion on CoCs: I don't like them at all.

The problem is, that it is either so general, that is in fact useless, because those rules were already being implicitly followed. And so it is pointless to add a such CoC.

Or the rules, or rather the people creating these rules, try to force their politics onto others (in all cases of politics-pushing I saw, they were an authoritarian, usually identitarian, left). This leads to a toxic community for a few weeks or months, ostracizing long term valuable contributers who are bullied out by lefty activists who don't care about the project, in majority of cases do no contributions, and only "joined" the project to virtue signal, to get points on social media, to kick out people who were real contributors. I disagree with weaponizing vague rules to get rid of people having different (not only political) opinions. Like for example the guy in Linux kernel who they tried to kick out, because he dared to critize objective flaws in a rape study. They argued he is a rape apologist... I don't think they succeeced, but if the rules were followed, they would have. And this is the kind of intolerant community you will be building, if you install rules deeply rooted in political opinions. It would result in fragmentation of your contributers and current community, loosing many people (to forks or to rival, more free, projects) and discouraging new people to join/use a politically active project.

When I have a choice at which library/language/asset/project to use or contribute to, I always chose a project without CoC, or generally a project without openly political rules.

**Comment by ericcornelissen** [comment] 2019-05-03 17:30
Those are interesting viewpoints 🤔 

I'm not all to familiar with CoCs, but from my experience there is also plenty of projects that have one and don't show this kind of behavior. I guess you point out an interesting example @mnn, but without context it is somewhat vague and I don't see how it really applies to this project, care to share a link explaining what happened?

I do personally believe that a Code of Conduct, even a somewhat vague one, can be useful. Even a CoC that is essentially "don't do bad things" shows that the maintainers care about the project and the contributors that give their, probably spare, time to the project. Showing that they (the maintainers) are willing to spent time and effort in protecting them (the contributors) against, for example, harassment.

I agree that it would ideally not contain a particular political stance (although we are already taking the political stance that [pirating is a "bad" thing](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon)). But something like "don't harass others" is already less vague then "don't do bad things" and I strongly believe that is not a _lefty_ thing. And I'm sure there is other similar things that can be incorporated in our CoC, that is why it is important to discuss the matter.

As for where this issue comes from, mostly from whatever happened in #1339. In my personal opinion it is not bad to have a CoC for a project this size (although simple, I wouldn't call lit small). Also the fact that (almost) nothing bad happened so far doesn't mean it won't happen in the future.

**Comment by mnn** [comment] 2019-05-03 18:42
> I'm not all to familiar with CoCs, but from my experience there is also plenty of projects that have one and don't show this kind of behavior.

If you have such CoC from start, or looking on the community after long time, you end up with people (contributors and community) with same values, same bias. So if your CoC has strong left wing (nowadays synonym to "progressive" = identitarian and illiberal) bias, then you will have only strong left wingers in your community and contributors (forming an ideological bubble), because everybody else, left-leaning, liberals (by that I mean true original liberals supporting personal freedom and so on), centrists and to the right, will avoid your project like fire. Easy to spot signs of biased CoC are use of many terms like minority, race, sex, gender, sexual orientation, sexual identity, over-concentration on feelings, undermining merit. Good example of this was the infamous "Contributor Covenant Code of Conduct" (I think they did actually fix some issues, but it is still biased, since for example forced usage of personal pronouns is a "progressive" ideology which many people don't agree and won't allow to be forced into by CoC/ToS or laws, even if in real life they would have no issue using such pronouns if the other side respects them as well). I don't deny that CCCoC looks nice on a paper, but in practise it is used to bully out "non-progressive" (many view them as "non-regressive") people who don't care about politics, so they don't actively try to kick out people who they don't agree with on e.g. politics discussed off-platform, because they don't care, they don't want to discuss personal politics in IT projects. Sure, you can use more sane version and mention harassment just once without all the buzzwords, but then it seems useless to have such common sense rules even written down.

Here is some reddit thread http://archive.is/ohsnr, there are probably better sources, but you can see just from the comments how the attacker (radical feminist) is trying to kick out a long term contributor, arguing he is a rape apologist (even if he was, I honestly don't see a reason why it should affect his contributions to an IT project). Even thought he was merely pointing at errors in a study, errors which were acknowledged even by the author of the study. She also seems to be breaking the very same CoC she was trying to weaponize...

I am not saying you should not implement CoC, that is your choice and I support your freedom to do so. But if you do use biased CoC, expect to attract similar extremists like that one mentioned, and to deter non-extreme or even apolitical users and contributors, because we don't like this kind of drama caused by (inherently apolitical) projects going political.

**Comment by birjolaxew** [comment] 2019-05-04 02:01
@ericcornelissen 

> But something like "don't harass others" is already less vague then "don't do bad things"

For the sake of the argument I was making, those are essentially the same thing. "Don't harass others" is so general that it doesn't bring anything new to the table when compared to before the rules of conduct were codified - one would assume that everyone already agrees that harassment is bad. Having it written down serves no purpose beyond, well, having it written down.

> Even a CoC that is essentially "don't do bad things" shows that the maintainers care about the project and the contributors that give their, probably spare, time to the project. Showing that they (the maintainers) are willing to spent time and effort in protecting them (the contributors) against, for example, harassment.

That is an interesting point to make. The power of CoC as a virtue signalling device (for lack of better term; "virtue signalling" has unfortunately adopted mostly negative connotations in recent years - I use it here for its original academic meaning) is undeniably strong, and I think that if readers see it the way you do, it is definitely a positive.

I will point out that this works both ways. Having a CoC gives an impression of a more "closed" community, in the sense that everyone must agree on more than just having an interesting in the project. This is perfectly fine for projects for which this is already a requirement (e.g. the community around a project like Tor must agree that total privacy = good, and signalling this through some means is important), but for Simple Icons this feels a bit out of place. Especially with the political connotations that CoC's have gotten (whether deserved or undeserved; I don't follow politics enough to comment on that), this could mean that some contributors are less likely to participate because they deem the virtues shown to not match their own.

**Comment by ericcornelissen** [comment] 2019-05-06 06:55
Okay, I agree the politics aspect of this can be tricky. I also certainly agree that this project is (mostly<sup>1</sup>) apolitical and doesn't need a CoC from that point of view (as opposed to e.g. the Tor project).

The discussion so far has mostly been about the people that like CoCs versus the people that don't like CoCs. And both groups will either contribute/not contribute based on whether there is a CoC or not. I think it is hard to find common ground in this regard, other then maybe: "have a CoC that is so general it is mostly meaningless for the purpose of _virtue signalling_<sup>2</sup>." (admittedly that is my current best solution for this issue 😅)

I hope more contributors join in on the discussion, from either side, with constructive feedback on how to tackle this issue. Of course, no CoC is also still a possibility.


> I don't deny that CCCoC looks nice on a paper, but in practise it is used to bully out "non-progressive" [...] people who don't care about politics, [...]

For the purposes of better understanding you @mnn, would you mind giving an extract from the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct) that can be used to the ends you described and how?

---

1. again the [pirating is a "bad" thing](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon) remark we have.
2. as it was [described by @birjolaxew](https://github.com/simple-icons/simple-icons/issues/1384#issuecomment-489284950)

**Comment by ericcornelissen** [comment] 2021-08-22 14:19
Any input on this one from @simple-icons/maintainers - if a majority thinks we shouldn't add it I think we should just close this.

**Comment by mondeja** [comment] 2021-08-22 16:06
I'm totally against adding it and agree with the arguments previously exposed in this issue.

**Comment by runxel** [comment] 2021-08-23 21:14
Some time ago I read a general comment on CoCs – from a very "progressive" person.
Long story short: If you need a CoC your community is already toxic and a CoC won't stop them nor solve the _underlying_ problem.
Also as others mentioned: We live in a civilized society, so "don't be an asshole" should already be the norm.

I'd be in favor of not adding a CoC at the moment.

**Comment by jorgeamadosoria** [comment] 2021-08-23 22:21
I think a code of conduct or a set of rules is always good.
However, I also think that we shouldn't add things if there is no need for them just yet.
So, if we can deal with feedback and contributions constructively (and for what I've seem most people subscribe to @runxel's general DBAS rule) we can live without a CoC for a little while longer at least.

**Comment by ericcornelissen** [comment] 2021-08-23 22:39
Seems there's still a general consensus against it so I'll be closing this.

To anyone stumbling on this thread, feel free to leave a comment here if you want to bring the discussion back to life.

**Closed by ericcornelissen** 2021-08-23 22:39 UTC
Labels: meta
