### ISSUE TITLE
Request: Code::Blocks logo

### ISSUE THREAD

**Issue by srushti1006** [simple-icons/simple-icons#7080] opened 2022-01-20 06:49 UTC
### Brand Name

Code::Blocks

### Website

https://www.codeblocks.org/

### Popularity Metric

Alexa rank : 47,675
https://www.alexa.com/siteinfo/codeblocks.org

### Official Resources for Icon and Color

https://www.codeblocks.org/images/logo160.png

### Additional Comments

Alternative logo: https://www.codeblocks.org/docs/cb_splash.png

### Contributing

No

**Comment by sachinraja** [comment] 2022-01-20 13:51
duplicate of #6637

**Closed by sachinraja** 2022-01-20 13:51 UTC
Labels: new icon
