### ISSUE TITLE
Gazebo Logo Missing

### ISSUE THREAD

**Issue by smitshah** [simple-icons/simple-icons#8669] opened 2023-05-19 16:54 UTC
### Brand Name

Gazebo

### Website

https://gazebosim.org/

### Popularity Metric

This is very popular in Robotics domain. The silimarweb global rank is 455,869.

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Gazebo_logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-19 20:13
Duplicate of #8529

**Closed by service-paradis** 2023-05-19 20:13 UTC
Labels: new icon
