### ISSUE TITLE
MIT (Massachusetts Institute of Technology)

### ISSUE THREAD

**Issue by neilroy1998** [simple-icons/simple-icons#3579] opened 2020-09-19 19:43 UTC
**Name:** MIT (Massachusetts Institute of Technology)
**Website:** https://www.mit.edu/
**Alexa rank:** 546
**Why?:** For MIT license
  

**Official resources for icon and color:** [File:MIT logo.svg - Wikimedia Commons](https://commons.wikimedia.org/wiki/File:MIT_logo.svg)

**Comment by runxel** [comment] 2020-09-22 21:57
Duplicate of #3541.

**Closed by runxel** 2020-09-22 21:57 UTC
Labels: duplicate, new icon
