### ISSUE TITLE
Pest icon

### ISSUE THREAD

**Issue by natanaugusto** [simple-icons/simple-icons#10409] opened 2024-02-07 14:24 UTC
### Brand Name

Pest

### Website

https://pestphp.com/

### Popularity Metric

https://pestphp.com/www/assets/logo.svg

### Official Resources for Icon and Color

https://pestphp.com/www/assets/logo.svg

### Additional Comments

I belive the icon is just this one I send

**Comment by service-paradis** [comment] 2024-02-07 16:13
Duplicate of #7051

**Closed by service-paradis** 2024-02-07 16:13 UTC
Labels: new icon
