### ISSUE TITLE
Request: Zitadel

### ISSUE THREAD

**Issue by Velka-DEV** [simple-icons/simple-icons#12111] opened 2024-11-04 14:13 UTC
### Brand Name

Zitadel

### Website

https://zitadel.com

### Popularity Metric

The Similarweb rank is #474,942 https://similarweb.com/website/zitadel.org

### Official Resources for Icon and Color

No official mediakit proposed.

**Comment by uncenter** [comment] 2024-12-05 02:59
Duplicate of #11808.

**Closed by uncenter** 2024-12-05 02:59 UTC
Labels: new icon
