### ISSUE TITLE
Request: RxJS

### ISSUE THREAD

**Issue by Ninad99** [simple-icons/simple-icons#3263] opened 2020-06-26 10:29 UTC
**Name:** RxJS
**Website:** https://rxjs.dev/
**Alexa rank:** 260,308

**Official resources for icon and color:** This is the [logo](https://rxjs.dev/assets/images/logos/logo.png) used in the website.

**Comment by PeterShaggyNoble** [comment] 2020-06-26 10:49
Thanks for the request, @Ninad99 

There's a monochrome SVG in one of their GitHub repos that we could use: https://github.com/ReactiveX/rxjs/blob/master/resources/CI-CD/logo/svg/RxJs_Logo_Black.svg

Not sure on the colour, black seems pretty dominant on their site (but that may be temporary while showing their support for BLM) but I'd actually lean towards the pink: `#d81b60`.

Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by Ninad99** [comment] 2020-06-26 12:28
Sure!

> Thanks for the request, @Ninad99
> 
> There's a monochrome SVG in one of their GitHub repos that we could use: https://github.com/ReactiveX/rxjs/blob/master/resources/CI-CD/logo/svg/RxJs_Logo_Black.svg
> 
> Not sure on the colour, black seems pretty dominant on their site (but that may be temporary while showing their support for BLM) but I'd actually lean towards the pink: `#d81b60`.
> 
> Would you like to have a look through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) and give this a try yourself?

**Comment by NovaGL** [comment] 2020-08-05 09:52
Duplicate of #3354 

If you think this is in error. Please reopen the issue

**Closed by NovaGL** 2020-08-05 09:52 UTC
Labels: good first issue, new icon
