### ISSUE TITLE
Request: Navidrome

### ISSUE THREAD

**Issue by epdntm** [simple-icons/simple-icons#11528] opened 2024-07-25 06:34 UTC
### Brand Name

Navidrome

### Website

https://www.navidrome.org/

### Popularity Metric

The similarweb rank is 275,026. https://www.similarweb.com/website/navidrome.org/

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment] 2024-08-20 12:00
Duplicate of #7818. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-08-20 12:00 UTC
Labels: new icon
