### ISSUE TITLE
Inertiajs

### ISSUE THREAD

**Issue by ConrDev** [simple-icons/simple-icons#8300] opened 2023-02-01 07:48 UTC
### Brand Name

Inertia

### Website

https://inertiajs.com/

### Popularity Metric

The Inertiajs global rank is # 273,107. see https://www.similarweb.com/website/inertiajs.com/#overview

### Official Resources for Icon and Color

svg: https://github.com/inertiajs/inertiajs.com/blob/2569b83e0395ed894b78eec9dbb9a76f941dbb92/resources/js/Components/Layout.jsx#L77-L81

Inertia ">>" logo:
```svg
<svg viewBox="0 0 61.9 34.4">
    <path d="M 230.633 150.592 L 212.833 150.592 L 230.033 167.792 L 212.833 184.992 L 230.633 184.992 L 247.833 167.792 L 230.633 150.592 Z" />
    <path d="M 257.533 150.592 L 239.733 150.592 L 256.933 167.792 L 239.733 184.992 L 257.533 184.992 L 274.733 167.792 L 257.533 150.592 Z" />
</svg>
```

### Additional Comments

An option would be to remove the inertia text and keep the ">>"

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-02-01 21:27
Duplicate of #7371

**Closed by service-paradis** 2023-02-01 21:27 UTC
Labels: new icon
