### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by CaedenPH** [simple-icons/simple-icons#7722] opened 2022-08-31 13:41 UTC
### Brand Name

Black

### Website

https://github.com/psf/black

### Popularity Metric

29k github stars

### Official Resources for Icon and Color

https://raw.githubusercontent.com/psf/black/main/docs/_static/logo2-readme.png

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-07-24 11:47
Duplicate of #4928

**Closed by adamrusted** 2023-07-24 11:47 UTC
Labels: new icon
