### ISSUE TITLE
Ubiquiti icon outdated

### ISSUE THREAD

**Issue by piotrstanowicz** [simple-icons/simple-icons#8920] opened 2023-07-01 09:39 UTC
### Brand Name

Ubiquiti

### Official Resources for Icon and Color

https://authenticator.2stable.com/assets/img/2fa-services/Icons/ui.com.svg

### Contributing

No

**Comment by adamrusted** [comment] 2023-07-02 10:10
There's an SVG icon in the header of [the site](https://www.ui.com/) that we can use. Would you want to contribute this @piotrstanowicz?

**Comment by service-paradis** [comment] 2023-07-04 11:59
Duplicate of #5667

**Closed by service-paradis** 2023-07-04 11:59 UTC
Labels: icon outdated
