### ISSUE TITLE
Request: Filament

### ISSUE THREAD

**Issue by dushmanta05** [simple-icons/simple-icons#10935] opened 2024-05-11 06:51 UTC
### Brand Name

Filament

### Website

https://filamentphp.com/

### Popularity Metric

The similar web rank is 80,339. See https://www.similarweb.com/website/filamentphp.com/#overview

### Official Resources for Icon and Color

PNG Icon: https://filamentphp.com/favicon/apple-touch-icon.png
GitHub profile image: https://avatars.githubusercontent.com/u/64450473

### Additional Comments

Currently, I'm searching to see if there's an SVG, and I believe we can keep the SVG in the same style as PNG image above instead of the full name (like in GitHub image)

**Comment by uncenter** [comment] 2024-06-03 13:27
Duplicate of #10344.

**Closed by uncenter** 2024-06-03 13:27 UTC
Labels: new icon
