### ISSUE TITLE
Icon request for matplotlib

### ISSUE THREAD

**Issue by rishabh1323** [simple-icons/simple-icons#5606] opened 2021-05-04 15:42 UTC
**Brand Name:** matplotlib
**Website:** https://matplotlib.org/
**Alexa rank:** 13,871
  

**Official resources for icon and color:** https://matplotlib.org/

**Comment by adamrusted** [comment] 2021-05-04 16:31
Duplicate of #3492

**Closed** 2021-05-04 16:32 UTC
Labels: new icon, duplicate

**Comment by rishabh1323** [comment] 2021-05-04 16:53
thanks
