### ISSUE TITLE
Request: Mullvad VPN

### ISSUE THREAD

**Issue by DerBraky** [simple-icons/simple-icons#11621] opened 2024-08-13 16:36 UTC
### Brand Name

Mullvad VPN

### Website

https://mullvad.net/

### Popularity Metric

- Similarweb Global Rank: [55,431](https://www.similarweb.com/website/mullvad.net)

### Official Resources for Icon and Color

SVG: 
- https://github.com/mullvad/mullvadvpn-app/blob/main/graphics/icon-android-mono.svg
- https://github.com/mullvad/mullvadvpn-app/blob/main/graphics/icon-shaved.svg
- https://mullvad.net/press/MullvadVPN_logo_Round_RGB_BW_positive.svg

Color: `#294d73`, first color in press kit

### Additional Comments

Press kit available: https://mullvad.net/press

**Comment by service-paradis** [comment] 2024-08-13 18:42
Duplicate of #8126

**Closed by service-paradis** 2024-08-13 18:42 UTC
Labels: new icon
