### ISSUE TITLE
Request: YII PHP Framework

### ISSUE THREAD

**Issue by rzlco666** [simple-icons/simple-icons#7143] opened 2022-02-12 14:43 UTC
### Brand Name

Yii PHP Framework

### Website

https://www.yiiframework.com/

### Popularity Metric

The Alexa site rank is 23,493. See https://www.alexa.com/siteinfo/yiiframework.com

### Official Resources for Icon and Color

svg: https://www.yiiframework.com/image/design/logo/yii3_sign.svg
color: `#83C933` , `#F18A2A` , `#40B3D8`

### Additional Comments

Yii is an open source, object-oriented, component-based MVC PHP web application framework. Yii also is the fastest PHP framework

### Contributing

Yes

**Comment by rzlco666** [comment] 2022-02-12 14:53
[Yii3 Sign Full Color](https://www.yiiframework.com/image/design/logo/yii3_sign.svg)
[Yii3 Sign White Color Only](https://www.yiiframework.com/image/design/logo/yii3_sign_white.svg)

**Comment by LitoMore** [comment] 2022-02-13 14:16
The brand name should be `Yii`.

**Comment by sachinraja** [comment] 2022-02-13 20:59
duplicate of #6832

**Closed by sachinraja** 2022-02-13 20:59 UTC
Labels: new icon
