### ISSUE TITLE
Request: Bubble.io

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12025] opened 2024-10-16 09:14 UTC
### Brand Name

Bubble.io

### Website

https://bubble.io/

### Popularity Metric

Global Rank - 13265

### Official Resources for Icon and Color

https://bubble.io/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment] 2024-10-16 10:03
Duplicate of #10355. Please check previous issues before submitting any others.

**Closed by adamrusted** 2024-10-16 10:03 UTC
Labels: new icon
