### ISSUE TITLE
Request: Numpy

### ISSUE THREAD

**Issue by danielmarostica** [simple-icons/simple-icons#3408] opened 2020-08-03 00:58 UTC
**Name:** Numpy
**Website:** https://numpy.org/
**Alexa rank:** 14502

**Official resources for icon and color:**
https://github.com/numpy/numpy/blob/master/branding/logo/logomark/numpylogoicon.svg

**Comment by NovaGL** [comment] 2020-08-03 10:44
Thanks for the request. Do you think you would be up to trying to do a pull request?

Please see the [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) if you are upto it.

**Comment by ericcornelissen** [comment] 2020-09-17 14:51
Seems #3529 was a duplicate of this :sweat_smile: Anyway, with #3531 merge the NumPy icon will be available with the next release :smiley:

**Closed by ericcornelissen** 2020-09-17 14:51 UTC
Labels: good first issue, new icon
