### ISSUE TITLE
FlightRadar24

### ISSUE THREAD

**Issue by Adhithya8055** [simple-icons/simple-icons#9159] opened 2023-07-30 07:56 UTC
### Brand Name

FlightRadar24

### Website

https://www.flightradar24.com/

### Popularity Metric

Global Ranking: 460   https://www.similarweb.com/website/flightradar24.com/#overview

### Official Resources for Icon and Color

-

### Additional Comments

-

### Contributing

No

**Comment by service-paradis** [comment] 2023-07-31 13:58
Duplicate of #8337

**Closed by service-paradis** 2023-07-31 13:58 UTC
Labels: new icon
