### ISSUE TITLE
WHO 

### ISSUE THREAD

**Issue by assintates** [simple-icons/simple-icons#2817] opened 2020-03-20 09:01 UTC
Name: WHO(World Health Organization)
Website: https://www.who.int
Offical icon: https://seeklogo.net/wp-content/uploads/2014/11/download-who-logo-png.png

**Comment by ericcornelissen** [comment] 2020-03-20 09:03
Thanks for the request @assintates, however its a duplicate of #2793 which as been resolved with  #2804. The icon will be available in the next release :slightly_smiling_face:

**Closed by ericcornelissen** 2020-03-20 09:03 UTC
Labels: new icon
