### ISSUE TITLE
Wells Fargo

### ISSUE THREAD

**Issue by Aman-0604** [simple-icons/simple-icons#9833] opened 2023-11-08 06:41 UTC
### Brand Name

Wells Fargo

### Website

https://www.wellsfargo.com/

### Popularity Metric

The Similarweb rank is 189. See https://www.similarweb.com/website/wellsfargo.com/#overview

### Official Resources for Icon and Color

https://www17.wellsfargomedia.com/assets/images/rwd/favicon_48x48.png

**Comment by adamrusted** [comment] 2023-11-08 06:48
Duplicate of #6338

**Closed** 2023-11-08 06:49 UTC
Labels: new icon, duplicate
