### ISSUE TITLE
Request: ESPN

### ISSUE THREAD

**Issue by ILoveHDDark** [simple-icons/simple-icons#8451] opened 2023-03-23 06:14 UTC
### Brand Name

ESPN

### Website

https://espn.com

### Popularity Metric

The Similarweb rank is 104. See https://www.similarweb.com/website/espn.com

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/2/2f/ESPN_wordmark.svg
color: `#E62031`  taken from the site header

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-03-24 14:52
Duplicate of #5931

**Closed by service-paradis** 2023-03-24 14:52 UTC
Labels: new icon
