### ISSUE TITLE
Request: gRPC

### ISSUE THREAD

**Issue by KritAsawaniramol** [simple-icons/simple-icons#12086] opened 2024-10-24 09:43 UTC
### Brand Name

gRPC

### Website

https://grpc.io/

### Popularity Metric

The similarweb rank is 161,990. see: https://www.similarweb.com/website/grpc.io/

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2024-10-24 11:34
Duplicate of #6275

**Closed by service-paradis** 2024-10-24 11:34 UTC
Labels: new icon
