### ISSUE TITLE
Request: LangChain

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11080] opened 2024-06-01 07:48 UTC
### Brand Name

LangChain

### Website

https://www.langchain.com/

### Popularity Metric

LangChain is a framework for developing applications powered by LLMs (Large Language Models). It is ranked 17,163 in SimilarWeb.

### Official Resources for Icon and Color

svg & png: https://seeklogo.com/vector-logo/528369/langchain
png: https://commons.wikimedia.org/wiki/File:LangChain_logo.png

### Additional Comments

LangChain is a popular framework among AI developers for integrating LLMs like ChatGPT, Llama, Mistral, Gemini etc with various external data sources to create really powerful applications tailored for a specific use case.

**Comment by uncenter** [comment] 2024-06-01 16:07
SVG available in the header.

**Comment by ancilcleetus** [comment] 2024-06-01 17:26
![LangChain-logo](https://github.com/simple-icons/simple-icons/assets/25684256/d1a1c8c0-1265-4763-8a15-b2a74689ae1c)

@uncenter Above LangChain Logo SVG created from markup copied from the website header.

**Comment by uncenter** [comment] 2024-06-03 13:54
Duplicate of #9482.

**Closed by uncenter** 2024-06-03 13:54 UTC
Labels: new icon
