### ISSUE TITLE
Hello Fresh logo outdated

### ISSUE THREAD

**Issue by EstLeaf** [simple-icons/simple-icons#8067] opened 2022-11-27 18:56 UTC
### Brand Name

Hello Fresh

### Official Resources for Icon and Color

svg: https://logovtor.com/download-logo-vector-1694/# (Just unzip the file) Colors: IDK

### Additional Comments

Green, white and black colors

### Contributing

No

**Comment by adamrusted** [comment] 2023-07-02 09:51
Duplicate of #5559

**Closed by adamrusted** 2023-07-02 09:51 UTC
Labels: icon outdated, duplicate
