### ISSUE TITLE
Request: PrimeFaces

### ISSUE THREAD

**Issue by abhijeetkharkar** [simple-icons/simple-icons#7257] opened 2022-03-24 12:12 UTC
### Brand Name

PrimeFaces

### Website

https://www.primefaces.org/

### Popularity Metric

The Global Rank is 48,234. Check out https://www.similarweb.com/website/primefaces.org/#overview

### Official Resources for Icon and Color

None

### Contributing

No

**Comment by PeterShaggyNoble** [comment] 2023-11-27 20:46
Duplicate of #5603

**Closed by PeterShaggyNoble** 2023-11-27 20:46 UTC
Labels: new icon
