### ISSUE TITLE
Request: add icon for Transmission torrent client; OSS project

### ISSUE THREAD

**Issue by ctalaveraw** [simple-icons/simple-icons#7821] opened 2022-09-19 03:37 UTC
### Brand Name

Transmission

### Website

https://transmissionbt.com/

### Popularity Metric

7.3K stars on GitHub:

https://github.com/transmission/transmission

### Official Resources for Icon and Color

logo:

https://transmissionbt.com/assets/images/Transmission_icon.png

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-09-19 13:52
I'll mark this as pending until the discussion about Torrent clients in https://github.com/simple-icons/simple-icons/issues/6246 has concluded.

**Comment by PeterShaggyNoble** [comment] 2023-11-27 23:10
Duplicate of #7490

**Closed by PeterShaggyNoble** 2023-11-27 23:10 UTC
Labels: new icon, pending
