### ISSUE TITLE
Request: FilamentPHP Icon

### ISSUE THREAD

**Issue by davidtriminio** [simple-icons/simple-icons#11760] opened 2024-09-12 17:58 UTC
### Brand Name

Filament PHP

### Website

https://filamentphp.com

### Popularity Metric

The Similarweb rank is #76,720. See https://www.similarweb.com/website/filamentphp.com/ for details.

### Official Resources for Icon and Color

- SVG: 
![logo_filament](https://github.com/user-attachments/assets/433b899d-ace2-4828-973c-074a1b4c4803)
- Color: #fdae4b

### Additional Comments

- Este icono fue realizado por mí, ya que la web no provee un icono oficial para descargar.

**Comment by uncenter** [comment] 2024-09-12 19:23
Duplicate of #10344. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-09-12 19:23 UTC
Labels: new icon
