### ISSUE TITLE
Adding Hackernews Icon

### ISSUE THREAD

**Issue by KarthikNayak024** [simple-icons/simple-icons#3472] opened 2020-08-20 15:45 UTC
**Name:** Hackernews
**Website:** [Hackernews](https://news.ycombinator.com/)
**Alexa rank:** [Rank](https://www.alexa.com/siteinfo/ycombinator.com)
  

**Official resources for icon and color:**

**Comment by NovaGL** [comment] 2020-08-21 03:25
Duplicate of #306

Please see Y Combinator which is already available.

**Closed by NovaGL** 2020-08-21 03:25 UTC
Labels: new icon
