### ISSUE TITLE
MATLAB

### ISSUE THREAD

**Issue by gspandhana** [simple-icons/simple-icons#9416] opened 2023-08-26 08:39 UTC
### Brand Name

MATLAB

### Website

https://in.mathworks.com/

### Popularity Metric

The Similarweb rank for mathworks.com is 7526. See https://www.similarweb.com/website/mathworks.com/#overview 

### Official Resources for Icon and Color

![matlab-seeklogo com](https://github.com/simple-icons/simple-icons/assets/12433565/54bc1ced-3a8d-4f1c-a2dd-59037001e4ac)

### Additional Comments

Yes, there are other versions of this logo. https://commons.wikimedia.org/wiki/File:Matlab_Logo.png 

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-08-26 17:16
Duplicate of #5835 (and many others)

Please take a look at https://github.com/simple-icons/simple-icons/issues/5835#issuecomment-853626958

**Closed by adamrusted** 2023-08-26 17:16 UTC
Labels: new icon
