### ISSUE TITLE
Sololearn

### ISSUE THREAD

**Issue by BeegCat** [simple-icons/simple-icons#5580] opened 2021-05-01 03:27 UTC
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment] 2021-05-01 08:27
@BeegCat thanks for your request.

Can you please provide the needed information?

Brand Name:
Website:
Alexa rank:

Official resources for icon and color:

Otherwise your request won't be valid.

**Comment by PeterShaggyNoble** [comment] 2021-05-05 11:21
Closing as a duplicate of #3566, which was added in #4624. If that _isn't_ the icon you're looking for then please provide the information requested above and we'll reopen this issue.

![](https://user-images.githubusercontent.com/15157491/117133568-55262a00-ad9c-11eb-983c-679426f3435a.png)

**Closed by PeterShaggyNoble** 2021-05-05 11:21 UTC
Labels: awaiting reply, new icon
