### ISSUE TITLE
Seaborn

### ISSUE THREAD

**Issue by shubamsumbria** [simple-icons/simple-icons#7070] opened 2022-01-16 11:15 UTC
### Brand Name

pydata seaborn

### Website

https://seaborn.pydata.org/

### Popularity Metric

None

### Official Resources for Icon and Color

None

### Additional Comments

None

### Contributing

No

**Comment by sachinraja** [comment] 2022-01-19 03:39
duplicate of #6324

**Closed by sachinraja** 2022-01-19 03:39 UTC
Labels: new icon
