### ISSUE TITLE
Burpsuite

### ISSUE THREAD

**Issue by darkoid** [simple-icons/simple-icons#9042] opened 2023-07-18 09:19 UTC
### Brand Name

burpsuite

### Website

https://portswigger.net/burp

### Popularity Metric

Burpsuite is a product of Portswigger its Similarweb rank is 46,394. See https://www.similarweb.com/website/portswigger.net/

### Official Resources for Icon and Color

![burpsuite-security-software-svgrepo-com](https://github.com/simple-icons/simple-icons/assets/81341961/4f6fdfde-3c62-417c-ac2a-24a4b59245a5)

this is also the logo of portswigger website but the website has slightly different logo, I couldn't find any svg file for application logo but an image is pasted below

![image](https://github.com/simple-icons/simple-icons/assets/81341961/173fbea9-cc76-41ee-b470-29507b95c4da)

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-07-21 14:36
Duplicate of #7075

**Closed by service-paradis** 2023-07-21 14:36 UTC
Labels: new icon
