### ISSUE TITLE
Please add icon Hapi.JS

### ISSUE THREAD

**Issue by afustrator** [simple-icons/simple-icons#8387] opened 2023-02-25 14:45 UTC
### Brand Name

Hapi

### Website

https://hapi.dev/

### Popularity Metric

The SimilarWeb rank is 976.021. See this https://www.similarweb.com/website/hapi.dev
Github Stars is 14.2k stars. See this https://github.com/hapijs/hapi

### Official Resources for Icon and Color

https://github.com/hapijs/hapi.dev/blob/master/static/icon.png
color: `#212121`, imitate from the head of the website, hopefully, the same,

### Contributing

No

**Comment by service-paradis** [comment] 2023-02-27 13:47
Duplicate of #7463

**Closed by service-paradis** 2023-02-27 13:47 UTC
Labels: new icon
