### ISSUE TITLE
Lattes

### ISSUE THREAD

**Issue by luizimgiolo** [simple-icons/simple-icons#10348] opened 2024-01-23 22:03 UTC
### Brand Name

Lattes Platform

### Website

https://lattes.cnpq.br/

### Popularity Metric

It does not use analytics.
But it is the main official academic resume platform in Brazil

### Official Resources for Icon and Color

![lattes](https://github.com/simple-icons/simple-icons/assets/37443004/98dfbbcb-3dea-48c0-8506-567e3f45acc7)

**Comment by PeterShaggyNoble** [comment] 2024-01-23 22:20
Duplicate of #3511

**Closed** 2024-01-23 22:19 UTC
Labels: new icon
