### ISSUE TITLE
Request: Browserstack

### ISSUE THREAD

**Issue by vanessafsoares** [simple-icons/simple-icons#4964] opened 2021-02-10 15:17 UTC
**Brand Name:** Browserstack
**Website:** https://www.browserstack.com/
**Alexa rank:** [8.577](https://www.alexa.com/siteinfo/browserstack.com)

**Official resources for icon and color:**
https://3fxtqy18kygf3on3bu39kh93-wpengine.netdna-ssl.com/wp-content/uploads/2019/11/browserstack.svg

**Comment by PeterShaggyNoble** [comment] 2021-02-10 15:19
Duplicate of #4668

**Closed by PeterShaggyNoble** 2021-02-10 15:19 UTC
Labels: duplicate, new icon
