### ISSUE TITLE
DBeaver Icon

### ISSUE THREAD

**Issue by HieloElemental** [simple-icons/simple-icons#8834] opened 2023-06-19 02:51 UTC
### Brand Name

DBeaver

### Website

https://dbeaver.io/

### Popularity Metric

The Similarweb rank is 152,167

### Official Resources for Icon and Color

https://dbeaver.io/wp-content/uploads/2016/07/beaver_icon_32x32.png
![image](https://github.com/simple-icons/simple-icons/assets/136840526/daddc94b-bed7-4c01-a534-c098781b2eb0)
https://dbeaver.io/wp-content/uploads/2015/09/beaver-head.png
![image](https://github.com/simple-icons/simple-icons/assets/136840526/617c0c1f-51b1-47d8-bd26-fc747da9d41f)

### Additional Comments

There is a variant of this icon, wich is the whole animal

### Contributing

Yes

**Comment by blakmagjick** [comment] 2023-06-19 23:13
I'll work on this one. :)

**Comment by service-paradis** [comment] 2023-06-21 16:07
Duplicate of #8217

**Closed by service-paradis** 2023-06-21 16:07 UTC
Labels: new icon
