### ISSUE TITLE
Hardhat

### ISSUE THREAD

**Issue by alexisljn** [simple-icons/simple-icons#8140] opened 2022-12-15 16:07 UTC
### Brand Name

Hardhat

### Website

https://hardhat.org/

### Popularity Metric

The Similarweb rank is 256,200 and the repository has 5k stars (https://github.com/NomicFoundation/hardhat) and it's the best Ethereum development environment

### Official Resources for Icon and Color

svg: https://hardhat.org/_next/static/media/hardhat-logo-dark.484eb916.svg
color : #181A1F (from background-color)

### Contributing

No

**Comment by service-paradis** [comment] 2023-04-21 17:24
Duplicate of #7026

**Closed by service-paradis** 2023-04-21 17:24 UTC
Labels: new icon
