### ISSUE TITLE
Matplotlib Icon

### ISSUE THREAD

**Issue by TruongNhanNguyen** [simple-icons/simple-icons#6421] opened 2021-08-28 03:40 UTC
I wonder why i can't find icon of Matplotlib.

**Comment by sachinraja** [comment] 2021-08-28 05:01
Thank you for your request, but there are required information needed when asking for an icon. Please add the following:

Brand Name
Website
Alexa Rank
Official Resources for Icon and Color (Media kits, brand guidelines, SVG files, etc. You can set this to "None" if you are unable to find any resources.)

Also please use the correct form:
https://github.com/simple-icons/simple-icons/issues/new?assignees=&labels=new+icon&template=icon_request.yml&title=Request%3A+

**Comment by gizmecano** [comment] 2021-08-28 05:05
Probable duplicate of #3410, #5321 a,d #5606.

**Comment by jorgeamadosoria** [comment] 2021-08-28 05:43
> I wonder why i can't find icon of Matplotlib.

Well, isn't this a popular brand icon! :)
unfortunately the discussion in #3410 appears to show that there are legal questions still unanswered on their side, hence why this is still pending @TruongNhanNguyen if you want to follow up on this issue if and when it is resolved, I would suggest you follow the discussion in #3410. The interest is there and the icon certainly qualifies for inclusion, we just need the greenlight on their side to start working on it!

In the mean time, I will close this issue as duplicated of #3410, per @gizmecano's comment.

**Closed by jorgeamadosoria** 2021-08-28 05:43 UTC
Labels: new icon, duplicate
