### ISSUE TITLE
Devfolio

### ISSUE THREAD

**Issue by Anmol-Baranwal** [simple-icons/simple-icons#7698] opened 2022-08-24 16:15 UTC
### Brand Name

Devfolio

### Website

https://www.similarweb.com/website/devfolio.co/#overview

### Popularity Metric

Global Rank: 316,012

### Official Resources for Icon and Color

svg: https://devfolio.co/hackathons
color: `#3770FF`, from website branding

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-08-25 00:51
Duplicate of #6354

**Closed by service-paradis** 2022-08-25 00:51 UTC
Labels: new icon
