### ISSUE TITLE
ServiceNow icon

### ISSUE THREAD

**Issue by jaepetto** [simple-icons/simple-icons#9599] opened 2023-09-20 12:44 UTC
### Brand Name

Service Now

### Website

https://www.servicenow.com/

### Popularity Metric

Similarweb global ranking 16,091

### Official Resources for Icon and Color

https://www.servicenow.com/content/dam/servicenow-assets/public/en-us/images/og-images/favicon.ico

### Contributing

No

**Comment by service-paradis** [comment] 2023-09-20 18:34
Duplicate of #8506

**Closed by service-paradis** 2023-09-20 18:34 UTC
Labels: new icon
