### ISSUE TITLE
Request: MATLAB Icon

### ISSUE THREAD

**Issue by shubhadeepmandal394** [simple-icons/simple-icons#5427] opened 2021-04-09 09:22 UTC
**Brand Name:** MATLAB
**Website:** https://www.mathworks.com/
**Alexa rank:** 1,862
  

**Official resources for icon and color:** 
Logo can be found here https://en.wikipedia.org/wiki/File:Matlab_Logo.png
To create one in Matlab itself https://in.mathworks.com/help/matlab/visualize/creating-the-matlab-logo.html

**Comment by adamrusted** [comment] 2021-04-09 09:24
Duplicate of https://github.com/simple-icons/simple-icons/pull/1233 - MATLAB is already in the project, and under discussion for removal due to the terms being quite strict on the colours involved.

**Closed by adamrusted** 2021-04-09 09:24 UTC
Labels: new icon
