### ISSUE TITLE
Request: LEGO icon

### ISSUE THREAD

**Issue by guibranco** [simple-icons/simple-icons#5823] opened 2021-06-01 07:18 UTC
**Brand Name:** Lego
**Website:** https://lego.com/
**Alexa rank:** [2,999](https://www.alexa.com/siteinfo/lego.com)

**Official resources for icon and color:**
 
  -  [Official logo file (JPG)](https://www.lego.com/cdn/cs/set/assets/blt445eec351be85ac6/Lego-logo.jpg?format=jpg&quality=80&height=256&dpr=1)
  - [Non-official (Wikipedia/Wikimedia) (SVG)](https://upload.wikimedia.org/wikipedia/commons/2/24/LEGO_logo.svg)
  - [Color schema](https://www.schemecolor.com/lego.php)

**Comment by adamrusted** [comment] 2021-06-01 07:35
Duplicate of #3674. In that issue, we've discussed that we can't add LEGO due to their trademark terms.

**Closed by adamrusted** 2021-06-01 07:35 UTC
Labels: new icon
