### ISSUE TITLE
Add Tailscale Icon

### ISSUE THREAD

**Issue by Intron014** [simple-icons/simple-icons#9853] opened 2023-11-13 16:19 UTC
### Brand Name

Tailscale

### Website

https://tailscale.com/

### Popularity Metric

The similarweb rank is 38,523, see https://www.similarweb.com/website/tailscale.com

### Official Resources for Icon and Color

https://brandfetch.com/tailscale.com

**Comment by PeterShaggyNoble** [comment] 2023-12-08 00:36
Duplicate of #8346

**Closed by PeterShaggyNoble** 2023-12-08 00:36 UTC
Labels: new icon
