### ISSUE TITLE
GameJolt Icon?!

### ISSUE THREAD

**Issue by antv199** [simple-icons/simple-icons#4750] opened 2021-01-13 10:01 UTC
I'm not sure if this exists already (I didn't find it on the website), but there's an icon for Itch.io, already. Why not for GameJolt? Are there legal restrictions around it?

**Comment by antv199** [comment] 2021-01-13 10:02
Name: GameJolt
Website: https://gamejolt.com
Alexa Ranking: https://www.alexa.com/siteinfo/gamejolt.com

**Comment by adamrusted** [comment] 2021-01-13 10:04
Hi @antv199, this is a duplicate of #3461 closed this morning by #4742. Icon should be available on the website and NPM package from Sunday. Hope that helps!

**Comment by antv199** [comment] 2021-01-13 10:05
> Hi @antv199, this is a duplicate of #3461 closed this morning by #4742. Icon should be available on the website and NPM package from Sunday. Hope that helps!

oh ok. thanks and sorry for any hassle caused

**Closed** 2021-01-13 10:04 UTC
Labels: new icon

**Comment by adamrusted** [comment] 2021-01-13 10:06
> oh ok. thanks and sorry for any hassle caused

No worries! I realise the issue and PR were probably already closed, and therefore not showing when you looked to request it 😅
