### ISSUE TITLE
Icon Request: MermaidJS

### ISSUE THREAD

**Issue by HariSekhon** [simple-icons/simple-icons#8610] opened 2023-05-04 00:31 UTC
### Brand Name

MermaidJS

### Website

https://github.com/mermaid-js/mermaid

### Popularity Metric

57,000 GitHub Stars

### Official Resources for Icon and Color

https://raw.githubusercontent.com/mermaid-js/mermaid/develop/docs/public/favicon.svg

### Contributing

No

**Comment by service-paradis** [comment] 2023-05-11 12:53
Duplicate of #8186

**Closed by service-paradis** 2023-05-11 12:53 UTC
Labels: new icon
