### ISSUE TITLE
Google Docs

### ISSUE THREAD

**Issue by ohnoitsnoah** [simple-icons/simple-icons#8540] opened 2023-04-13 15:17 UTC
### Brand Name

Google Docs

### Website

https://www.google.com/docs/about/

### Popularity Metric

There is no rank, however there is 6.0B visits :).

### Official Resources for Icon and Color

https://en.wikipedia.org/wiki/File:Google_Docs_2020_Logo.svg
#4688F2

### Contributing

No

**Comment by service-paradis** [comment] 2023-04-21 17:25
Duplicate of #5155

**Closed by service-paradis** 2023-04-21 17:25 UTC
Labels: new icon
