### ISSUE TITLE
Request: Gradio

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11415] opened 2024-07-06 09:22 UTC
### Brand Name

Gradio

### Website

https://www.gradio.app/

### Popularity Metric

Gradio is an open-source Python package that allows you to quickly build a demo or web application for your machine learning model, API, or any arbitrary Python function. Creating a Gradio interface only requires adding a couple lines of code to your project. Gradio can be embedded in Python notebooks or presented as a webpage. You can then share a link to your demo or web application in just a few seconds using Gradio's built-in sharing features. No JavaScript, CSS, or web hosting experience needed!

It is ranked 102,720 in SimilarWeb. Its [GitHub repo](https://github.com/gradio-app/gradio) has 30.7k stars. The star history is on a consistently upward trajectory.

### Official Resources for Icon and Color

svg: https://www.gradio.app/brand

gradio-icon-white-24x24.svg created as per Contribution Guidelines is below:

![gradio-icon-white-24x24.svg](https://github.com/simple-icons/simple-icons/assets/25684256/8a1b8919-80a2-4c4d-bbac-9ab8dc251ca4)

**Comment by uncenter** [comment] 2024-12-05 03:16
Duplicate of #9481.

**Closed by uncenter** 2024-12-05 03:16 UTC
Labels: new icon
