### ISSUE TITLE
Request: Matlab logo badge missing

### ISSUE THREAD

**Issue by RezuwanHassan262** [simple-icons/simple-icons#11714] opened 2024-08-31 06:52 UTC
### Brand Name

Matlab

### Website

https://www.mathworks.com/products/matlab.html

### Popularity Metric

need this logo

### Official Resources for Icon and Color

need this logo, make it defau
![Matlab_Logo](https://github.com/user-attachments/assets/b86d42f5-4059-4d91-88ea-ff23bcb45f85)
lt I guess

**Comment by Dip-Gyawali** [comment] 2024-08-31 14:32
@RezuwanHassan262  can you give me details where this badge is missing a screen shot might help a lot

**Comment by uncenter** [comment] 2024-08-31 14:35
Duplicate of https://github.com/simple-icons/simple-icons/issues/5835 and about 20 others. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-08-31 14:35 UTC
Labels: new icon

**Comment by RezuwanHassan262** [comment] 2024-09-01 07:16
@Dip-Gyawali Dip-Gyawali it's missing from here, can't find it!

https://badges.pages.dev/
