### ISSUE TITLE
Request: Snowpack

### ISSUE THREAD

**Issue by TropicalRaisel** [simple-icons/simple-icons#6521] opened 2021-09-14 23:13 UTC
### Brand Name

Snowpack

### Website

https://www.snowpack.dev/

### Popularity Metric

19.2k stars on GitHub: https://github.com/snowpackjs/snowpack/stargazers

### SVG from website
```html
<svg class="logo-icon astro-ahFEmudE" viewBox="0 0 640 512" version="1.1" xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <g transform="translate(-1.000000, 0.000000)" fill-rule="nonzero" class="astro-ahFEmudE">
    <path
      d="M635.92,462.7 L347.92,14.7 C342.03,5.54 331.89,0 321,0 C310.11,0 299.97,5.54 294.08,14.7 L6.08,462.7 C-0.250773249,472.547007 -0.699487627,485.064987 4.91,495.34 C10.522069,505.612419 21.2945349,512 33,512 L609,512 C620.71,512 631.48,505.61 637.09,495.33 C642.699457,485.058495 642.250708,472.543372 635.92,462.7 Z M321,91.18 L406.39,224 L321,224 L257,288 L218.94,249.94 L321,91.18 Z"
      id="Shape" class="astro-ahFEmudE"></path>
  </g>
</svg><span class="logo-type astro-ahFEmudE">Snowpack</span>
```

### Color
`#2e5e82`

### Contributing

No

**Comment by service-paradis** [comment] 2021-09-14 23:15
Duplicate of #6072

**Closed by service-paradis** 2021-09-14 23:15 UTC
Labels: new icon
