### ISSUE TITLE
Zeit is now Vercel - Vercel icon

### ISSUE THREAD

**Issue by bzerangue** [simple-icons/simple-icons#2972] opened 2020-04-22 20:09 UTC
**Name: Vercel**
**Website: https://vercel.com**
**Official resources for icon and color:**
  
https://vercel.com/blog/zeit-is-now-vercel  
https://vercel.com/design

**Comment by ericcornelissen** [comment] 2020-04-22 20:39
Thanks for the report @bzerangue, it seems to be a duplicate of #2964 so I will close this :slightly_smiling_face: : 

Just for clarity, as this concerns a name change, we have scheduled it for [our next major release](https://github.com/simple-icons/simple-icons/milestone/2). If you want the icon to be available as Vercel before that, let us know here and we will consider adding it before then :wink:

**Closed by ericcornelissen** 2020-04-22 20:39 UTC
Labels: new icon
