### ISSUE TITLE
Request: Center for Open Science

### ISSUE THREAD

**Issue by roaldarbol** [simple-icons/simple-icons#6811] opened 2021-11-01 20:50 UTC
### Brand Name

Center for Open Science

### Website

cos.io and osf.io

### Popularity Metric

Alexa rank: 32,136

### Official Resources for Icon and Color

There's a folder of png files at https://osf.io/7cewn/. The blue colour appears to be their main colour. 

### Additional Comments

The Center for Open Science runs the Open Science Framework, essentially a Github for research projects. It has become an increasingly important tool for many researchers (as also witnessed by their Alexa ranking for osf.io). All images and logos (on their website) are licensed under Creative Commons Attribution-NoDerivatives 4.0 International License.

### Contributing

No

**Comment by service-paradis** [comment] 2021-11-02 12:50
Duplicate of #3651

**Closed by service-paradis** 2021-11-02 12:50 UTC
Labels: new icon
