### ISSUE TITLE
Geany

### ISSUE THREAD

**Issue by adrianoifnmg** [simple-icons/simple-icons#8499] opened 2023-04-01 17:12 UTC
### Brand Name

Geany

### Website

https://www.geany.org/

### Popularity Metric

Similarweb global rank is 656,729 

### Official Resources for Icon and Color

https://upload.wikimedia.org/wikipedia/commons/a/a0/Geany_logo.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-04-04 17:22
Duplicate of #6261

**Closed by service-paradis** 2023-04-04 17:22 UTC
Labels: new icon
