### ISSUE TITLE
qwik (javascript framework)

### ISSUE THREAD

**Issue by MarioVieilledent** [simple-icons/simple-icons#8994] opened 2023-07-11 09:31 UTC
### Brand Name

Builder.io

### Website

https://qwik.builder.io/

### Popularity Metric

https://www.similarweb.com/website/qwik.builder.io/#overview
https://github.com/BuilderIO/qwik

### Official Resources for Icon and Color

https://seeklogo.com/vector-logo/443207/qwik

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-07-11 12:47
Duplicate of #7922

**Closed by service-paradis** 2023-07-11 12:47 UTC
Labels: new icon
