### ISSUE TITLE
Davinci Resolve

### ISSUE THREAD

**Issue by smir-ant** [simple-icons/simple-icons#8287] opened 2023-01-27 11:45 UTC
### Brand Name

Davinci Resolve

### Website

https://www.blackmagicdesign.com/products/davinciresolve

### Popularity Metric

Global rank  in similarweb is 18,374. Proof: https://www.similarweb.com/website/blackmagicdesign.com/#overview

### Official Resources for Icon and Color

https://www.blackmagicdesign.com/media/images/davinci-resolve-logo
https://www.blackmagicdesign.com/media/images/davinci-resolve-logo

### Additional Comments

There are two variants of this icon…

### Contributing

Yes

**Comment by smir-ant** [comment] 2023-01-27 13:40
update: second link for icon is https://www.blackmagicdesign.com/media/images/davinci-resolve-logo-square

**Comment by service-paradis** [comment] 2023-01-30 13:03
Duplicate of #6062

**Closed by service-paradis** 2023-01-30 13:03 UTC
Labels: new icon
