### ISSUE TITLE
Add Nrwl Nx icon

### ISSUE THREAD

**Issue by sebastiandg7** [simple-icons/simple-icons#4856] opened 2021-01-25 03:36 UTC
**Brand Name:** Nx
**Website:** https://nx.dev/
**Alexa rank:** 161,488
  

**Official resources for icon and color:**
  
https://nx.devassets/images/nx-logo-white.svg
https://github.com/nrwl/nx/tree/master/images

**Comment by PeterShaggyNoble** [comment] 2021-01-25 10:26
Duplicate of #4767

**Closed by PeterShaggyNoble** 2021-01-25 10:26 UTC
Labels: new icon
