### ISSUE TITLE
Please add NetBox (DCIM, IPAM) Logo to the collection

### ISSUE THREAD

**Issue by sthierolf** [simple-icons/simple-icons#9359] opened 2023-08-21 20:32 UTC
### Brand Name

NetBox

### Website

https://github.com/netbox-community/netbox

### Popularity Metric

The NetBox project has about 13k stars on GitHub.

### Official Resources for Icon and Color

SVG Logo: https://docs.netbox.dev/en/stable/netbox_logo.svg
Color: 1685FC, from Logo

### Additional Comments

See Style guide/Branding for usage
https://docs.netbox.dev/en/stable/development/style-guide/#branding

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-08-22 12:34
Duplicate of #7058

**Closed by service-paradis** 2023-08-22 12:34 UTC
Labels: new icon
