### ISSUE TITLE
Request: yuque

### ISSUE THREAD

**Issue by shawlj** [simple-icons/simple-icons#11466] opened 2024-07-13 07:27 UTC
### Brand Name

yuque

### Website

https://www.yuque.com/

### Popularity Metric

The similarweb rank is 5852. https://www.similarweb.com/website/yuque.com/

### Official Resources for Icon and Color

logo svg
https://mdn.alipayobjects.com/huamei_0prmtq/afts/img/A*PXAJTYXseTsAAAAAAAAAAAAADvuFAQ/original

**Comment by uncenter** [comment] 2024-12-05 03:14
Duplicate of #7623.

**Closed by uncenter** 2024-12-05 03:14 UTC
Labels: new icon
