### ISSUE TITLE
Please add zustand Icon

### ISSUE THREAD

**Issue by martinkarugaba** [simple-icons/simple-icons#10007] opened 2023-12-03 15:38 UTC
### Brand Name

Zustand

### Website

https://docs.pmnd.rs/zustand/getting-started/introduction

### Popularity Metric

37.4k 

### Official Resources for Icon and Color

Brown

**Comment by service-paradis** [comment] 2023-12-04 18:12
Duplicate of #7847

**Closed by service-paradis** 2023-12-04 18:12 UTC
Labels: new icon
