### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by sian0x0** [simple-icons/simple-icons#8914] opened 2023-06-30 18:15 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

The similarweb rank is 34,821. See https://www.similarweb.com/website/matplotlib.org/#overview

### Official Resources for Icon and Color

https://github.com/matplotlib 
![215947](https://github.com/simple-icons/simple-icons/assets/89950630/ebe49e3e-1446-4958-99a6-ede16cbbd6c9)

### Contributing

No

**Comment by service-paradis** [comment] 2023-06-30 18:16
Duplicate of https://github.com/simple-icons/simple-icons/issues/3410.

**Closed by service-paradis** 2023-06-30 18:16 UTC
Labels: new icon
