### ISSUE TITLE
Apache HBase

### ISSUE THREAD

**Issue by Yanyz-ok** [simple-icons/simple-icons#8905] opened 2023-06-29 13:53 UTC
### Brand Name

Apache HBase

### Website

https://hbase.apache.org/

### Popularity Metric

https://github.com/apache/hbase

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-06-29 18:23
Duplicate of #7624

**Closed by service-paradis** 2023-06-29 18:23 UTC
Labels: new icon
