### ISSUE TITLE
Request: Grafana Loki

### ISSUE THREAD

**Issue by angelhaon** [simple-icons/simple-icons#10766] opened 2024-04-04 07:18 UTC
### Brand Name

Grafana Loki

### Website

https://grafana.com/oss/loki/

### Popularity Metric

21.9k stars at https://github.com/grafana/loki, consistent upwards star history, actively maintained.

### Official Resources for Icon and Color

None

**Comment by service-paradis** [comment] 2024-04-04 11:35
Duplicate of #9597

**Closed by service-paradis** 2024-04-04 11:35 UTC
Labels: new icon
