### ISSUE TITLE
Bazel icon

### ISSUE THREAD

**Issue by carloshdezbueno** [simple-icons/simple-icons#9834] opened 2023-11-08 09:55 UTC
### Brand Name

Bazel

### Website

https://bazel.build/

### Popularity Metric

The similar web rank is 317,798. See https://www.similarweb.com/website/bazel.build/

### Official Resources for Icon and Color

svg: https://blog.bazel.build/images/bazel-icon.svg
color: #8ccf7f

**Comment by adamrusted** [comment] 2023-11-08 10:09
Duplicate of #8166

**Closed by adamrusted** 2023-11-08 10:09 UTC
Labels: new icon
