### ISSUE TITLE
Request: Please Add Icon and Badge for Materializecss

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12017] opened 2024-10-16 08:29 UTC
### Brand Name

Materializecss

### Website

https://materializecss.com/

### Popularity Metric

Global Rank - 319969

### Official Resources for Icon and Color

https://www.svgrepo.com/svg/354047/materializecss

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment] 2024-10-16 08:36
Duplicate of #3203 - please search existing issues before opening a new one!

**Closed by adamrusted** 2024-10-16 08:36 UTC
Labels: new icon
