### ISSUE TITLE
Hugging Face Icon

### ISSUE THREAD

**Issue by E1250** [simple-icons/simple-icons#10222] opened 2024-01-07 12:42 UTC
### Brand Name

Hugging Face

### Website

https://huggingface.co/

### Popularity Metric

[2,839](https://www.similarweb.com/website/huggingface.co/#overview)
Global rand 2,839

### Official Resources for Icon and Color

![image](https://github.com/simple-icons/simple-icons/assets/24204104/b0371728-e58e-4cb7-8017-ef76baeaced5)

**Comment by PeterShaggyNoble** [comment] 2024-01-07 12:49
Duplicate of #6074

**Closed by PeterShaggyNoble** 2024-01-07 12:49 UTC
Labels: new icon
