### ISSUE TITLE
FabricMC

### ISSUE THREAD

**Issue by wiktormalyska** [simple-icons/simple-icons#9680] opened 2023-10-04 19:06 UTC
### Brand Name

FabricMC

### Website

https://fabricmc.net/

### Popularity Metric

https://www.similarweb.com/website/fabricmc.net/#overview
Global rank 63307
Category rank 2078

### Official Resources for Icon and Color

https://fabricmc.net/assets/logo.png

**Comment by adamrusted** [comment] 2023-10-04 19:12
Duplicate of #7465

**Closed by adamrusted** 2023-10-04 19:12 UTC
Labels: new icon
