### ISSUE TITLE
Request: SAS Icon

### ISSUE THREAD

**Issue by wintrobz** [simple-icons/simple-icons#6019] opened 2021-06-23 21:39 UTC
**Brand Name:** SAS (Statistical Anlaysis Software)
**Website:** https://www.sas.com/en_us/home.html
**Alexa rank:** 8269 (as of June 23, 2021)
  

**Official resources for icon and color:**
 
*Brand Page:* https://brand.sas.com/en/home.html
*Brand Assets:* https://brand.sas.com/en/home/brand-assets.html
*Brand Guidelines:* [https://brand.sas.com/content/dam/SAS/sasbrand/Documents/sas-brand-creative-guide.pdf](https://brand.sas.com/content/dam/SAS/sasbrand/Documents/sas-brand-creative-guide.pdf)

I regularly use SAS and would love to be able to easily integrate a badge to relevant git pages, sites, etc. with shield.io. I have **NO** affiliation with this brand.

**Comment by PeterShaggyNoble** [comment] 2021-06-23 21:42
Duplicate of #5875

**Closed by PeterShaggyNoble** 2021-06-23 21:42 UTC
Labels: new icon
