### ISSUE TITLE
AutoCAD

### ISSUE THREAD

**Issue by QQBoxy** [simple-icons/simple-icons#6973] opened 2021-12-22 06:01 UTC
### Brand Name

AutoCAD

### Website

https://www.autodesk.com.tw/products/autocad/overview

### Popularity Metric

The Alexa rank is 447,650. See https://www.alexa.com/siteinfo/autodesk.com.tw

### Official Resources for Icon and Color

png: https://damassets.autodesk.net/content/dam/autodesk/www/product-imagery/lockup-610x66/autocad-lockup-610x66.png

### Contributing

No

**Comment by adamrusted** [comment] 2022-01-03 18:02
Duplicate of #1984.

**Closed by adamrusted** 2022-01-03 18:02 UTC
Labels: new icon
