### ISSUE TITLE
Request: 

### ISSUE THREAD

**Issue by ahmedshahriar** [simple-icons/simple-icons#6602] opened 2021-09-26 13:52 UTC
### Brand Name

PythonAnywhere

### Website

https://www.pythonanywhere.com/

### Popularity Metric

The Alexa rank is 15,443 see https://www.alexa.com/siteinfo/www.pythonanywhere.com

### Official Resources for Icon and Color

reference link : https://www.pythonanywhere.com/about/media_resources/

logo in png: https://www.pythonanywhere.com/static/anywhere/images/PA-logo-large-icononly.png

Preview of the logo
![](https://www.pythonanywhere.com/static/anywhere/images/PA-logo-large-icononly.png)

color: black , #000000

### Contributing

Yes

**Comment by service-paradis** [comment] 2021-09-27 12:35
Duplicate of #5853

Thank you for your request @ahmedshahriar. I'm closing this one in favor of the older #5853, but feel free to contribute :)

**Closed by service-paradis** 2021-09-27 12:35 UTC
Labels: new icon
