### ISSUE TITLE
Request: Vestel

### ISSUE THREAD

**Issue by EfekanPekel** [simple-icons/simple-icons#11743] opened 2024-09-09 17:49 UTC
### Brand Name

Vestel

### Website

https://www.vestel.com.tr

### Popularity Metric

The SimilarWeb Global rank: 10,513 (https://www.similarweb.com/tr/website/vestel.com.tr/)
![image](https://github.com/user-attachments/assets/13fdb9e5-b324-4785-b338-63ae41c0705d)

### Official Resources for Icon and Color

SVG: https://upload.wikimedia.org/wikipedia/commons/8/8b/Vestel_logo.svg

Brand Guideline: https://www.vestel.com.tr/content/logolar

**Comment by coson-lu** [comment] 2024-09-10 00:22
I can work on this

**Comment by service-paradis** [comment] 2024-09-10 11:55
Duplicate of #10751

**Closed by service-paradis** 2024-09-10 11:55 UTC
Labels: new icon
