### ISSUE TITLE
SVGO(MG) misery

### ISSUE THREAD

**Issue by runxel** [simple-icons/simple-icons#2061] opened 2019-12-03 15:58 UTC
### Kind of issue 
  - [x] Improvement
  - [x] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [x] Everything. 

### Description
I think most of us already know that there's some kind of trouble with SVGO(MG) optimized svgs.
I noticed this again when reviewing #2046: the icon looks fine and most browsers should have no problem at all, but Illustrator will just show an empty file, which to me indicates a problem.
(_It is_ in fact also a problem for us, as @ericcornelissen [already stated here](https://github.com/simple-icons/simple-icons-font/issues/29).)

I found [an issue at svgo](https://github.com/svg/svgo/issues/1164#issuecomment-542310044) where these problems are referenced.
First we should update our [svgo.yaml](https://github.com/simple-icons/simple-icons/blob/develop/.svgo.yml) file to incorporate the recommendations from the svgo issue and stop encouraging users to use the online tool. At least I didn't found any way to put a detailed config there.
Fixing SVGOMG could also be an alternative, but given that this thing has 5 year old issues and four year old PR's I doubt we will come very far this way.

**Comment by ericcornelissen** [comment] 2019-12-03 23:08
>  I found an issue at svgo where these problems are referenced.
> First we should update our svgo.yaml file to incorporate the recommendations from the svgo issue

I already updated the `.svgo.yaml` file in 5e57e8fef98cffb8363f482ab0860c954328b236


> stop encouraging users to use the online tool. At least I didn't found any way to put a detailed config there.

This would be the easiest solution for us. However, given one of the goals of this project - which is to make it very easy to contribute an icon if an SVG is readily available - it is preferable for us to keep that option open.

In some regards this would also requires us to look at #1532


> Fixing SVGOMG could also be an alternative, but given that this thing has 5 year old issues and four year old PR's I doubt we will come very far this way.

I get that this is cause of concern for you, but I got [a PR merged](https://github.com/jakearchibald/svgomg/pull/141) last year without much trouble and with help from the original author. If your PR is useful it will get attention (at least last year...).

That said, getting this to work would require two major updates

1. Add a toggle to change this setting
2. Add support to import a configuration file so that we can provide one with our desired configuration (as the standard configuration will probably not comply with https://github.com/svg/svgo/issues/1164#issuecomment-542310044)

**Comment by runxel** [comment] 2019-12-04 10:56
Hey @ericcornelissen, appreciating your fast answer! :)

> I already updated the `.svgo.yaml` file in [5e57e8f](https://github.com/simple-icons/simple-icons/commit/5e57e8fef98cffb8363f482ab0860c954328b236)

Yes I saw that, but might it be that this flag should also be disabled for `mergePaths`?
(Because this is the second flag which was referenced in the issue I linked. But I am not sure, how important that one actually is.)

> > stop encouraging users to use the online tool. At least I didn't found any way to put a detailed config there.
> 
> This would be the easiest solution for us. However, given one of the goals of this project - which is to make it very easy to contribute an icon if an SVG is readily available - it is preferable for us to keep that option open.

Yes, I thought so as well. It would take away the 'easy contribution' factor too much...

> > Fixing SVGOMG could also be an alternative, but given that this thing has 5 year old issues and four year old PR's I doubt we will come very far this way.
> 
> I get that this is cause of concern for you, but I got [a PR merged](https://github.com/jakearchibald/svgomg/pull/141) last year without much trouble and with help from the original author. If your PR is useful it will get attention (at least last year...).

Okay, maybe we can take a look into it.
But that's not a timely solution. So my other question would be: Do we accept PRs which will brake our current tooling (i.e. SVGOMG optimized svgs will break the Travis build)?

**Comment by ericcornelissen** [comment] 2019-12-14 21:04
> Yes I saw that, but might it be that this flag should also be disabled for mergePaths?
(Because this is the second flag which was referenced in the issue I linked. But I am not sure, how important that one actually is.)

It could be, however in #1718 I used the [`.svgo.yml`](https://github.com/simple-icons/simple-icons/blob/5e57e8fef98cffb8363f482ab0860c954328b236/.svgo.yml) with that flag unspecified. That said, I'm not opposed to your change in https://github.com/simple-icons/simple-icons/commit/0aeb436e9b6cec828a173dffa34056ef7f686c03.


> Okay, maybe we can take a look into it. But that's not a timely solution. Do we accept PRs which will brake our current tooling (i.e. SVGOMG optimized svgs will break the Travis build)?

That is fair, if we want we could (temporarily) set up a clone website and link contributors there instead... We could decide to let the Travis build fail for "faulty" SVGs and not accept those (I would probably be in favour of providing a "correct" SVG in the error than, at that point we might as well look into automatically fixing SVGs being contributed and commiting the back to the PR). But the first problem would be to detect the "faults" correctly :thinking:

**Comment by phatbhoy67** [comment] 2019-12-15 03:16
> That is fair, if we want we could (temporarily) set up a clone website and link contributors there instead

I would agree that a fork of SVGOMG, temporary or otherwise, would be a good idea, this tool is a key element in keeping the project easy to contribute to in my opinion. I think this would also minimise disruption.

Most of the time (especially if tackling a few issues in a row) I optimise and annotate before even adding the .svg file into the branch so when I get to that point all I have to do is update the .json and push. It is very visual, I edit in Inkscape (I have a very simple template file set up), I use SVGOMG to optimise because it allows a visual check and non destructive changing of the precision which I think is very helpful.

I build on GitPod, catch any silly mistakes, see how the icon looks, then submit PR. I'm sure everyone else does things a bit differently.

Updating the contribution guidance and adding detailed examples of different workflows using different software (Inkscape, Ai, etc) might be a good idea. 

More information in the guidance, especially around using SVGO on the command line would be useful, for example, how to check for visual loss of quality. What to do if there is? 

Maybe even create a separate folder for that guidance and/or a section on the website? Sharing tips, suggested plugins to use with ide/text editors for previewing .svg. etc. This might also have an added benefit of lowering the barrier to contribution even further?

Happy to review current guidelines and make some suggestions for consideration if you think this would benefit?

There is a [plugin for Inkscape](https://github.com/juanfran/svgo-inkscape) that lets you save an optimised svg. Can we work with that as another option for a GUI type workflow? I think you can toggle SVGO options. I will check that out further and let you know.

**Comment by ericcornelissen** [comment] 2019-12-16 19:34
> I use SVGOMG to optimise because it allows a visual check and non destructive changing of the precision which I think is very helpful.

I agree that this is a benefit of SVGO, though I don't think I have ever noticed an icon that looked bad at precision 3. 🤔 

> Updating the contribution guidance and adding detailed examples of different workflows using different software (Inkscape, Ai, etc) might be a good idea.
>
> More information in the guidance, especially around using SVGO on the command line would be useful, for example, how to check for visual loss of quality. What to do if there is?

We might do that. However, I doubt how useful that is for contributors. If they are unfamiliar with the software I think Googling how to use it is more effective (though we could provide some pointers in [the table](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo)), if they are familiar with the software I think people will just use whatever they feel comfortable with. 


> Maybe even create a separate folder for that guidance and/or a section on the website? Sharing tips, suggested plugins to use with ide/text editors for previewing .svg. etc. This might also have an added benefit of lowering the barrier to contribution even further?

I don't think it is a good idea to add it in a separate folder, personally. I think it is best to keep most of that stuff in the Contributing Guidelines file. If you feel like writing about contributing with Inkscape you could look into writing a [dev.to](https://dev.to/) or [Medium](https://medium.com/) (or whatever else). That might even get us some new contributors 😉 


> There is a plugin for Inkscape that lets you save an optimised svg. Can we work with that as another option for a GUI type workflow? I think you can toggle SVGO options. I will check that out further and let you know.

Illustrator can do that out of the box (at least optimizing, not SVGO stuff as far as I know) and I suppose there is a couple of other ways to do it. The benefit of using just SVGO(MG) is that you don't need anything new. SVGOMG just works in the browser and you can use SVGO if you have Node with NPM installed (which is maybe not true for every contributor).

**Comment by ericcornelissen** [comment] 2021-02-20 23:56
Just want to point out real quick here that with [SVGO v2](https://github.com/svg/svgo/releases/tag/v2.0.0) there is now a bundle included with SVGO to run it in a browser context. This _could_ make it significantly easier for us to have a "clone" of SVGOMG of our own, perhaps even just one that always uses the configuration we need (though probably the precision needs to stay configurable).

**Comment by PeterShaggyNoble** [comment] 2021-02-22 10:45
>  even just one that always uses the configuration we need (though probably the precision needs to stay configurable)

I'd be in favour of that, @ericcornelissen as it could significantly reduce one of the barriers to entry for contributors who are complete new to working with SVGs. With everything else we have going on right now, though, I wouldn't deem it high priority.

**Comment by adamrusted** [comment] 2021-05-05 18:51
@runxel did you ever have any joy with SVGOMG and Illustrator? I'm having a _wonderful_ time trying to review PRs that've used it, resorting to using Affinity Designer or Inkscape for comparison, when I'm not that confident in those packages when comparing.

**Comment by runxel** [comment] 2021-05-05 21:34
@adamrusted Ha!
It's atrocious when people use the online SVGOMG.

**Comment by jorgeamadosoria** [comment] 2021-09-23 17:46
It's this issue still relevant? Is there an action that can be taken to move this along or close it?
FWIW, working with Inkscape I have have zero problems and have never needed SVGOMG, so it's definitely possible for a completely ignorant person like me to work with SVGs without ever needing that particular software.

**Comment by runxel** [comment] 2021-09-24 17:22
Maybe this issue can be closed now, @jorgeamadosoria.
The original problem was that SVGOMG broke Travis builds and other stuff, like the PDF generation.
This is no longer the case, since we switched to GitHub Actions e.g.
(Also it broke Illustrator)

I guess all of this is no longer relevant since every commit gets checked.

**Closed** 2021-09-24 17:39 UTC
Labels: meta

**Comment by ericcornelissen** [comment] 2021-09-25 10:42
I still strongly believe that providing SVGOMG as an option for contributor is very useful. Just because we tend to use editor plugins or the CLI doesn't mean others want to or can use it.

But even more than that, the problem isn't just SVGOMG, the problem is that SVGO [can be configured](https://github.com/svg/svgo/issues/1164#issuecomment-542310044) in such a way that it breaks some SVG tooling - most notably (older?) versions of Adobe Illustrator, but also others, see #2713. If I recall correctly the default configuration of SVGO does this, so using a plugin (without configuration) probably doesn't help when it comes to the "misery" that this issue addresses. The only thing that definitely addresses it is using the `npm run svgo -- icons/file.svg` command from this repo as we control the configuration for that.

That being said, beyond creating our own SVGOMG that uses the correct (for us) configuration, forcing contributors to use the SVGO CLI, or having this flagged by the (SVG) linter - none of which are ideal (*) - I don't see a solution here. In that regard, closing this issue is fine. However, if we do that, I do think there's merit in re-opening #2713 for visibility.

---

(*) They're not ideal because:

- "our own SVGOMG that uses the correct (for us) configuration": probably quite some work and people will probably still use the existing SVGOMG for quite a while, especially people that have contributed in the past.
- "forcing contributors to use the SVGO CLI": messes with a lot of peoples workflows, not to mention that it requires all contributors to have NodeJS setup (which is definitely not something all our contributors have).
- "having this flagged by the (SVG) linter": while probably not too hard, the only solution once it's flagged is for the contributor to use the CLI (with its drawbacks).
