### ISSUE TITLE
Request: Midjourney

### ISSUE THREAD

**Issue by Yasar2019** [simple-icons/simple-icons#11755] opened 2024-09-11 22:52 UTC
### Brand Name

Midjourney

### Website

https://www.midjourney.com/home

### Popularity Metric

The Similarweb rank is 1720. See https://www.similarweb.com/website/midjourney.com/#overview

### Official Resources for Icon and Color

SVG : https://en.m.wikipedia.org/wiki/File:Midjourney_Emblem.svg

**Comment by uncenter** [comment] 2024-09-11 22:55
Duplicate of #8753. Please search for existing issues before opening new ones!

**Closed by uncenter** 2024-09-11 22:55 UTC
Labels: new icon
