### ISSUE TITLE
Request to add Axios icon

### ISSUE THREAD

**Issue by mrhrifat** [simple-icons/simple-icons#6807] opened 2021-11-01 11:10 UTC
### Brand Name

Axios

### Website

https://axios-http.com/

### Popularity Metric

It's download 
> 92M/Month

See,
```
http://npm-stat.com/charts.html?package=axios
```

### Official Resources for Icon and Color

SVG
```
https://avatars.githubusercontent.com/u/32372333?s=200&v=4
```
Color
> #5a29e4

### Additional Comments

Thanks for making Icons for all world's developer community.

**Comment by mrhrifat** [comment] 2021-11-01 11:26
Actually a icon or seems to button of your organization has been added to my Profile Activity. That's why I closed & reopen this issue.
How to remove it?

**Comment by service-paradis** [comment] 2021-11-01 12:51
Duplicate of #3821

PR: #5991

**Closed by service-paradis** 2021-11-01 12:51 UTC
Labels: new icon

**Comment by mrhrifat** [comment] 2021-11-01 12:56
> Duplicate of #3821
> 
> PR: #5991

Please help to solve this... 

Actually a icon or seems to button of your organization has been added to my Profile Contribution Activity. How to remove it?

**Comment by service-paradis** [comment] 2021-11-01 12:59
You open this issue. This activity will appear in your activity:
![image](https://user-images.githubusercontent.com/12817388/139675317-94d4588f-79b2-432d-af6f-4335d6ea3a9b.png)

**Comment by mrhrifat** [comment] 2021-11-01 13:34
I am talking about this issue.

![image](https://user-images.githubusercontent.com/45077312/139679943-b2fd857f-1bc9-4644-83f5-26dc58d46e00.png)

**Comment by mrhrifat** [comment] 2021-11-01 13:40
I am talking about this issue. On contribution activity profile. Although I didn't fork, contribute any repository of this organization. 
![image](https://user-images.githubusercontent.com/45077312/139680752-b8d4ea45-cb7c-40d8-811d-b93292e1dbeb.png)


Is this problem happen for I choose **YES** while I was creating issue, which is a option in your add icon request form. Than please delete my issue.

![2](https://user-images.githubusercontent.com/45077312/139680796-c604267a-f51d-46e7-b3d0-cc3e1a8e697f.png)

**Comment by service-paradis** [comment] 2021-11-01 13:59
Opening issues is counted towards contribution activity for Github profiles:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/viewing-contributions-on-your-profile#what-counts-as-a-contribution

There is nothing I can do to remove your profile activity.

**Comment by mrhrifat** [comment] 2021-11-01 14:27
If you delete this issue, than it will be remove. So please delete my issue. Only admin of this repository can do this.

**Comment by mrhrifat** [comment] 2021-11-01 18:08
> Opening issues is counted towards contribution activity for Github profiles: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/viewing-contributions-on-your-profile#what-counts-as-a-contribution
> 
> There is nothing I can do to remove your profile activity.

If you delete this issue, than it will be remove. So please delete my issue. Only admin of this repository can do this.

**Comment by mrhrifat** [comment] 2021-11-02 12:31
@service-paradis  Please delete my issue.

**Comment by service-paradis** [comment] 2021-11-02 12:42
@mrhrifat Please stop bumping this issue. I'm not an admin here. I cannot delete this issue.

Once an admin have some time, they will take a look at it. Next time, instead of asking to delete an issue, open one only if needed.
