### ISSUE TITLE
grpc

### ISSUE THREAD

**Issue by Perry-chouteau** [simple-icons/simple-icons#8340] opened 2023-02-12 22:05 UTC
### Brand Name

grpc

### Website

https://grpc.io/

### Popularity Metric

Is gRPC widely used?
gRPC is a robust open-source RPC (Remote Procedure Call) framework used to build scalable and fast APIs. It allows the client and server applications to communicate transparently and develop connected systems. Many leading tech firms have adopted gRPC, such as Google, Netflix, Square, IBM, Cisco, & Dropbox.

### Official Resources for Icon and Color

icon:

https://cncf-branding.netlify.app/projects/grpc/

color are: #5ac5c5 #244c5a 

and should be: #5ac5c5

### Contributing

Yes/No

**Comment by service-paradis** [comment] 2023-02-13 14:10
Duplicate of #6275

**Closed by service-paradis** 2023-02-13 14:10 UTC
Labels: new icon
