### ISSUE TITLE
Request: Taipy

### ISSUE THREAD

**Issue by ancilcleetus** [simple-icons/simple-icons#11087] opened 2024-06-02 04:08 UTC
### Brand Name

Taipy

### Website

https://taipy.io/

### Popularity Metric

Taipy is an open-source Python library used for creating full-stack web applications in no time using only Python code. It is a strong competitor to Streamlit and is getting quickly adopted by data scientists and machine learning engineers to build full-stack apps. It is ranked 762,738 in SimilarWeb. Its GitHub repo has got 9.4k stars and star history is on a consistently upward trajectory.

### Official Resources for Icon and Color

svg: https://taipy.io/_next/static/media/2b7195d6381f0a32d6a885c234272d9a.svg

### Additional Comments

With Taipy, we can create full-stack web apps without learning new languages or full-stack frameworks. UI can be designed using Markdown in Taipy. It has been designed to expedite application development, from initial prototypes to production-ready applications in no time.

**Comment by anhthang** [comment] 2024-06-02 07:39
duplicate #11016, also fixed by #11049

**Comment by ancilcleetus** [comment] 2024-06-02 11:53
@anhthang But I cannot see taipy in https://simpleicons.org/

Can you share the img.shields.io badge url for taipy ?

**Comment by anhthang** [comment] 2024-06-02 12:00
@ancilcleetus It will be available in the next release

**Comment by ancilcleetus** [comment] 2024-06-02 12:06
@anhthang Thanks for the info.

**Comment by uncenter** [comment] 2024-06-02 12:51
Duplicate of #11016. Please search pre-existing issues and pull requests before opening a new one.

**Closed by uncenter** 2024-06-02 12:51 UTC
Labels: new icon
