### ISSUE TITLE
Need Icon

### ISSUE THREAD

**Issue by warzoneheatt** [simple-icons/simple-icons#7072] opened 2022-01-19 04:06 UTC
### Brand Name

OpenSea

### Website

https://opensea.io/

### Popularity Metric

[https://opensea.io/](url)

### Official Resources for Icon and Color

[https://opensea.io/](url)[](url)

### Additional Comments

White boat inside a blue circle

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-01-19 07:06
duplicate of #6773

**Comment by sachinraja** [comment] 2022-01-19 07:06
cc @mondeja @service-paradis we really need to fix the potential duplicates action

**Closed by sachinraja** 2022-01-19 07:06 UTC
Labels: new icon, duplicate
