### ISSUE TITLE
Helix Text Editor Logo

### ISSUE THREAD

**Issue by yogiyiorgos** [simple-icons/simple-icons#9916] opened 2023-11-25 09:59 UTC
### Brand Name

Helix Editor

### Website

https://helix-editor.com/

### Popularity Metric

The GitHub stars are currently: 26.4k

### Official Resources for Icon and Color

https://helix-editor.com/logo.svg

**Comment by service-paradis** [comment] 2023-11-27 12:34
Duplicate of #8421

**Closed by service-paradis** 2023-11-27 12:34 UTC
Labels: new icon
