### ISSUE TITLE
Request: Avalonia UI

### ISSUE THREAD

**Issue by patryk-penczek** [simple-icons/simple-icons#12281] opened 2024-12-04 20:10 UTC
### Brand Name

Avalonia UI

### Website

https://avaloniaui.net

### Popularity Metric

The Similarweb rank is 187,294. See https://www.similarweb.com/website/avaloniaui.net

### Official Resources for Icon and Color

- PNG: https://avatars.githubusercontent.com/u/14075148?s=200&v=4
- Color: `#0d6efd`, from the GitHub organisation

**Comment by uncenter** [comment] 2024-12-05 02:56
Duplicate of #9223.

**Closed by uncenter** 2024-12-05 02:56 UTC
Labels: new icon
