### ISSUE TITLE
AVM Fritz logo

### ISSUE THREAD

**Issue by Smartich0ke** [simple-icons/simple-icons#9791] opened 2023-10-29 00:03 UTC
### Brand Name

AVM Fritz

### Website

https://avm.de

### Popularity Metric

The AVM rank is 11,572

### Official Resources for Icon and Color

none

**Comment by service-paradis** [comment] 2023-10-30 16:37
Duplicate of https://github.com/simple-icons/simple-icons/issues/7992

**Closed by service-paradis** 2023-10-30 16:37 UTC
Labels: new icon
