### ISSUE TITLE
Adding multiple `hex` to icons

### ISSUE THREAD

**Issue by mwskwong** [simple-icons/simple-icons#9940] opened 2023-11-28 01:33 UTC
### Kind of Issue

Feature

### This issue concerns the...

NPM package

### Package Version

10.0.0

### Other Software

Unrelevant

### Description

Currently, `simple-icons` have assigned `hex` to each of the icons, which is (usually) the branding color of the corresponding brand. Yet, for some brands, it can have multiple branding colors, e.g. for light and dark modes, examples are:

- [Prisma](https://github.com/prisma/presskit)
- [Vercel](https://vercel.com/design/brands)

I would like to propose allowing multiple `hex` to be associated to icons, e.g., for Prisma

```ts
{
  hex: {
    light: 'ffffff',
    dark: '2d3748',
    colored: '4c51bf',
  }
}
```

**Comment by adamrusted** [comment] 2023-11-28 07:10
If using [our CDN](https://cdn.simpleicons.org) you can specify a light and dark mode colour. Adding a light and dark hex to the package would add a lot of code, and seems kind of counter-intuitive to the _simple_ in Simple Icons.

**Comment by LitoMore** [comment] 2023-11-28 07:41
This might be against some icon brand guidelines. Closing.

**Closed by LitoMore** 2023-11-28 07:41 UTC
Labels: package

**Comment by mondeja** [comment] 2023-11-30 21:30
> This might be against some icon brand guidelines. Closing.

I think that this is a poor explanation. The closing reason should be because this is a duplicate of #9802, so I'm marking as is.
