### ISSUE TITLE
GRPC icon request

### ISSUE THREAD

**Issue by apoorvdwi** [simple-icons/simple-icons#9767] opened 2023-10-21 16:37 UTC
### Brand Name

grpc

### Website

https://grpc.io/

### Popularity Metric

SimilarWeb rank is 270,375. See https://www.similarweb.com/website/grpc.io/#overview
GitHub is https://github.com/grpc

### Official Resources for Icon and Color

https://grpc.io/img/logos/grpc-logo.png from website

**Comment by service-paradis** [comment] 2023-10-23 12:52
Duplicate of #6275

**Closed by service-paradis** 2023-10-23 12:52 UTC
Labels: new icon
