### ISSUE TITLE
TypeORM Icon

### ISSUE THREAD

**Issue by deivisonresende** [simple-icons/simple-icons#6078] opened 2021-07-04 02:09 UTC
**Brand Name:** TypeORM
**Website:** https://typeorm.io/#/
**Alexa rank:** https://www.alexa.com/siteinfo/typeorm.io

**Official resources for icon and color:**

![typeorm 1](https://user-images.githubusercontent.com/66370425/124370974-7186fb80-dc53-11eb-83d4-1c3b6b1bc260.jpg)

**Comment by service-paradis** [comment] 2021-07-04 18:26
Duplicate of #3436

**Closed by service-paradis** 2021-07-04 18:26 UTC
Labels: new icon
