### ISSUE TITLE
Rumble

### ISSUE THREAD

**Issue by namaste99** [simple-icons/simple-icons#9214] opened 2023-08-05 00:15 UTC
### Brand Name

Rumble

### Website

https://rumble.com/

### Popularity Metric

The Similarweb site for Rumble is https://www.similarweb.com/website/rumble.com/

### Official Resources for Icon and Color

https://commons.wikimedia.org/wiki/File:Rumble_logo_2022.svg

### Contributing

No

**Comment by service-paradis** [comment] 2023-08-07 12:40
Duplicate of #8495

**Closed by service-paradis** 2023-08-07 12:40 UTC
Labels: new icon
