### ISSUE TITLE
Request: Final Cut Pro

### ISSUE THREAD

**Issue by Whoami-Voyager** [simple-icons/simple-icons#11477] opened 2024-07-15 19:24 UTC
### Brand Name

Final Cut Pro

### Website

https://apps.apple.com/us/app/final-cut-pro/id424389933?ign-itscg=20201&ign-itsct=fcp-sem-168128672630-704882499060&mttnagencyid=c1a&mttncc=US&mttnpid=Google%20AdWords&mttnsiteid=141192&mttnsubad=fcp-sem-168128672630-704882499060&mttnsubkw=kwd-15028640&mttnsubplmnt=c_adext%3A

### Popularity Metric

2.2% of video editors use Final Cut Pro, and you guys have already included the Xcode icon so why not add this.

### Official Resources for Icon and Color

None

### Additional Comments

I think Logic Pro should be additionally added to complete the professional suite of apple products

**Comment by uncenter** [comment] 2024-07-15 19:25
Can you provide a valid popularity metric from our list? https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity

**Comment by Whoami-Voyager** [comment] 2024-07-15 19:30
> Can you provide a valid popularity metric from our list? https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity

The Problem is that using this I can't really get an accurate assessment of website traffic due to both it being nested in the app store and apple.com website, which gives traffic statistics for all other apps and website visit, not just Final Cut. 
Accoring to Wikipedia:
In April 2018, Apple said that there were more than 2.5 million users of Final Cut Pro X. In version 10.4. 1, released during the NAB Show 2018, closed captioning was added, along with support for ProRes RAW.

**Comment by uncenter** [comment] 2024-12-05 03:11
Duplicate of #5372, and still as the same issue:

> Closing this given more than 2 years have passed with no suggestions of how to convert it to monochrome while maintaining the integrity of the brand. If anyone _does_ have an idea then we can revisit this issue.

**Closed by uncenter** 2024-12-05 03:11 UTC
Labels: new icon, vector unavailable
