### ISSUE TITLE
Icon request for Processing IDE

### ISSUE THREAD

**Issue by TheHolyWaterme1on** [simple-icons/simple-icons#5575] opened 2021-04-29 22:06 UTC
**Brand Name:** Processing
**Website:** https://processing.org/
**Alexa Rank:** #41,859 https://www.alexa.com/siteinfo/processing.org
**Official resource for icons:** https://commons.wikimedia.org/wiki/File:Processing_3_logo.png

**Comment by PeterShaggyNoble** [comment] 2021-04-29 22:28
Duplicate of #4885

**Closed by PeterShaggyNoble** 2021-04-29 22:28 UTC
Labels: new icon
