### ISSUE TITLE
Request: VRChat

### ISSUE THREAD

**Issue by anatawa12** [simple-icons/simple-icons#11337] opened 2024-06-27 11:57 UTC
### Brand Name

VRChat

### Website

https://hello.vrchat.com/

### Popularity Metric

The Similarweb rank is 8,674. See https://www.similarweb.com/website/vrchat.com/

### Official Resources for Icon and Color

https://hello.vrchat.com/press

Color: unknown

**Comment by uncenter** [comment] 2024-06-27 12:19
Duplicate of #7763. Please search existing issues before opening new ones.

**Closed by uncenter** 2024-06-27 12:19 UTC
Labels: new icon

**Comment by anatawa12** [comment] 2024-06-27 12:31
Sorry I searched with additional query by mistake

**Comment by anatawa12** [comment] 2024-06-27 15:56
Sorry I searched issue on https://github.com/simple-icons/simple-icons-website and I forget to search after redirecting to this repository.
