### ISSUE TITLE
Request: Zed

### ISSUE THREAD

**Issue by tecandrew** [simple-icons/simple-icons#10506] opened 2024-02-21 00:56 UTC
### Brand Name

Zed

### Website

https://zed.dev

### Popularity Metric

Similarweb global rank is 84,519. See https://similarweb.com/website/zed.dev

### Official Resources for Icon and Color

Zed editor and website logo are from their GitHub repo: https://github.com/zed-industries/zed/tree/main/assets/icons

seems to be only in white. the "Zed Industries" seem to be a logo on their site too, but isn't published anywhere officially.

![logo_96](https://github.com/simple-icons/simple-icons/assets/21319730/48fd2c42-cec8-43b2-90ae-08439310e1b5)

### Additional Comments

Icon and assets are under "AGPL-3.0 or later" (from github repo)

https://github.com/zed-industries/zed

**Comment by adamrusted** [comment] 2024-02-22 20:38
Hey @tecandrew - I think we can totally accept this icon, based on both SimilarWeb rank and GitHub stars.
I think you're right that it's `Zed Industries` that we should include - that way we're using the 'official brand name' and it'll still be visible for people using 'zed' as their search term!

**Comment by PeterShaggyNoble** [comment] 2024-02-23 10:36
Duplicate of #7583, which was closed as being out of scope. And, while it is now _in_ scope, there was a massive jump in its Similarweb rank this month and its [star history](https://star-history.com/#zed-industries/zed) has been on a suspiciously straight vertical climb over the past month, in which they've gained ~21.5k stars. o I'd be in favour of monitoring at least until SW update their data next month.

**Comment by nirvikpurkait** [comment] 2024-02-24 03:02
>suspiciously straight vertical climb over the past month


I don't know much, but after seeing some YouTube video I'm guessing the reason for the jump in star history is because, it was under development as closed-source but recently became open-souce.

**Closed** 2024-03-11 13:46 UTC
Labels: new icon, good first issue
