### ISSUE TITLE
Request: Babylon.js

### ISSUE THREAD

**Issue by timondev** [simple-icons/simple-icons#8736] opened 2023-06-06 12:47 UTC
### Brand Name

Babylon.js

### Website

https://www.babylonjs.com/

### Popularity Metric

The Similarweb rank is 140,065. See https://www.similarweb.com/website/babylonjs.com/#overview
The Github repo has 20.8k stars.

### Official Resources for Icon and Color

svg: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/fullColor/babylon_logo_color.svg
color: #BB464B
brand-toolkit: https://github.com/BabylonJS/Brand-Toolkit

### Additional Comments

There are multiple monochrome variants of the logo:
- monochrome dark: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/monochrome/babylon_logo_monochrome_dark.svg
- monochrome light: https://github.com/BabylonJS/Brand-Toolkit/blob/master/babylon_logo/monochrome/babylon_logo_monochrome_light.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-06-06 18:02
Duplicate of #7148

**Closed by service-paradis** 2023-06-06 18:02 UTC
Labels: new icon, duplicate
