### ISSUE TITLE
generate colored versions of SVGs

### ISSUE THREAD

**Issue by cloudagon** [simple-icons/simple-icons#5707] opened 2021-05-16 06:12 UTC
It is not possible to add attributes to the svgs served in the CDN unless you manually copy the SVG to your page. It would be nice to provide the colored versions of all SVGs that can simply be embedded via CDN, perhaps under a different package as to not increase the size the current one.

**Comment by PeterShaggyNoble** [comment] 2021-05-28 10:20
Duplicate of #1060

**Closed by PeterShaggyNoble** 2021-05-28 10:20 UTC
Labels: package
