### ISSUE TITLE
Icon request: Navidrome

### ISSUE THREAD

**Issue by mmonseurs** [simple-icons/simple-icons#11650] opened 2024-08-20 07:46 UTC
### Brand Name

Navidrome

### Website

https://navidrome.org

### Popularity Metric

Similarweb ranking is 424,677. See https://www.similarweb.com/website/navidrome.org/#overview

### Official Resources for Icon and Color

None

**Comment by uncenter** [comment] 2024-08-20 12:01
Duplicate of #7818. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-08-20 12:01 UTC
Labels: new icon
