### ISSUE TITLE
Request: Add MIT license icon

### ISSUE THREAD

**Issue by muath-ye** [simple-icons/simple-icons#7511] opened 2022-06-16 22:33 UTC
### Brand Name

MIT License

### Website

https://mit-license.org/

### Popularity Metric

https://github.com/remy/mit-license

### Official Resources for Icon and Color

![favicon.ico](https://mit-license.org/favicon.ico)

### Contributing

Yes

**Comment by service-paradis** [comment] 2022-06-23 19:34
Duplicate of #3541

**Closed by service-paradis** 2022-06-23 19:34 UTC
Labels: new icon
