### ISSUE TITLE
Icon Requests: Hadoop and Hive

### ISSUE THREAD

**Issue by LvffY** [simple-icons/simple-icons#5457] opened 2021-04-15 09:39 UTC
Hi

It would be great if you could add more Big data technologies logos, like Apache Hive and/or Apache Hadoop

## Apache Hadoop 

**Brand Name:** Apache hadoop
**Website:** https://hadoop.apache.org/
**Alexa rank:** 181.4 k
  

**Official resources for icon and color:** https://svn.apache.org/repos/asf/comdev/project-logos/originals/hadoop.svg
  
  

## Apache Hive

**Brand Name:** Apache Hive
**Website:** https://hive.apache.org/
**Alexa rank:** 181.4 k *Same rank as before because it's dectected as <b>apache.org</b> website*
  

**Official resources for icon and color:** https://svn.apache.org/repos/asf/comdev/project-logos/originals/hive.svg

**Comment by PeterShaggyNoble** [comment] 2021-04-15 09:42
Duplicate of #3548 & #3545

Hive is already in our collection:
![Apache Hive](https://user-images.githubusercontent.com/15157491/114849017-3fde6100-9dd7-11eb-8265-5d4e7f4d55ce.png)

**Closed by PeterShaggyNoble** 2021-04-15 09:42 UTC
Labels: new icon

**Comment by LvffY** [comment] 2021-04-15 09:44
Hi @PeterShaggyNoble 

What hadoop the Hadoop logo ?
