### ISSUE TITLE
crowdsec.net

### ISSUE THREAD

**Issue by ToXinE** [simple-icons/simple-icons#11752] opened 2024-09-10 15:02 UTC
### Brand Name

Crowdsec

### Website

https://app.crowdsec.net

### Popularity Metric

the similairweb rank is 292,157 https://www.similarweb.com/fr/website/crowdsec.net/#overview

### Official Resources for Icon and Color

https://app.crowdsec.net/vectors/logo-outlined.svg

**Comment by sebastien46** [comment] 2024-09-10 16:58
Duplicate of #8638

**Closed** 2024-09-10 17:59 UTC
Labels: new icon
