### ISSUE TITLE
Request: Flipkart Icon

### ISSUE THREAD

**Issue by hasthamalp** [simple-icons/simple-icons#3986] opened 2020-11-20 13:03 UTC
**Name:** Flipkart
**Website:** https://www.flipkart.com/
**Alexa rank:** 81
  

**Official resources for icon and color:** https://www.flipkart.com/

**Comment by PeterShaggyNoble** [comment] 2021-01-07 12:24
Duplicate of #3190

**Closed by PeterShaggyNoble** 2021-01-07 12:24 UTC
Labels: new icon
