### ISSUE TITLE
Rumble icon is missing

### ISSUE THREAD

**Issue by jurilents** [simple-icons/simple-icons#10431] opened 2024-02-10 17:09 UTC
### Brand Name

Rumble

### Website

https://rumble.com/

### Popularity Metric

The rumble rank is 367 in global (144 US), look here https://www.similarweb.com/website/rumble.com/

### Official Resources for Icon and Color

svg: https://en.m.wikipedia.org/wiki/File:Rumble_logo_2022.svg
svg (from website): https://rumble.com/img/rumble-full-logo-v4-dark.svg
color: #85c742 (--rumble-green)

### Additional Comments

You already have this icon, but there is no icon to download

**Comment by Garbg** [comment] 2024-02-10 17:42
The source is present in _data/simpleicons.json, I don't understand the issue
![image](https://github.com/simple-icons/simple-icons/assets/83542885/1b4eefc3-a807-4f26-a0f1-c3b3442da035)

**Comment by PeterShaggyNoble** [comment] 2024-02-10 20:54
Duplicate of #8495

And, as @Garbg mentioned, this is already in our library.

**Closed** 2024-02-10 20:53 UTC
Labels: new icon

**Comment by Garbg** [comment] 2024-02-10 23:59
The icon is available for download, no issue here
