### ISSUE TITLE
Request: Seaborn

### ISSUE THREAD

**Issue by jacktheripp3r** [simple-icons/simple-icons#7014] opened 2022-01-02 07:38 UTC
### Brand Name

Seaborn

### Website

https://seaborn.pydata.org/index.html

### Popularity Metric

https://www.alexa.com/siteinfo/pydata.org

### Official Resources for Icon and Color

https://github.com/mwaskom/seaborn/tree/master/doc/_static

### Contributing

No

**Comment by adamrusted** [comment] 2022-01-03 16:31
We cannot use the Alexa rank as a popularity metric because that relates to pydata.org, as opposed to Seaborn as a product/brand in it's own right. However, with >9k⭐ this can be worked on no problem. Would you want to contribute this icon yourself?

**Comment by sachinraja** [comment] 2022-01-19 03:38
duplicate of #6324

**Closed by sachinraja** 2022-01-19 03:38 UTC
Labels: new icon
