### ISSUE TITLE
Appium icon request

### ISSUE THREAD

**Issue by sadabnepal** [simple-icons/simple-icons#7112] opened 2022-01-30 17:37 UTC
### Brand Name

Appium

### Website

https://appium.io/

### Popularity Metric

Alexa Rank: #89,860
GitHub star: 14.7K

### Official Resources for Icon and Color

https://worldvectorlogo.com/download/appium.svg

### Contributing

No

**Comment by sachinraja** [comment] 2022-02-02 02:34
duplicate of #3385

**Closed by sachinraja** 2022-02-02 02:34 UTC
Labels: new icon
