### ISSUE TITLE
please add icon google 

### ISSUE THREAD

**Issue by azkadev** [simple-icons/simple-icons#6904] opened 2021-11-24 03:32 UTC
[google-apps-script](https://www.gstatic.com/script/apps_script_1x_24dp.png)

**Comment by service-paradis** [comment] 2021-11-24 13:49
Duplicate of #3556

Next time, use the issue template before requesting an icon. Without required information, it wont be added anyway.

**Closed by service-paradis** 2021-11-24 13:49 UTC
