### ISSUE TITLE
Express.js

### ISSUE THREAD

**Issue by mvaden** [simple-icons/simple-icons#4279] opened 2020-12-06 16:41 UTC
[Express.js](https://expressjs.com/) .

**Name:** Express.js
**Website:**  https://expressjs.com/
**Alexa rank:** 11,513
  

**Official resources for icon and color:**

**Comment by mondeja** [comment] 2020-12-06 16:46
This is a duplicate of #2924.

**Closed by mondeja** 2020-12-06 16:46 UTC
Labels: new icon
