### ISSUE TITLE
Poetry packages

### ISSUE THREAD

**Issue by Umesh-JNU** [simple-icons/simple-icons#6007] opened 2021-06-20 22:40 UTC
**Brand Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by service-paradis** [comment] 2021-06-21 19:23
Hello @Umesh-JNU. If you want an icon to be added, you have to provide the needed information from the issue template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

**Comment by Umesh-JNU** [comment] 2021-06-21 23:37
Well thank you for reaching me.
Your required information are as follows
Website: https://python-poetry.org/
Name Poetry : Python dependency package manager.
I don't know about Alexa ranking.

**Comment by service-paradis** [comment] 2021-06-22 00:31
Duplicate of #5486

**Closed by service-paradis** 2021-06-22 00:31 UTC
Labels: awaiting reply, new icon
