### ISSUE TITLE
Phoenix icon

### ISSUE THREAD

**Issue by ZaneH** [simple-icons/simple-icons#8405] opened 2023-03-07 05:54 UTC
### Brand Name

Phoenix Framework

### Website

https://www.phoenixframework.org/

### Popularity Metric

**Similarweb global rank**: 432,292
- https://www.similarweb.com/website/phoenixframework.org/#overview

**GitHub stars**: 19.2k
- https://github.com/phoenixframework/phoenix

### Official Resources for Icon and Color

color: `#F0531E`, from logo in the documentation
png: https://hexdocs.pm/phoenix/assets/logo.png from documentation
svg: https://github.com/simple-icons/simple-icons/issues/4917#issuecomment-1411059723 from a previous request

### Additional Comments

- This is a web framework that has been gaining more attention lately

### Contributing

No

**Comment by karthiknadar1204** [comment] 2023-03-07 09:10
I would love to work on this issue,please assign it to me and please give me more insight into where do we have to add the icon.

**Comment by service-paradis** [comment] 2023-03-07 14:40
Duplicate of #4917

**Closed by service-paradis** 2023-03-07 14:40 UTC
Labels: new icon
