### ISSUE TITLE
mongoose icon

### ISSUE THREAD

**Issue by hwd-2020** [simple-icons/simple-icons#8118] opened 2022-12-07 14:32 UTC
### Brand Name

mongoose

### Website

https://mongoosejs.com/

### Popularity Metric

https://github.com/Automattic/mongoose

### Official Resources for Icon and Color

color: #800

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-01-16 20:21
Duplicate of #5594

**Closed by service-paradis** 2023-01-16 20:21 UTC
Labels: new icon
