### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by Tarun-Kamboj** [simple-icons/simple-icons#5321] opened 2021-03-20 05:53 UTC
**Brand Name:** Matplotlib
**Website:** https://matplotlib.org/
**Alexa rank:** 13,549
  

**Official resources for icon and color:** https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Created_with_Matplotlib-logo.svg/1024px-Created_with_Matplotlib-logo.svg.png

**Comment by fbernhart** [comment] 2021-03-20 07:24
Duplicate of #3410

**Closed by fbernhart** 2021-03-20 07:24 UTC
Labels: new icon, duplicate
