### ISSUE TITLE
Request: Gradio

### ISSUE THREAD

**Issue by peinan** [simple-icons/simple-icons#10534] opened 2024-02-26 04:40 UTC
### Brand Name

Gradio

### Website

https://www.gradio.app/

### Popularity Metric

Global rank: 119,426
cf. https://www.similarweb.com/website/gradio.app/

### Official Resources for Icon and Color

svg: https://www.gradio.app/_app/immutable/assets/gradio-logo.3d131bff.svg
Brand page: https://www.gradio.app/brand

**Comment by Mvlprem** [comment] 2024-02-26 06:32
Thanks for the request, @peinan  👍🏻 Would you like to have a read through [our contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon) and try this one yourself?

**Comment by service-paradis** [comment] 2024-02-26 13:41
Duplicate of #9481

**Closed by service-paradis** 2024-02-26 13:41 UTC
Labels: new icon
