### ISSUE TITLE
namecheap

### ISSUE THREAD

**Issue by EdzonQS** [simple-icons/simple-icons#4256] opened 2020-12-03 05:41 UTC
**Name:**
**Website:**
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by fbernhart** [comment] 2020-12-03 09:04
Hi @EdzonQS. If you want an icon to be added, you have to provide the needed information in the template:

> Name:
> Website:
> Alexa rank:
> 
> Official resources for icon and color:

And please search for already opened issues for this icon first. This is a duplicate of #3974

**Comment by service-paradis** [comment] 2020-12-03 13:11
Duplicate of https://github.com/simple-icons/simple-icons/issues/3974

**Closed by service-paradis** 2020-12-03 13:11 UTC
Labels: new icon
