### ISSUE TITLE
Request: Recoil

### ISSUE THREAD

**Issue by devpla** [simple-icons/simple-icons#7161] opened 2022-02-19 18:04 UTC
### Brand Name

Recoil

### Website

https://recoiljs.org/

### Popularity Metric

The Alexa rank is 158,568. See https://www.alexa.com/siteinfo/recoiljs.org

![image](https://user-images.githubusercontent.com/87457066/154813165-1834b58e-42dd-4429-aceb-68686b3125fd.png)

### Official Resources for Icon and Color

svg: https://recoiljs.org/img/logo.svg
color: #1C1E21

![](https://recoiljs.org/img/logo.svg)

### Contributing

No

**Comment by sachinraja** [comment] 2022-02-20 15:08
duplicate of #5498

**Closed by sachinraja** 2022-02-20 15:08 UTC
Labels: new icon
