### ISSUE TITLE
Request: Matplotlib

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12026] opened 2024-10-16 09:16 UTC
### Brand Name

Matplotlib

### Website

https://matplotlib.org/

### Popularity Metric

Global Rank - 41935

### Official Resources for Icon and Color

https://matplotlib.org/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by adamrusted** [comment] 2024-10-16 10:02
Duplicate of #3410

**Closed by adamrusted** 2024-10-16 10:02 UTC
Labels: new icon
