### ISSUE TITLE
Add icon: openscad

### ISSUE THREAD

**Issue by 21st-centuryman** [simple-icons/simple-icons#8317] opened 2023-02-06 14:33 UTC
### Brand Name

Openscad

### Website

https://openscad.org/

### Popularity Metric

> 274,380

https://www.similarweb.com/website/openscad.org/#overview

### Official Resources for Icon and Color

![9CBA59B0-9C52-49AC-A05D-39B6D1AAE430](https://user-images.githubusercontent.com/60197499/216997708-c974e837-2e05-40c4-a472-cf3b992d8a83.png)

https://commons.m.wikimedia.org/wiki/File:Openscad.svg
#f9d72c

### Additional Comments

https://commons.m.wikimedia.org/wiki/File:Openscad.svg

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-02-06 15:10
Duplicate of #6809

**Closed by service-paradis** 2023-02-06 15:10 UTC
Labels: new icon
