### ISSUE TITLE
Request: Disney+

### ISSUE THREAD

**Issue by volcachi** [simple-icons/simple-icons#7430] opened 2022-05-20 02:09 UTC
### Brand Name

Disney+

### Website

https://www.disneyplus.com/

### Popularity Metric

365.7M

### Official Resources for Icon and Color

svg: https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney%2B_logo.svg

### Contributing

Yes

**Comment by sisp** [comment] 2022-05-20 14:18
What's the popularity metric you're referring to with "365.7M"?

**Comment by service-paradis** [comment] 2022-05-20 16:23
Duplicate of https://github.com/simple-icons/simple-icons/issues/2309, https://github.com/simple-icons/simple-icons/issues/3493, https://github.com/simple-icons/simple-icons/issues/3693, https://github.com/simple-icons/simple-icons/issues/5327, https://github.com/simple-icons/simple-icons/issues/5443, https://github.com/simple-icons/simple-icons/issues/6352.

Disney are super strict about their brands, and as such we will not be adding them to this project.

**Closed by service-paradis** 2022-05-20 16:23 UTC
Labels: new icon
