### ISSUE TITLE
Adding Materialize CSS logo

### ISSUE THREAD

**Issue by tomatopickle** [simple-icons/simple-icons#5413] opened 2021-04-05 15:24 UTC
**Brand Name: Materialiaze CSS**
**Website: https://materializecss.com/**
**Alexa rank: 18,178**
  

**Official resources for icon and color: Logo:https://materializecss.com/res/materialize.svg, color:#ee6e73**
  
  

Materialize CSS is a popular open source framework that uses material UI guidelines.
Thanks

**Comment by PeterShaggyNoble** [comment] 2021-04-12 13:44
Duplicate of #3203

**Closed by PeterShaggyNoble** 2021-04-12 13:44 UTC
Labels: new icon
