### ISSUE TITLE
Please add Pinia icon

### ISSUE THREAD

**Issue by aliston-gomes** [simple-icons/simple-icons#9948] opened 2023-11-28 18:24 UTC
### Brand Name

Pinia

### Website

https://pinia.vuejs.org

### Popularity Metric

.

### Official Resources for Icon and Color

https://pinia.vuejs.org

### Additional Comments

.

**Comment by PeterShaggyNoble** [comment] 2023-11-28 18:29
Duplicate of #7498

**Closed** 2023-11-28 18:29 UTC
Labels: new icon
