### ISSUE TITLE
Request: Restful API

### ISSUE THREAD

**Issue by soubhatta** [simple-icons/simple-icons#12049] opened 2024-10-16 11:54 UTC
### Brand Name

Restful API

### Website

https://restfulapi.net/

### Popularity Metric

Global Rank - 324702

### Official Resources for Icon and Color

https://restfulapi.net/

### Additional Comments

Please Include this badge in your website - https://badges.pages.dev/

**Comment by uncenter** [comment] 2024-10-16 12:03
Duplicate of #3773.

**Closed by uncenter** 2024-10-16 12:03 UTC
Labels: new icon
