### ISSUE TITLE
Request: Tistory

### ISSUE THREAD

**Issue by happylie** [simple-icons/simple-icons#7195] opened 2022-03-05 08:53 UTC
### Brand Name

Tistory

### Website

https://www.tistory.com

### Popularity Metric

- https://www.similarweb.com/website/tistory.com/#overview
- https://www.alexa.com/siteinfo/tistory.com

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by sachinraja** [comment] 2022-03-06 05:44
duplicate of #6963

**Comment by sachinraja** [comment] 2022-03-06 05:45
Duplicate of #6963

**Closed by sachinraja** 2022-03-06 05:44 UTC
Labels: new icon
