### ISSUE TITLE
Request: Add gRPC icon

### ISSUE THREAD

**Issue by riZZZhik** [simple-icons/simple-icons#7304] opened 2022-04-09 12:56 UTC
### Brand Name

gRPC

### Website

https://grpc.io

### Popularity Metric

34k stars on GitHub: https://github.com/grpc/grpc
#155,066 rank on Similarweb

### Official Resources for Icon and Color

I wasn't able to find SVG.
Png examples available on their Website.

### Contributing

Yes

**Comment by riZZZhik** [comment] 2022-04-09 13:03
Unofficial SVG icon and colours: https://cncf-branding.netlify.app/projects/grpc/

**Comment by sisp** [comment] 2022-04-09 15:43
Duplicate of #6275.

**Closed** 2022-04-10 04:24 UTC
Labels: new icon
