### ISSUE TITLE
Request: VSCodium

### ISSUE THREAD

**Issue by BGTECH-PRO** [simple-icons/simple-icons#7690] opened 2022-08-22 15:13 UTC
### Brand Name

VSCodium

### Website

https://vscodium.com/

### Popularity Metric

https://www.similarweb.com/website/vscodium.com/#overview

### Official Resources for Icon and Color

![codium](https://user-images.githubusercontent.com/49822283/185955813-56184187-8f3c-4e09-9bf5-4b4863e221e3.png)

### Additional Comments

I really love VSCodium, I would love to show that on github by making a badge.

### Contributing

No

**Comment by service-paradis** [comment] 2022-08-25 00:52
Duplicate of #7434

**Closed by service-paradis** 2022-08-25 00:52 UTC
Labels: new icon
