### ISSUE TITLE
google developer group logo

### ISSUE THREAD

**Issue by AbhishekPratap05** [simple-icons/simple-icons#11725] opened 2024-09-04 17:05 UTC
### Brand Name

google developer group

### Website

https://gdg.community.dev/

### Popularity Metric

https://www.similarweb.com/website/developers.google.com/#overview

### Official Resources for Icon and Color

https://res.cloudinary.com/startup-grind/image/upload/dpr_2.0,fl_sanitize/v1/gcs/platform-data-goog/contentbuilder/logo_dark_QmPdj9K.svg

**Comment by uncenter** [comment] 2024-09-04 21:55
Duplicate of #9236. Please search existing issues before opening new ones!

**Closed by uncenter** 2024-09-04 21:55 UTC
Labels: new icon
