### ISSUE TITLE
Icon Request: RustDesk

### ISSUE THREAD

**Issue by josephjosedev** [simple-icons/simple-icons#8190] opened 2023-01-01 06:51 UTC
### Brand Name

RustDesk

### Website

https://rustdesk.com/

### Popularity Metric

rank 84,552

### Official Resources for Icon and Color

https://rustdesk.com/

### Contributing

No

**Comment by service-paradis** [comment] 2023-01-09 15:00
Duplicate of #7534

**Closed by service-paradis** 2023-01-09 15:00 UTC
Labels: new icon
