### ISSUE TITLE
Request: LlamaIndex

### ISSUE THREAD

**Issue by himself65** [simple-icons/simple-icons#12089] opened 2024-10-27 09:33 UTC
### Brand Name

LlamaIndex

### Website

https://llamaindex.ai/

### Popularity Metric

Global rank 87,228
Country rank 70,079
Industry rank 640

https://pypistats.org/packages/llama-index Downloads last week: ~620k

### Official Resources for Icon and Color

https://github.com/run-llama/logos/blob/main/LlamaSquareBlack.svg

**Comment by service-paradis** [comment] 2024-10-28 15:27
Duplicate of https://github.com/simple-icons/simple-icons/issues/11081

**Closed by service-paradis** 2024-10-28 15:27 UTC
Labels: new icon

**Comment by GeorgVolkov** [comment] 2024-10-28 19:01
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
