### ISSUE TITLE
ParcelJS Logo not found and ExpressJS as well.

### ISSUE THREAD

**Issue by salihcodev** [simple-icons/simple-icons#3781] opened 2020-10-29 19:10 UTC
**Name:** ParcelJS
**Website:** https://parceljs.org
**Alexa rank:**
  

**Official resources for icon and color:** #21374b

**Comment by NovaGL** [comment] 2020-11-02 07:28
Duplicate of #3482 and #2924

**Closed by NovaGL** 2020-11-02 07:28 UTC
Labels: new icon
