### ISSUE TITLE
Request: Jetbrains Rider

### ISSUE THREAD

**Issue by Taucher2003** [simple-icons/simple-icons#4913] opened 2021-02-03 15:00 UTC
**Brand Name:** Rider (made by Jetbrains)
**Website:** https://www.jetbrains.com/rider/
**Alexa rank:** 203.9 k (this is the rank from the jetbrains website)
  

**Official resources for icon and color:** https://www.jetbrains.com/rider/
  
  

As there are already IntelliJ IDEA, PhpStorm, WebStorm, PyCharm added to the list, I think the other programs could also be added. I wanted to request the Rider icon because I use the program and would add it to my profile readme.

**Comment by PeterShaggyNoble** [comment] 2021-02-03 15:14
Duplicate of #3488

**Closed by PeterShaggyNoble** 2021-02-03 15:14 UTC
Labels: new icon

**Comment by Taucher2003** [comment] 2021-02-03 15:37
whooops, didn't see that while looking through the other issues
