### ISSUE TITLE
CorelDRAW Icon

### ISSUE THREAD

**Issue by welenkens** [simple-icons/simple-icons#10411] opened 2024-02-07 21:08 UTC
### Brand Name

CorelDRAW

### Website

https://www.coreldraw.com/

### Popularity Metric

![coreldraw](https://github.com/simple-icons/simple-icons/assets/69676449/608c6b92-451c-44b9-b49b-6555e0a2d7c5)

**Comment by PeterShaggyNoble** [comment] 2024-02-07 21:22
Duplicate of #5290

**Closed** 2024-02-07 21:22 UTC
Labels: new icon
