### ISSUE TITLE
Redmine logo

### ISSUE THREAD

**Issue by RishoT17** [simple-icons/simple-icons#6357] opened 2021-08-23 09:42 UTC
**Brand Name:** Remine
**Website:** https://www.redmine.org/
**Alexa rank:** 77,615

**Official resources for icon and color:**
https://www.redmine.org/projects/redmine/wiki/logo
https://commons.wikimedia.org/wiki/File:Redmine_logo.svg

**Comment by gizmecano** [comment] 2021-08-23 10:25
Duplicate of #6309 (cf. #6326 for recent pull request)

**Closed** 2021-08-23 12:56 UTC
Labels: new icon, duplicate
