### ISSUE TITLE
Twitter (X) has update

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [simple-icons/simple-icons#9185] opened 2023-08-01 01:49 UTC
### Brand Name

Twitter (Old name)
It named "X" now!

### Official Resources for Icon and Color

[x.com](https://x.com) (twitter.com)
`<svg viewBox="0 0 24 24" aria-hidden="true" class="r-18jsvk2 r-4qtqp9 r-yyyyoo r-16y2uox r-8kz0gk r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-lrsllp"><g><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></g></svg>`
 color: 000000
### Additional Comments

Bird has dead
X now！

### Contributing

Yes

**Comment by BUGProtectionAssociation** [comment] 2023-08-01 01:58
Add a new icon named X...or update this old bird icon

![image](https://github.com/simple-icons/simple-icons/assets/65578116/273a1973-e032-4b81-aac6-b342e33bf718)

**Comment by LitoMore** [comment] 2023-08-01 08:14
Duplicate of #9099.

**Closed by LitoMore** 2023-08-01 08:14 UTC
Labels: icon outdated
