### ISSUE TITLE
Icon Request for Zustand

### ISSUE THREAD

**Issue by usmanabdurrehman** [simple-icons/simple-icons#10196] opened 2023-12-31 09:26 UTC
### Brand Name

Zustand

### Website

https://docs.pmnd.rs/zustand/getting-started/introduction

### Popularity Metric

https://github.com/pmndrs/zustand
38k Stars

### Official Resources for Icon and Color

None

**Comment by adamrusted** [comment] 2023-12-31 09:39
Duplicate of #7847

**Closed by adamrusted** 2023-12-31 09:39 UTC
Labels: new icon
