### ISSUE TITLE
URI Online Judge

### ISSUE THREAD

**Issue by AugustoEstevaoMonte** [simple-icons/simple-icons#3423] opened 2020-08-05 00:41 UTC
**Name:** Augusto Estevão Monte
**Website:** https://www.urionlinejudge.com.br/judge/pt
**Alexa rank:**
  

**Official resources for icon and color:**

**Comment by runxel** [comment] 2020-08-13 15:16
Hi @AugustoEstevaoMonte, thanks for this request.
I'm not familiar with the brand. Is this really their logo?
![logo-big](https://user-images.githubusercontent.com/2277182/90152871-94cd6180-dd88-11ea-8467-35a24ae4e3c8.png)

There seems to be no vectorized version around – will be quite hard to vectorize this one by hand.



The [alexa rank](https://www.alexa.com/siteinfo/urionlinejudge.com.br) is at ~171K.

**Comment by AugustoEstevaoMonte** [comment] 2020-08-13 15:45
Yes @runxel , this is their logo.

**Comment by runxel** [comment] 2020-08-13 16:16
Thanks clarification, @AugustoEstevaoMonte.

**Comment by jorgeamadosoria** [comment] 2021-10-03 20:09
Closed as obsolete duplicate of #6647 (Uri Online Judge soon to happen rebranding)

**Closed** 2021-10-04 13:44 UTC
Labels: new icon
