### ISSUE TITLE
Prolog Programming Language Icon

### ISSUE THREAD

**Issue by cr2007** [simple-icons/simple-icons#9106] opened 2023-07-25 11:49 UTC
### Brand Name

Prolog

### Website

https://www.swi-prolog.org/

### Popularity Metric

Similarweb Rank: 331,179

It's a functional programming language that is widely used in the development space.

### Official Resources for Icon and Color

https://www.swi-prolog.org/download/logo/

### Contributing

No

**Comment by service-paradis** [comment] 2023-07-25 16:42
Duplicate of #6110

**Closed by service-paradis** 2023-07-25 16:42 UTC
Labels: new icon
