### ISSUE TITLE
BrowserStack

### ISSUE THREAD

**Issue by dhruvkb** [simple-icons/simple-icons#5503] opened 2021-04-21 17:32 UTC
**Brand Name:** BrowserStack
**Website:** https://www.browserstack.com
**Alexa rank:** 6112
  

**Official resources for icon and color:**
  
Could not find any. The logo in the site-header is an SVG though.

**Comment by PeterShaggyNoble** [comment] 2021-04-21 17:34
Duplicate of #4668

**Closed by PeterShaggyNoble** 2021-04-21 17:34 UTC
Labels: new icon
