### ISSUE TITLE
REQUEST A FEATURE TO ADD THE OFFICIAL MIDJOURNEY LOGO for Simple Icons.

### ISSUE THREAD

**Issue by mjneuroart** [simple-icons/simple-icons#10359] opened 2024-01-25 14:30 UTC
### Brand Name

Midjourney

### Website

https://www.midjourney.com

### Popularity Metric

The Similarweb rank global for Midjourney is 1602, see : https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/3m?webSource=Total&key=midjourney.com

### Official Resources for Icon and Color

![Midjourney](https://github.com/simple-icons/simple-icons/assets/151175632/df9946fe-4db4-4314-af89-9c73b201efbc)
![Midjourney](https://github.com/simple-icons/simple-icons/assets/151175632/ba847266-d5fa-4cf2-bb98-50708a85fbb0)
[Midjourney.pdf](https://github.com/simple-icons/simple-icons/files/14053260/Midjourney.pdf)

https://docs.midjourney.com/docs/trademark-policy

### Additional Comments

for the icon, i would like it as it is displayed in the pdf, I don't know why svg and png display it weirdly. Maybe I'm wrong. I need it because I use Framer website builder and in a component when I browse simple icons list, I don't find MidJourney icon.

![image](https://github.com/simple-icons/simple-icons/assets/151175632/66917a28-5a11-4501-bb7a-bd524e061b56)
![image](https://github.com/simple-icons/simple-icons/assets/151175632/0f5e83ef-3b85-4712-a2bd-7fedf2ac41ed)

**Comment by PeterShaggyNoble** [comment] 2024-01-25 14:33
Duplicate of #8753

**Closed** 2024-01-25 14:33 UTC
Labels: new icon
