### ISSUE TITLE
Autodesk - Fusion 360 icon

### ISSUE THREAD

**Issue by Skyler-Guha** [simple-icons/simple-icons#9515] opened 2023-09-09 16:01 UTC
### Brand Name

Fusion 360

### Website

https://www.autodesk.in/products/fusion-360/overview?term=1-YEAR&tab=subscription

### Popularity Metric

https://www.trustradius.com/products/autodesk-fusion-360/reviews?qs=pros-and-cons#overview

### Official Resources for Icon and Color

None

### Additional Comments

Fusion 360 is a product of the company Autodesk. It is the most widely used 3D cad software out there. Icon for Autodesk the company already exists, but I could not find any icon for fusion 360. This icon would look good: https://play-lh.googleusercontent.com/WVl18ugl3adNd8rjRQUJwnmt5VeiSf-7GSv7Fae8vbKywECFwsYXbD43buTZCmAR11ht

### Contributing

Yes

**Comment by adamrusted** [comment] 2023-09-10 10:18
Duplicate of #8279.

**Closed** 2023-09-10 10:18 UTC
Labels: new icon
