### ISSUE TITLE
Clip Studio Paint

### ISSUE THREAD

**Issue by LM-ANT** [simple-icons/simple-icons#8134] opened 2022-12-13 13:10 UTC
### Brand Name

Clip Studio Paint

### Website

https://www.clipstudio.net/

### Popularity Metric

https://www.similarweb.com/fr/website/clipstudio.net

### Official Resources for Icon and Color

None

### Contributing

Yes

**Comment by service-paradis** [comment] 2023-05-23 12:43
Duplicate of #7656

**Closed by service-paradis** 2023-05-23 12:43 UTC
Labels: new icon
